### ISSUE TITLE
I noticed a bug with the shutdown of any server !!!

### ISSUE THREAD

**Issue by The-Emperator** [SmartlyDressedGames/Unturned-3.x-Community#2438] opened 2021-02-26 19:54 UTC
The bug is that when a person dies at the same time is teleported by the /home command-the Server Shuts down.
Video:
https://disk.yandex.ru/i/6bk_NSqHtl7SNg

**Comment by SDGNelson** [comment] 2021-02-26 20:00
Closing because this is a duplicate of #2437

**Closed by SDGNelson** 2021-02-26 20:00 UTC
