### ISSUE TITLE
Level failing to load

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#4091] opened 2023-08-31 21:31 UTC
I've had this happen a few times now - I think it's being caused by players putting symbols on signs?
<img width="336" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/fb673324-fc74-4250-b8a8-5318a95259f6">
Here's a link to the barricades.dat: https://filebin.net/o69t22opoi1dkv42/Barricades.dat

**Comment by SDGNelson** [comment] 2023-09-01 21:27
Do you have any plugins that patch barricade data? That's one common cause, particularly "AVI" plugins. Symbols on signs shouldn't cause any special problems - the text is encoded as UTF8 regardless of symbols. The game also checks that the encoded length will not exceed 230 bytes.

**Comment by AdamDN** [comment] 2023-09-01 23:07
Nope, no AVI plugins and no other plugins that should be altering barricade data (to my knowledge). 
We do have a uScript that updates sign text when a player logs out - but that also has checks to ensure it's well within the character limit before making any changes.
Just to double check, is the issue definitely related to signs - or could it be anything else?

**Comment by DanielWillett** [comment] 2023-09-04 05:24
The error is caused by your barricade file becoming corrupted somehow, not necessarily signs.

**Comment by SDGNelson** [comment] 2023-09-04 19:08
Does your script check the string.Length, or does it check the number of UTF8 encoded bytes? For example, a string with Length 64 could surpass the buffer length if each character is encoded as 4 bytes.

**Comment by AdamDN** [comment] 2023-09-04 20:14
The script checks string.Length of the player's name and trims it down to 18 characters if necessary (to better fit on one line) then appends either 86 or 94 characters depending on the context - so it should still be within the limit even if all 18 characters of their name are encoded as 4 bytes, right? 
As far as I can tell though the script changing the signs text isn't the cause of the issue - I've done some testing trying to force a sign over the byte limit and haven't been able to intentionally corrupt anything. 
the server has been fine and playable until it's restarted, the issue is always on level load

I'm not certain that signs are even related, I'm just assuming they're the cause because of the "Destination buffer is too small" line

**Comment by SDGNelson** [comment] 2023-09-05 01:38
You're right the signs could be completely unrelated.

I loaded up the Barricades.dat file and the previous barricade before the one that breaks is a Pine Crate with seemingly valid properties. Then the next region must be corrupted because it has 10,752 barricades. The first one has guid 000500643f00010064000600003f0001 and likely invalid properties.

Something could have gone wrong and the file got corrupted during save or sometime after save. Do you have any storage-related plugins that could have broken the Pine Crate's state?

**Comment by AdamDN** [comment] 2023-09-05 22:33
Nope, no plugins that should be affecting pine crates or any storages at all.
I have a build logs showing 6 Pine Crates being destroyed (at coordinates -800, 41, 605, which should be outside of the region that has 10k barricades) about 6 hours before the server restarted and started having this issue. But other than that, I can't imagine why pine crates (or any storages) would be having any issues.

I've just found a previous barricades.dat from 2 weeks earlier which also had the same issue, if you'd like to compare them.
https://filebin.net/01fcx0qcne6fxkwm/Barricades.dat

If you're able to identify the GUID of a corrupted barricade, is it possible to fix/remove/skip the barricade during level load?

**Comment by DanielWillett** [comment] 2023-09-05 23:47
You most likely don't have a region with 10k barricades, which is why he thinks the pine crate corrupted it. For reference, this is the size of a region (the small grey squares)

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/e2b48105-2ca9-4a51-996c-cc25f1b6517d)

**Comment by AdamDN** [comment] 2023-09-06 00:10
You're right, the 10k number didn't click.
I was thinking of map tiles rather than regions - the southwestern _tile_ has had a combined 10k barricades total in the past so it didn't sound too crazy, but in both the barricades.dat above the total is probably closer to 4k with no individual region higher than 1.5k.

**Comment by SDGNelson** [comment] 2023-09-06 03:17
> If you're able to identify the GUID of a corrupted barricade, is it possible to fix/remove/skip the barricade during level load?

That's the point at which the save starts being nonsense, but there's no way for the game to know that.

Has it been happening often? (Since you mentioned a similar save file?) I expect a save-breaking bug would be widely reported, so this also makes me think it must be related to your setup / mods / plugins. Though maybe other hosts are running into the same problem? In the past though if there's been a save issue I've received lots of messages.

**Comment by AdamDN** [comment] 2023-09-06 14:02
I've seen it 3 times in the last 3 months. Once a couple months ago, then twice in the last 2 weeks.

All 3 occurrences have been on the same server so I don't think it's wide-spread, and I can definitely believe it's a plugin causing the issue - but the server is setup/plugins are identical to a second server which hasn't experienced this, and none of the plugins should be altering barricades/storages/signs at all. Both servers have been running the same setup for a couple years now and there hasn't been any recent changes that could have set it off. The only difference between the two servers is the one with issues is Windows and the other is Linux. 

Actually, could this be related to patch 3.23.7.0 closing/saving windows servers?
I've just grabbed the last log from before the .dat corrupted, the had server crashed and judging by logs there had been no autosaves for 3 hours until I manually closed the server.


```
[2023-08-31 08:16:27 INF][OpenMod.Core.Commands.CommandExecutor] Actor player/некит (76561199535410500) has executed command "home"
[2023-08-31 08:16:56 INF][RocketMod] AdvancedRegions >> Player frololow has left region __global
[2023-08-31 08:16:56 INF][SDG.Unturned] Disconnecting: PlayerID: 76561199535410500 Name: frololow Character: некит
[2023-08-31 08:16:56 INF][SDG.Unturned] BattlEye Server: Player #1 frololow disconnected
[2023-08-31 08:18:07 INF][SDG.Unturned] BattlEye Server: Failed to receive from BE Master (0)
[2023-08-31 08:18:07 INF][SDG.Unturned] BattlEye Server: Disconnected from BE Master
[2023-08-31 08:18:08 INF][RocketMod] Yeeti >> [Fatal] System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine.
                                                                                                                                                                                   . ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine.
                                                                                                                                                                                   
  at System.Net.Sockets.Socket.EndReceive (System.IAsyncResult asyncResult) [0x00012] in <39d8670c8f6e487fb992d3c14d754584>:0 
  at System.Net.Sockets.NetworkStream.EndRead (System.IAsyncResult asyncResult) [0x00057] in <39d8670c8f6e487fb992d3c14d754584>:0 
   --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.EndRead (System.IAsyncResult asyncResult) [0x0009b] in <39d8670c8f6e487fb992d3c14d754584>:0 
  at WebSocketSharp.Ext+<>c__DisplayClass9.<ReadBytesAsync>b__8 (System.IAsyncResult ar) [0x00002] in <c38b489757264127979e0419ce4762ab>:0 
[2023-08-31 08:18:08 INF][RocketMod] Yeeti >> Disconnected [1006]: An exception has occurred while receiving.
[2023-08-31 08:18:08 INF][RocketMod] Yeeti >> Reconnecting...
[2023-08-31 08:18:08 INF][RocketMod] Yeeti >> [Warn] The current logging level has been changed to Warn.
[2023-08-31 11:13:04 INF][RocketMod] Saving server

```

**Comment by SDGNelson** [comment] 2023-09-06 14:50
The Windows server saving change only applies when clicking the quit X button and it would log something about handling SIGINT / SIGBREAK.

Unfortunately, no good ideas come to mind for tracking this down. It's infrequent enough that trying turning some plugins/mods on/off seems impractical. If you'd like to send the full server log from the run where the file gets saved as corrupted I can take a look.

The game really needs an auto backup saves feature, but perhaps for the meantime you could have periodic backups of the Barricades.dat file?

**Comment by AdamDN** [comment] 2023-09-06 15:30
> The Windows server saving change only applies when clicking the quit X button and it would log something about handling SIGINT / SIGBREAK.

The X quit button was definitely clicked in this case, as the server had crashed and a shutdown command wouldn't have executed. I've just closed the server using the X button to test and I can't see any logs mentioning "SIGINT / SIGBREAK" in the server.log rocket.log or openmod.log? 

> The game really needs an auto backup saves feature, but perhaps for the meantime you could have periodic backups of the Barricades.dat file? 

I've got auto daily backups of everything, but I guess I could make them more frequent - a built in feature would be good for the future

**Comment by SDGNelson** [comment] 2023-09-07 15:04
> The X quit button was definitely clicked in this case, as the server had crashed and a shutdown command wouldn't have executed.

By crashed do you mean it was frozen / wasn't responding? If so, the main thread being blocked would prevent the game from doing anything when X was clicked. Perhaps whatever blocked the main thread is related to the issue. Was there any context in the log of what it was in the middle of doing?

**Comment by AdamDN** [comment] 2023-10-14 19:10
Sorry for the late reply, I completely forgot this issue was open until today.
Today/last night 4 of my servers have experienced corrupted barricade.dat's either caused by, or related to, the latest Unturned update. 
I'm even more at a loss for what could be causing this now that it's affecting multiple servers. There isn't a single common element between all 4 of them other than them all being Windows servers.

> By crashed do you mean it was frozen / wasn't responding? 

The most common "crash" that I experience on the server that I was originally talking about involves the following: All players lose connection, the server still appears online, players cannot connect (error: This server lost your connection.), the server still appears fully functional from the console (I'll see timed broadcasts and airdrops are still coming through), but the console won't allow any commands to be sent which forces me to use the X to shutdown the server.

> If so, the main thread being blocked would prevent the game from doing anything when X was clicked. 

Every time this has happened, Structures and Vehicles have saved correctly. It's only Barricades that get corrupted, so I don't think it's this.

> Perhaps whatever blocked the main thread is related to the issue. Was there any context in the log of what it was in the middle of doing?

I've attached 2 openmod logs (the end of one log, then a full second log) from last night's update.
In this instance the X button wasn't used, the server was safely shutdown using a command.
[openmod-2023-10-12-19-29-28.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/12907647/openmod-2023-10-12-19-29-28.log)
[openmod-2023-10-13-13-40-34.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/12907648/openmod-2023-10-13-13-40-34.log)
There's no errors during the last automated server save, or while shutting down the server (at least before OM shutdown). And the errors post-update are plugin related, not level related.

**Comment by SDGNelson** [comment] 2023-10-16 18:59
@AdamDN Sorry, I think I've already forgotten some of the context I was thinking around this. From your description it doesn't sound like the main thread is getting blocked, otherwise it wouldn't be logging any shutdown messages.

The first log mentions saving, but the second one doesn't. Did it run into any exceptions while saving? Since the original post mentions an exception when loading the barricades. Or does it run into the exception when loading after that despite no saving exception?

**Comment by AdamDN** [comment] 2023-10-17 02:17
I'm not sure if I understand the question. I haven't seen any exceptions while saving, and the second log doesn't mention saving because the level hadn't finished loading past 94%. 
There's this in the server.log after leaving the server online for log enough that it attempts an autosave: 
[2023-10-15 15:52:50] Ignoring request to save before level finished loading
But that just seems sensible, and it's the only mention of saving. 

> Since the original post mentions an exception when loading the barricades. Or does it run into the exception when loading after that despite no saving exception?

The error message was still the same as the original post, it's just not logged in openmod logs or server.log, it's only visible in console hence the screenshot rather than a copy+paste.

I've already loaded backups for the affected servers, but if the issue happens again is there anything else I can provide to help track down the cause?

**Comment by SDGNelson** [comment] 2023-11-07 02:18
Sorry, I thought I'd responded to this. Unfortunately, I don't really have any ideas except that I do want to rewrite parts of the barricade features and this would be another good reason to work on that.

There were problems with signs after this most recent update because I added a main thread check to a method used by a popular sign-related plugin. (the plugin was using the network connection list pool from a different thread) I don't suppose that fixed this?

**Comment by AdamDN** [comment] 2023-11-08 20:05
It sounds unlikely to have fixed it, as we don't use any sign related plugins - the only thing effecting signs on a _couple_ of the servers that were effected was a uScript script. 

But then again, it's really hard to tell whether any changes have fixed the issue since it happens pretty infrequently.. It hasn't happened again since, so it's possible everything is fixed 🤷‍♂️ it's hard to know for sure.

**Comment by SDGNelson** [comment] 2023-11-08 22:24
Thanks for the update. Well, hopefully it's miraculously fixed. 😟

**Comment by SDGNelson** [comment] 2023-12-13 22:01
Closing since it hasn't come up again, but the barricade rewrite is still on my mind - just a question of what will get prioritized next.

**Closed by SDGNelson** 2023-12-13 22:01 UTC
Labels: Pending response from issue poster
