### ISSUE TITLE
Weapon UI still showing, even after dying.

### ISSUE THREAD

**Issue by Lakmejrup** [SmartlyDressedGames/Unturned-3.x-Community#2138] opened 2020-12-04 18:11 UTC
Picked up a heartbreaker, died and after respawning the UI is still there.
Tried picking up a 1911 after that, and the 1911 UI overlapped with the heartbreaker ui. 
![20201204185916_1](https://user-images.githubusercontent.com/63169450/101198959-87542400-3664-11eb-93c5-418e948646f1.jpg)

**Comment by SDGNelson** [comment] 2020-12-04 18:16
Can you attach your Client.log file please? I was unable to reproduce this, but there will probably be some sort of error in the log.

**Comment by Lakmejrup** [comment] 2020-12-04 18:20
Yup, here you go
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5644607/Client.log)

**Comment by SDGNelson** [comment] 2020-12-04 18:32
Thanks for the log! There are a few exceptions, so I am copying them here for my reference:

[2020-12-04 18:57:58]   at SDG.Unturned.GlazierBase_uGUI.set_isVisible (System.Boolean value) [0x00006] in <9d9d689f237446c29d18b969b9b82c89>:0 
  at SDG.Unturned.UseableGun.tick () [0x00eb3] in <9d9d689f237446c29d18b969b9b82c89>:0 
  at SDG.Unturned.PlayerEquipment.Update () [0x0025e] in <9d9d689f237446c29d18b969b9b82c89>:0 

[2020-12-04 18:57:58]   at (wrapper managed-to-native) UnityEngine.Transform.GetParent(UnityEngine.Transform)
  at UnityEngine.Transform.get_parentInternal () [0x00001] in <f15e66ec8bac455da00fc30eb5e18d09>:0 
  at UnityEngine.Transform.get_parent () [0x00001] in <f15e66ec8bac455da00fc30eb5e18d09>:0 
  at SDG.Unturned.GlazierBase_uGUI.RemoveChild (SDG.Unturned.ISleekElement child) [0x0002f] in <9d9d689f237446c29d18b969b9b82c89>:0 
  at SDG.Unturned.SleekWrapper.RemoveChild (SDG.Unturned.ISleekElement sleek) [0x00000] in <9d9d689f237446c29d18b969b9b82c89>:0 
  at SDG.Unturned.UseableGun.tick () [0x00e93] in <9d9d689f237446c29d18b969b9b82c89>:0 
  at SDG.Unturned.PlayerEquipment.Update () [0x0025e] in <9d9d689f237446c29d18b969b9b82c89>:0 

[2020-12-04 18:59:10] NullReferenceException: Object reference not set to an instance of an object
[2020-12-04 18:59:10] SDG.Unturned.UseableGun.updateCrosshair () (at <9d9d689f237446c29d18b969b9b82c89>:0)
SDG.Unturned.PlayerStance.internalSetStance (SDG.Unturned.EPlayerStance newStance) (at <9d9d689f237446c29d18b969b9b82c89>:0)
SDG.Unturned.PlayerStance.checkStance (SDG.Unturned.EPlayerStance newStance, System.Boolean all) (at <9d9d689f237446c29d18b969b9b82c89>:0)
SDG.Unturned.PlayerStance.checkStance (SDG.Unturned.EPlayerStance newStance) (at <9d9d689f237446c29d18b969b9b82c89>:0)
SDG.Unturned.PlayerStance.simulate (System.UInt32 simulation, System.Boolean inputCrouch, System.Boolean inputProne, System.Boolean inputSprint) (at <9d9d689f237446c29d18b969b9b82c89>:0)
SDG.Unturned.PlayerInput.FixedUpdate () (at <9d9d689f237446c29d18b969b9b82c89>:0)

**Comment by Lakmejrup** [comment] 2020-12-04 18:35
No problemo

**Comment by SDGNelson** [comment] 2020-12-04 19:31
Turns out it was all caused by the rangefinder attachment. Will be fixed in the .1 patch later this afternoon

**Closed by SDGNelson** 2020-12-04 19:31 UTC
Labels: Next Patch
