### ISSUE TITLE
Server was listed without workshop items, but requested workshop downloads.

### ISSUE THREAD

**Issue by lefondo** [SmartlyDressedGames/Unturned-3.x-Community#3585] opened 2022-12-16 20:32 UTC
How do I fix this issue?

**Comment by sunnamed434** [comment] 2022-12-16 20:35
This is your server?

**Comment by lefondo** [comment] 2022-12-16 20:58
Yep, my server

**Comment by sunnamed434** [comment] 2022-12-16 21:00
Could you send please the `WorkshopDownloadConfig.json` from your server, do you have plugins that can cause that problem?

**Comment by lefondo** [comment] 2022-12-16 21:01
{
  "Workshop": true,
  "File_IDs": [1116598620, 1951390397, 2055883148, 2079947828, 2079950203, 2079953791, 2081272257, 2092219945, 2099073425, 2101269463, 2110692744, 2142699307, 2144646099, 2150330550, 2153272553, 2155605291, 2202393257, 2876376295, 496514336, 877777769],
  "Ignore_Children_File_IDs": [],
  "Query_Cache_Max_Age_Seconds": 600,
  "Max_Query_Retries": 2,
  "Use_Cached_Downloads": true,
  "Should_Monitor_Updates": true,
  "Shutdown_Update_Detected_Timer": 600,
  "Shutdown_Update_Detected_Message": "Workshop file update detected, shutdown in: {0}",
  "Shutdown_Kick_Message": "Shutdown for Workshop file update."
}

**Comment by sunnamed434** [comment] 2022-12-16 21:03
> "File_IDs": [1116598620, 1951390397, 2055883148, 2079947828, 2079950203, 2079953791, 2081272257, 2092219945, 2099073425, 2101269463, 2110692744, 2142699307, 2144646099, 2150330550, 2153272553, 2155605291, 2202393257, 2876376295, 496514336, 877777769],

Here we are, you have specified which workshop IDs will be installed on your server, so every client should also install these things

**Comment by lefondo** [comment] 2022-12-16 21:04
I have every mod installed on the PC I want to play from

**Comment by lefondo** [comment] 2022-12-16 21:07
I just have to enable the workshop somehow. I added the "Workshop": true, thing after I saw it in a reddit post about the same issue but it doesn't work.

**Comment by sunnamed434** [comment] 2022-12-16 21:16
> I just have to enable the workshop somehow. I added the "Workshop": true, thing after I saw it in a reddit post about the same issue but it doesn't work.

I don't think that 'Workshop:true' argument plays something this is Json as I see and it should be 'Workshop:false' by default, idk probably in Unturned by default this argument is ignored or even does not exist, I don't have now access to the "source-code" of Unturned, sadly

**Comment by lefondo** [comment] 2022-12-16 21:27
Thank you for offering help, the problem fixed itself after I restarted the server a couple of times!

**Comment by SDGNelson** [comment] 2022-12-16 22:14
Glad to hear it started working!
To clarify: this happens if the advertisement for the server does not have workshop files listed. Most commonly this was caused by plugins that modify the server listing in particular to hide workshop files.

**Closed by SDGNelson** 2022-12-16 22:14 UTC
