### ISSUE TITLE
[Feature Request] Shoot Animation Hook

### ISSUE THREAD

**Issue by RexmecK** [SmartlyDressedGames/Unturned-3.x-Community#2741] opened 2021-08-05 10:50 UTC
I haven't been able to find a animation or a hook to able to play a custom shooting animations inside of the model. 
So far I've been working on this.
![AnimationCobra](https://user-images.githubusercontent.com/22859225/128338115-e8a8bfa9-6e5d-4773-9b91-a927742645cc.gif)

**Comment by SDGNelson** [comment] 2021-08-05 16:25
Sorry, there is a plan for this [on the roadmap](https://trello.com/c/scIWKQUe/13-equipment-animation), but no ETA yet. Closing as duplicate of #2740

**Closed by SDGNelson** 2021-08-05 16:25 UTC
