### ISSUE TITLE
Admin editor not working

### ISSUE THREAD

**Issue by ElRicki7u7** [SmartlyDressedGames/Unturned-3.x-Community#2195] opened 2020-12-07 14:43 UTC
When you press Shift + F6 the editor works, but you cant select anything. (I only tested it on my own Server using RocketMod) In singleplayer works.

**Comment by CyberAndrii** [comment] 2020-12-07 15:01
Duplicate of #2152

**Comment by SDGNelson** [comment] 2020-12-07 16:47
Solution in the issue CyberAndrii linked. If that is not the case then feel free to comment there

**Closed by SDGNelson** 2020-12-07 16:47 UTC
