### ISSUE TITLE
ERROR! Failed to install app '304937' (Invalid platform)

### ISSUE THREAD

**Issue by strongunturned** [SmartlyDressedGames/Unturned-3.x-Community#687] opened 2019-03-16 13:02 UTC
Hi, our coder asked to install the platform version - 304937, but on my hosting - ERROR! Failed to install app '304937' (Invalid platform), does this platform work for someone?
<img width="391" alt="Снимок экрана 2019-03-16 в 15 58 57" src="https://user-images.githubusercontent.com/48184311/54475623-6a2e5080-4804-11e9-9c81-aa26ea5e1937.png">

**Comment by D-AIRY** [comment] 2019-03-16 13:06
You should use different executable (Unturned_Headless_LatestMono.x86) instead of different AppID

**Comment by strongunturned** [comment] 2019-03-16 13:51
@D-AIRY Something I do not understand where I find this file

**Comment by D-AIRY** [comment] 2019-03-16 13:55
It will appear in server root directory once you installed app 304930 or updated existing server
![](https://user-images.githubusercontent.com/20150321/54476265-4111be00-480c-11e9-893e-31216e83975b.PNG)

**Comment by strongunturned** [comment] 2019-03-16 14:03
@D-AIRY Please send us this file)

**Comment by strongunturned** [comment] 2019-03-16 14:04
I just don’t have it, maybe I’m doing something wrong.....

**Comment by D-AIRY** [comment] 2019-03-16 14:07
It will not work as there many dependencies. Just run steamcmd as usual.

I've assumed you want linux server. Is it right? Otherwise you already has latest mono

**Comment by strongunturned** [comment] 2019-03-16 14:11
@D-AIRY yes it happened when i try to install by id 304937. OS Ubuntu 16.04

**Comment by D-AIRY** [comment] 2019-03-16 14:13
There is my update script:
```
@sSteamCmdForcePlatformBitness 32
login login password
force_install_dir /hlds/store/dist/unity/unturned/latest/
app_update 304930
exit
```

**Comment by strongunturned** [comment] 2019-03-16 14:16
@D-AIRY ./steamcmd.sh +@sSteamCmdForcePlatformBitness 32 +login "$STEAM_USERNAME" "$STEAM_PASSWORD" +force_install_dir $UNTURNED_HOME +app_update 304937 validate +exit

my script

**Comment by D-AIRY** [comment] 2019-03-16 14:21
Use 304930 and Unturned_Headless_LatestMono.x86 will appear

**Comment by strongunturned** [comment] 2019-03-16 14:31
![IMAGE 2019-03-16 17:30:53](https://user-images.githubusercontent.com/48184311/54476674-47566900-4811-11e9-9e52-560f4a143b3f.jpg)

I do not know what to do

**Comment by D-AIRY** [comment] 2019-03-16 14:33
You use invalid appid, 304930 is the right. Forget about 304937

**Comment by Trojaner** [comment] 2019-03-16 18:13
You are using wrong install command, this is unrelated to Unturned and not a bug.
Please close the issue.

**Comment by SDGNelson** [comment] 2019-03-16 18:18
Yes, you need to use AppID 304930 with forced Linux 32 to download it. The Steam DepotID for Linux files is 304937, but it's a different command to download the depot.

**Closed by SDGNelson** 2019-03-16 18:18 UTC

**Comment by Trojaner** [comment] 2019-03-16 18:19
+force_install_dir /mnt/server +app_update 304930 304937 +quit
