### ISSUE TITLE
zombie does't walk

### ISSUE THREAD

**Issue by armychawakorn** [SmartlyDressedGames/Unturned-3.x-Community#3970] opened 2023-06-25 16:08 UTC
my server running on linux and using Arid map
sometime zombie doesn't walk
it's need to restart server to fix it

**Comment by SDGNelson** [comment] 2023-06-28 04:18
Thanks Jdance-Media , also it might be #2884

**Comment by KarmaWSYD** [comment] 2023-07-01 01:02
I'll add that I've also noticed this kind of issue on multiple maps, including Arid and A6 Polaris. In each instance, the error has been #2884 (or for the specific error log the duplicate #3611). Vanilla instances on Linux through pterodactlyl. It's a particularly annoying bug as it requires a restart to fix - and, other than setting up monitoring and restart functionality to servers that allows for a restart whenever the error is posted there isn't much that can currently be done on the server management side.

In my experience with a decent number of servers, there isn't much in terms of consistency for what causes the error. I'd suspect a specific kind of player action or zombie movement could be the cause, and indeed, it seems to occur more frequently on servers with higher player counts.

**Comment by SDGNelson** [comment] 2023-11-07 01:58
Closing because it's been a while and I think it's actually been resolved thanks to @DiFFoZ's suggested patch!

**Closed by SDGNelson** 2023-11-07 01:58 UTC
Labels: Pending response from issue poster
