### ISSUE TITLE
Lost the blowtorch icon in inventory.

### ISSUE THREAD

**Issue by WCPistolPete** [SmartlyDressedGames/Unturned-3.x-Community#2345] opened 2021-01-23 01:45 UTC
It shows only as two black boxes. Same if it's in the primary or secondary slot. Not visible in right-click information box.

**Comment by aladairmaxwell** [comment] 2021-01-23 10:34
Crossbow too.

**Comment by SDGNelson** [comment] 2021-01-23 21:49
Sorry, this will be fixed in the next patch, but holding off until next week to avoid disturbing servers over the weekend. Closing because duplicate of #2342

**Closed by SDGNelson** 2021-01-23 21:49 UTC
