### ISSUE TITLE
Steam Overlay issue still persists?!?

### ISSUE THREAD

**Issue by joeytheadmingamer** [SmartlyDressedGames/Unturned-3.x-Community#235] opened 2018-03-14 23:03 UTC
_Hello @SDGNelson , Devs, and Server Owners,

I notice we still have no resolution for the Steam Overlay being non-functional for Unturned users and I was hoping by starting a new thread that we could see some useful input and resources towards shedding light on this subject. So far we know that it has to do with recent updates, between battle eye and nelson, by meaning of that I've had several server owners disable battle eye and they were able to get the steam overlay running perfectly on Unturned. This isn't only affecting players, but this is also affecting donators,  reporters,  server staff, voters, and the amount of people that play on Unturned generally speaking.

I do understand that you are focused on the new version of Unturned that you are releasing, Nelson, but I would like for you to take some time to see that the current version does get the care that it especially needs, so that staff can take screenshots again of glitched bases, so that players can vote without using external browsers, so that donators can donate instead of using external browsers, and so that players can use webstores to buy in-game items when they want to._

Not all kids have money to buy the new version that you are releasing, when you release it so therefore most people will probably stick with the current version, please take care of it.

**Rude remarks aren't needed, I'm simply asking for a response from Nelson in relation to the game experience that is currently provided.**

**Comment by Trojaner25** [comment] 2018-03-14 23:04
Duplicate of #232 and #224 

This bug is related to Battleye, Nelson can not fix it.
Please close.

**Comment by joeytheadmingamer** [comment] 2018-03-14 23:06
@Trojaner25 Nelson can forward a request to Battleeye for a bugfix, rather sooner than later, and it is an issue that needs to be taken care of. This issue needs to be resolved and taken care of regardlessly.

**Comment by Trojaner25** [comment] 2018-03-14 23:07
- As he did already. There is nothing he, you or me can do. All we can do is to wait for Battleye to fix it.
Please close this issue as there are already 2 ones. No need to report something multiple times.

**Comment by joeytheadmingamer** [comment] 2018-03-14 23:10
Eh, we'll let Nelson decide to close or keep it open, if the issue isn't fixed there should be an open thread until the matter is resolved. 💯

**Comment by Trojaner25** [comment] 2018-03-14 23:11
...
The issue was already reported and Nelson already responded to it. There is absolutely no need to report it multiple times. You can respond to the other **open** issue instead.

**Comment by 18** [comment] 2018-03-15 00:05
There is no reason to keep an issue open if it cannot be fixed by the people maintaining the repo. This is Unturned's repository, not Battleye's, and adding an issue to this is akin to complaining to Valve that one of the games on steam have a bug.

**Comment by Jonnyfencing1** [comment] 2018-03-15 11:49
@joeytheadmingamer your putting thumbs down when this issue has been discussed in detail in many different issues please check before making a new one

**Comment by Jonnyfencing1** [comment] 2018-03-15 11:50
it seems like you don't want the answer to the question you are asking

**Comment by joeytheadmingamer** [comment] 2018-03-15 22:26
It seems like all you guys want to do is gang up on new forum threads especially made by new people. I'm keeping this post open until nelson acknowledges and works on a resolution. Keep the retardism to a minimum. Thx.

**Comment by Jonnyfencing1** [comment] 2018-03-15 22:29
If you had read into other issues made on this topic you would’ve seen the answer you wanted

**Comment by Trojaner25** [comment] 2018-03-15 22:41
This is not a forum.
As everyone already said an issue already exists  and opening more will not help you.

**Comment by Vulby** [comment] 2018-03-16 02:21
#224 
Nelson made a responds on the steam discussions
http://steamcommunity.com/app/304930/discussions/0/1694914736004525487/

"Unfortunately a side effect of the BattlEye upgrade to enhance anti-cheat measures has been blocking the Steam Overlay from hooking into Unturned. The BattlEye team is aware and has been continuing to work on a fix, but from the sounds of things, it's a tricky problem. They're confident it's possible, however."

**Closed** 2018-03-24 19:32 UTC
