### ISSUE TITLE
FPS freezes breaks the game

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#481] opened 2018-12-05 20:35 UTC
So.. i reported it to you once already, you said that you are busy with Unturned 2.
But now i'm back again, hoping finally you can try to do something for it.
It is here in the game for a long time, and a lot of your players are being annoyed/quit the game for sure due to that. They can not really enjoy pvp mostly on military bases at any of the maps.
These locations are the most weak, even it happens on more places of each map.

Imagine, when the player is a child (most of players) and your game just stop for 2-3 second, meanwhile the other player can kill you easy.. how anyone can get annoyed by that and its a true reason to get annoyed.
I came here cuz this problem is happening on less populated servers aswell, which never ever full or has 15+ player in a month or so, and just got wiped 1-2 weeks ago.
Here is a video from a player but there are many more positions aswell.. :/
me and i trully can say, all the Unturned players hope for fix or to reduce this.

https://youtu.be/I_eZLL2KuLE

**Comment by evermoreservers** [comment] 2018-12-07 10:44
I also meet this problem when the game supposed to render a base like that: 
https://cdn.discordapp.com/attachments/339101375034032130/520550255767584768/unknown.png

Pretty big but.. not that much.. and causes 4-5second fps freeze for everyone or even disconnection for some players.
Something must be really bad here, this base isnt a glitch base, not stacked and not even filled with too many stuff inside.

I hope, there is something that you can do to fix this, because sometimes it goes too far.. and players like to build,, its not a big castle, but still.. ugh..

**Comment by SDGNelson** [comment] 2018-12-21 22:58
That is remarkably bad in the videos! I haven't reproduced a freeze that long, but in the upcoming engine update I've also worked on improving some of these instantiation delays. Part of the problem is that multiple buildables get created all during one frame which is unlikely to change at this point, but I think you should see at least some improvement after the update. Will leave this open so we can review after that releases.

**Comment by SDGNelson** [comment] 2019-01-19 18:04
Has it gotten any better for you in 3.28?

**Comment by evermoreservers** [comment] 2019-01-19 18:14
I reported more things below, if you are interested for short answer, here it is:
 I didn't notice FPS freezes yet as i had wipe a week ago. - Can not answer it yet.


--------------------------------------- >
Long answer + more reports:
I had server wipe a week ago, so couldn't rly check it yet, but i Will keep you updated.
What i can say.. there are more bugs i plan to report..
Example.. Bedroll can not be placed in some metal bases somewhy, and there is a weird spot where you cant go in, like an invisible wall which wasnt noticed before (germany) - https://youtu.be/At4hj_bQkyI

and.. people who had like 120 FPS before the update, now having 50-60.. which is still better than the first "pack" of this update, which made it 10-12 FPS. But still, worse than it was. I dont know if its related to this topic.. if its meant to be like that.. or problem.. also i found a weird error on my sandbox server:
https://cdn.discordapp.com/attachments/339101375034032130/536241745265033216/unknown.png

I can seperate these reports in different topics if needed, but felt like say here. ^^

**Comment by SDGNelson** [comment] 2019-01-19 18:45
Ah okay, thanks.

Seeing the landscape hole not working there my stomach lurched, but it seems to be something specific to that one hole (other holes are working okay), so I'll dig into that.

Performance has generally improved for me, but it seems like every update it goes up for some and down for others. We'll see if something seems to be a common cause of performance changes.

Stack trace there is from rocket but I'll see if anything calls that RPC serverside in the vanilla code.

**Comment by SDGNelson** [comment] 2019-01-19 20:07
Tracked down the landscape hole volume bug which will be fixed in the .2 patch.

Looking through the code I think your stack trace there is caused by a plugin creating an item without state which has been bulletproofed for the .2 patch as well.

**Closed** 2019-01-21 16:16 UTC
