### ISSUE TITLE
strange bug in vehicles on my server

### ISSUE THREAD

**Issue by Duggz0r1** [SmartlyDressedGames/Unturned-3.x-Community#4314] opened 2024-01-18 05:00 UTC
for some years in my server I have had this problem that makes it difficult to walk on top of the vehicles, bugging the hitbox and giving some problems. this problem forces me to perform a cleaning of vehicles almost weekly to avoid this problem, when I perform the elimination of vehicles the bug goes away, but a few days after the users play the game it comes back.

here is a demonstration video

[](https://youtu.be/uFMle9_sa60)

https://youtu.be/uFMle9_sa60

**Comment by GazziFX** [comment] 2024-01-18 05:43
Never had that issue, did you check your plugins like virtual garage or vehicle store?

**Comment by Duggz0r1** [comment] 2024-01-18 06:09
the bug always happened to me, even if I deactivate the plugins, for a while I used up to 3 different (paid) virtual garage plugins

**Comment by sunnamed434** [comment] 2024-01-18 08:18
By deactivating the plugin you mean /rocket unload plugin_name ?

**Comment by Duggz0r1** [comment] 2024-01-18 14:17
Yesterday I tried it and the bugg continued without the plugins

**Comment by GazziFX** [comment] 2024-01-18 19:31
I mean what if you clean vehicles and run without that plugins, perhaps it won't break in a week. And also there was similar issue #4093 but there was no idea what caused that bug

**Comment by Duggz0r1** [comment] 2024-01-18 19:58
yes, that's the same problem I'm having, I have the vehicles file corrupted as well

**Comment by SDGNelson** [comment] 2024-01-18 23:02
Can you attach the broken Vehicles.dat file please? I'll see if it's something I can reproduce without plugins.

**Comment by Duggz0r1** [comment] 2024-01-18 23:24
sure, here is the vehicles.dat 
[Vehicles (1).zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/13982545/Vehicles.1.zip)

**Comment by Duggz0r1** [comment] 2024-01-18 23:39
I have researched more about this bugg during these 2 years, let me send you more videos about how the bugg originates and some miscellaneous stuff.

**Comment by Duggz0r1** [comment] 2024-01-19 16:24
for a strange reason all the research I had done didn't work when it came to testing it, but once I was testing I realized that if a vehicle (usually from some mod) is spawned outside the map limits it automatically bugs everything and for a while I used a /tpvehicle plugin in which I would teleport to some vehicle that was outside the map, because for some strange reason they were bugged in the sky (I never understood why it worked) and in other situations it would teleport me far away from everything where there was only sky and no vehicle was near (in those situations I didn't know how to remove the vehicle).

(here are photos of the out-of-bounds cars that appeared for no reason)
![imsdssdfsdfdage](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/121524803/4bb7973e-a95c-4b59-b817-307bbd37602b)
![imasdadadaage](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/121524803/957adddf-7ea3-4072-af9c-43dd6a8fe3e2)

**Comment by SDGNelson** [comment] 2024-01-19 21:24
Thanks for the vehicles file. I loaded it up on a test server - albeit without the modded vehicles - and everything seemed to work normally. Perhaps it is related to one of the custom/modded vehicles, or whatever is causing the vehicles to end up in the sky. I recall the developers of Gloomwood posted about a case where a physics object far outside the level was causing various issues. Maybe a similar case here. You mentioned sometimes they spawn outside the map: What's causing that?

**Comment by Duggz0r1** [comment] 2024-01-19 21:26
I have never come to a concrete conclusion, my theory is that it could be some garage plugin, but I have used more than one and the problem persisted, the other theory may be that when there are users inside the vehicles and the server shuts down it generates some bugg with the mod cars.

**Comment by SDGNelson** [comment] 2024-01-21 20:56
Closing for the meantime since it doesn't sound like it's a vanilla bug, but feel free to follow up if otherwise seems to be the case.

**Closed by SDGNelson** 2024-01-21 20:56 UTC
Labels: Pending response from issue poster
