### ISSUE TITLE
some strange glitch when inventory opened

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2127] opened 2020-12-04 17:39 UTC
https://medal.tv/clips/38017301/d1337pM2EXc2

**Comment by SDGNelson** [comment] 2020-12-04 17:42
If I understand correctly from the video it looks like the inventory grid images are flashing solid white. Doing a quick test I am unable to reproduce this unfortunately. I wonder: if you relog does it still happen? (to narrow down whether it is something straightforward to reproduce)

**Comment by baranmod** [comment] 2020-12-04 17:52
not sure, tested on 2 PCs, same glitch on both. Can it be hardware related? I mean those 2 PCs I tested are basically identical

**Comment by WCPistolPete** [comment] 2020-12-04 17:53
That's part of the artifact I referred to in my email to you. Also happens when mousing over buttons in menus where the text from another button flashes as a stretch-to-fit image over all other buttons and map images.

**Comment by SDGNelson** [comment] 2020-12-04 17:56
Okay I have a hunch: since those grid sprites are tiled, and they are the ones flashing, I wonder if there is a frame when Unity gives them a bad tiling value. This would be a bug in uGUI, but we can probably work around it by enabling the image component the frame after the game object is activated. Will investigate.

**Comment by baranmod** [comment] 2020-12-04 17:56
actually it disappeared after game restart now, for another PC it didn't tho

**Comment by SDGNelson** [comment] 2020-12-17 23:48
Closing because IMGUI support is restored for players experiencing flickering in tomorrow's update.

**Closed by SDGNelson** 2020-12-17 23:48 UTC
Labels: Next Patch
