### ISSUE TITLE
Add Selling_Rewards in NPCs

### ISSUE THREAD

**Issue by MonsterGeeks** [SmartlyDressedGames/Unturned-3.x-Community#1699] opened 2020-05-14 14:18 UTC
Please add Selling_Rewards and Buying_Rewards in NPCs vendor.
Buying_Conditions and Selling_Conditions already exists but not him and it would be very useful

**Comment by SDGNelson** [comment] 2020-05-14 15:02
Closing because this is a duplicate of #1696

**Closed by SDGNelson** 2020-05-14 15:02 UTC
