### ISSUE TITLE
Alien Text Bug. 

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#1620] opened 2020-04-17 09:21 UTC
I've recently bumped into this bug a few times lately and thought I would just share some info as to what might cause it. I believe it may have been reported before but I can't find any issues about it so maybe this is the first time anyone has spoke about it.

When playing on a server that has many structures in a close area you will often get a lag spike and then all of a sudden all game text is broken. The only ways I've found to fix this is to die in-game and respawn somewhere that doesn't have as many structures or to restart your game as it ruins the text even on the default menus of the game. This has happened to me on my server when going into Seattle when there are too many items placed and it also happened to me yesterday as I walked across a map on someone else's server. 

I'm 90% sure its caused by too many items being placed in one area as I never get reports after a fresh map wipe. It's not too serious of a bug as most of the time server owners try to keep their maps clean so it doesn't happen often but maybe its something that could be looked into in the future. 
![image](https://user-images.githubusercontent.com/47075751/79553868-7935a100-809d-11ea-917a-3c804daa0d02.png)

**Comment by CatzMR** [comment] 2020-04-17 09:31
Large maps and relatively stuttered servers are prone to appear. After I appeared, I used the / tp command to send it to another place. Once I stuttered again, it returned to normal.

**Comment by PandahutMiku** [comment] 2020-04-17 09:53
This issue has been around as long as I can remember, I always thought it had to do with running out of RAM (Video Card memory or actual ram?). It has something directly to do with the amount of objects/players/etc though, as you highlighted above.

**Comment by CatzMR** [comment] 2020-04-17 09:55
Sudden stuttering will cause this problem, but stuttering will return to normal again.

**Comment by Bradler26** [comment] 2020-04-17 09:58
@PandahutMiku Yeh will do next time it happens. Don't think a lack of resources causes it.

**Comment by SDGNelson** [comment] 2020-04-17 15:18
I have seen a few Unity logs which report running out of font atlas space which I think is related. There may be so many signs in an area that Unity is breaking internally. My hope has been that it would get fixed in one of the LTS updates, but no luck on that. Considering they made TextMesh Pro official rather than continuing the built-in text components maybe we should transition toward that... but it still feels like a 3rd party dependency.

**Comment by GoryBark** [comment] 2020-04-30 08:58
I have run across this on a server I am staff on. We seem to have figured it out. I don't know the basics
but it is to do  with signs and lots of coloured text, for example: flags on signs. This can cause the game to bug out and crash everyone near said signs. Contact me on discord if you need any more info, as I don't come on GitHub often. GoryBark18481#2387
<3

**Comment by Johnanater** [comment] 2020-05-05 19:42
I asked my server staff if they knew anything. Divisioniz also says that it's caused by signs

"Alien bug issue if it happens in a server then its most likely because of placards, signs with colored text https://cdn.discordapp.com/attachments/501036806075187220/702706173320757278/unknown.png"

Which is kind of weird, because I can recall sometimes I would boot up the game and the menu would be like that, after I restarted the game it was fixed again.

**Comment by XanderCodes** [comment] 2020-05-06 05:45
> I asked my server staff if they knew anything. Divisioniz also says that it's caused by signs
> 
> "Alien bug issue if it happens in a server then its most likely because of placards, signs with colored text https://cdn.discordapp.com/attachments/501036806075187220/702706173320757278/unknown.png"
> 
> Which is kind of weird, because I can recall sometimes I would boot up the game and the menu would be like that after I restarted the game it was fixed again.

We are having the same alien text issue with some players on our server, and with it being RP, having placards everywhere with colored text. We have restricted this to one coloured sign per store (apparently to reduce server RAM usage), but the server is not up, so now way to see if it had an effect. 

Would be nice to know what is ACTUALLY causing it though

**Comment by XanderCodes** [comment] 2020-05-06 06:39
> Would be nice to know what is ACTUALLY causing it though

So after some troubleshooting, turns out the because of the number of signs in Seattle on our roleplayer server, players who are in that area can't join, because their game immediately crashes when they do, some players experience this text bug when near the area, and if anyone walks into the area, their game crashes, or they get the alien text... a usually full server has had nobody playing for the past couple hours because everybody logged off in the same, sign-filled area.

Is the only solution to reset barricades?

**Comment by Bradler26** [comment] 2020-05-06 20:49
Wipe the map or install wrecking ball and wreck signs across the map. If you cant login to get someone to wreck the signs you can delete their player data folder and then they will hopefully spawn far enough away to not crash.

**Comment by XanderCodes** [comment] 2020-05-07 08:42
> Wipe the map or install wrecking ball and wreck signs across the map. If you cant login to get someone to wreck the signs you can delete their player data folder and then they will hopefully spawn far enough away to not crash.

Yeah this is what I ended up doing along with the server owner.

Would still be really really nice if this was fixed... Even partly fixed.

We have had to outright ban coloured signs, and signs in general... Which is painful for an RP server full of shops that need to show their prices.

**Comment by XanderCodes** [comment] 2020-05-12 02:56
Any update on this? It's killing our server... people hate not being able to use coloured signs.. and because we don't know if it's coloured signs or signs overall, we have had to limit the number of signs people are using.

**Comment by khakers** [comment] 2020-08-27 00:02
This bug still seems to be showing up for some people despite the upgrade to textmeshpro.

https://media.discordapp.net/attachments/324233420152504331/748327280937271296/Screen_Shot_2020-08-27_at_9.44.28_am.png

https://media.discordapp.net/attachments/324233420152504331/747354476150784050/unknown.png

**Comment by educatalan02** [comment] 2020-08-27 13:26
Is he using a Translation?

**Comment by SDGNelson** [comment] 2020-08-27 15:36
Signs were updated to TMP, but not the rest of the user interface yet.

**Comment by SDGNelson** [comment] 2020-12-31 02:56
All of the built-in UI uses TMP with uGUI by default after the UI refactor now.

**Closed by SDGNelson** 2020-12-31 02:56 UTC
