### ISSUE TITLE
typing while tactical lights, lasers, and bayonets activate/deactiviate

### ISSUE THREAD

**Issue by AndrewGrafics** [SmartlyDressedGames/Unturned-3.x-Community#2191] opened 2020-12-07 02:58 UTC
whenever you're typing b in chat your tactical light. laser, and bayonet get activated/de-activated.

**Comment by SDGNelson** [comment] 2020-12-07 03:16
Thanks for the report! Closing though because it is a duplicate of #2185, but will be fixed in the next patch

**Closed by SDGNelson** 2020-12-07 03:16 UTC
