### ISSUE TITLE
Again bug with hotkeys

### ISSUE THREAD

**Issue by schelchok** [SmartlyDressedGames/Unturned-3.x-Community#2269] opened 2020-12-23 06:36 UTC
It's writing a wrong hotkey number 
![again](https://user-images.githubusercontent.com/74832662/102967085-995e0f80-450a-11eb-85ce-8a49dc6a3ebf.png)
It's hotkey third

**Comment by SDGNelson** [comment] 2020-12-23 16:17
Thanks for the report, but closing because this is a duplicate of #2247.

**Closed by SDGNelson** 2020-12-23 16:17 UTC
