### ISSUE TITLE
Hello Nelson Please fix Videoplayer

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#3420] opened 2022-09-11 18:47 UTC
I know what if your check UnturnedPlayerLoop.DISABLED_SYSTEMS you can see a PreUpdate.UpdateVideo, please remove it from Disabled Systems in next update, and we can use standard VideoPlayer in modifications.

I know it's not that hard to do, please do it. 😉

**Comment by Gamingtoday093** [comment] 2022-09-11 20:58
Duplicate of #3403

**Comment by QERT2002** [comment] 2022-09-11 23:02
And what you want from your message?
Why you did this?
Nelson ignoring previous issue, i think its good idea to reopen this topic. :/

**Comment by Jdance-Media** [comment] 2022-09-12 21:23
It was posted 13 days ago, there is a high chance that Nelson saw the last one.

**Closed** 2023-01-11 18:55 UTC
