### ISSUE TITLE
Player join cause high latency/makes server slow

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#563] opened 2019-02-02 18:07 UTC
1-2 days ago started to notice a weird glitch which caused every player on a server to have high latency and console could be barely used (very slowly).

Desc: If the player joined the server, everyone (including himself) started to lag, this wasn't a PC lag as all the other servers ran on this PC was running smoothly.
Once the player(causer) left / got kicked, everything became okey.
If he joined again, lag started again.

I'm not sure if it's caused by some plugin, some weird glitch or the game itself.. as i didn't see any error sadly.
Wondering if you know any way to find the "trouble" like an error or whatever (once again: nothing was shown in rockét log or the console.)

**Comment by TLingC** [comment] 2019-02-03 06:10
What operating system do you use?

**Comment by evermoreservers** [comment] 2019-02-03 06:51
Windows 8.1 PRO
(Used it in past 1 Year without any problem)

**Comment by SDGNelson** [comment] 2019-02-04 17:16
My initial guess is they might be running a program to interfere with server traffic, e.g. sending bogus data or an invalid request which gets repeatedly denied. In general the server will automatically kick these, but maybe they were developing something new. Do you know who the player was? If they're a regular on your server then I guess it throws out my theory.

**Comment by evermoreservers** [comment] 2019-02-04 18:54
The player i talked about is an active player of my servers since a few months.
He donated a lot to me already. Wouldn't think he uses cheats.
In same case, he became friend with a guy who was playing my servers for a half Year or so, BUT he was always mentioned as hacker, however we could never proove it.

So what i wanna say, your theory still can be right, even if its a good donator for me.

Proof for that: I known a guy once who sent me a skin worth like 20 eur, next day he started to say how sh*t f*cking whatever i am..
There are actors in this World with no real brain.

So in the end, you don't think it's a bug with a nonwiped server since the big update (where u updated unity)
Correct? I mean this server was wiped before that update.
Or you either dont think its a plugin's glitch.

**Comment by SDGNelson** [comment] 2019-02-04 19:23
Hmm another potential cause then might be that something saved per-player is causing slowdown serverside. For example maybe they're wearing a cosmetic item that's loading improperly serverside (even though serverside they shouldn't be instantiated), or an item they picked up in the map that is being created improperly serverside.

One test to see if it's caused by their in-game per-player savedata would be to temporarily remove their folder from Players/TheirSteamId_# before they join and see if it runs normally, in which case if you could send their save file to me I'll load it up and see what's wrong.

May also be worth seeing if it doesn't happen with plugins.

Otherwise if you/they can send me a list of their equipped cosmetics I'll see if that might be the cause.

**Comment by SDGNelson** [comment] 2019-02-04 19:47
Well, that's pretty bizarre. I'm glad that it seems to have sorted itself out! I'll close it for the meantime, but like you say feel free to re-open if you replicate it. I'll subscribe to the comments so I get a notification.

**Closed by SDGNelson** 2019-02-04 19:47 UTC
