### ISSUE TITLE
Loadouts Are Broken

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#1612] opened 2020-04-15 12:05 UTC
I have recently opened an arena server and when using loadouts there is a chance that a player can't drop the items in the loadout. When they try to drop, move or do anything with the item it either causes the item to duplicate on their screen or just not move at all. if more items are spawned they overlap the items that were "dropped" before and their icons sit on top of each other.

I have tested almost everything I can think of on my end and it seems very random but I think the most likely cause is when the loadout is given before the player has fully loaded in, this causes the items to glitch out for some reason. I have asked developers and they seem to agree with me as I can recreate the glitch by triggering a kit to spawn as a user loads as well. 

I can run further tests if needed but I think a good option is just a slight delay before spawning a loadout.

Edit: Tested on a localhosted server with no plugins at all and still get the same issue.

**Comment by SDGNelson** [comment] 2020-04-15 20:09
When you tested on localhost was it still a RocketMod server? I wonder if there is a RocketMod bug we need to sort out.

My inclination is that the vanilla features work because Dango used loadouts for its items without bugs like this reported (afaik), and no related features have changed since then.

**Comment by Bradler26** [comment] 2020-04-16 08:11
Tested without rocketmod and had the same issue on the local machine. Could it be something to do with Alpha Valley?

**Comment by SDGNelson** [comment] 2020-04-16 08:42
Using the "loadout" command on Alpha Valley with items granted each time the player spawns? If you can attach your Commands.dat I will use your exact setup and try replicating it locally.

**Comment by Bradler26** [comment] 2020-04-16 09:12
Did a few more tests and got some extra info that might be useful. It happens on Washington as well, but only happens when the player file is first generated.  Also clothes and backpacks seem to work fine but other items glitch. I Tried testing other items in my loadout and removing some and still had the issue. I also tested in singleplayer and had no issues so it seems to only happen when there is a slight delay thats caused by servers.

Here is all thats in my Commands.dat:
`Map Alpha Valley`
`loadout 255/253/8/143/21/145/153/296/1004/146/149/1007/1008/151/152`

**Comment by SDGNelson** [comment] 2020-04-16 09:45
It seems you are completely right. Thank you for the report and the reproducible case! I am not sure what the cause is yet, but I will get this sorted out for the next patch.

**Comment by SDGNelson** [comment] 2020-05-01 17:48
Thanks again for the report! The underlying issue should be resolved in the next update, and seems to be working on my local server. It is a bit of a hack though so my hope is to clean it up during the netcode refactor.

**Closed by SDGNelson** 2020-05-01 17:48 UTC
Labels: Next Patch
