### ISSUE TITLE
Linux Multiple Server Error

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#1622] opened 2020-04-17 18:43 UTC
There's a problem when launching 2 servers in the same instance. (Using Linux Obviously)

When you run both servers simultaneously, one of them crash with the following error:
**./ServerHelper.sh: line 19:  8810 Bus error               (core dumped) ./Unturned_Headless.x86_64 -batchmode -nographics "$@"**

**Comment by SDGNelson** [comment] 2020-04-17 19:31
Just to double-check before digging further: both servers are using different ports? e.g. 27015 and 27018

**Comment by ZoomGYT** [comment] 2020-04-17 21:11
yes

**Comment by educatalan02** [comment] 2020-04-17 21:14
First server was with port 27015, and the second 27020.

**Comment by SDGNelson** [comment] 2020-04-18 02:45
Alright. I will mark this "next patch" so that I remember to give it a try soon.

**Comment by gegtor** [comment] 2020-04-18 20:23
I have 4 server setup running on my Linux host without a hitch 

Weird 🤔

**Comment by ZoomGYT** [comment] 2020-04-18 20:26
@gegtor What code do you use in serverhelper.sh?

**Comment by gegtor** [comment] 2020-04-18 23:30
I find default scripts very unreliable and use my own @ZoomGYT 

https://github.com/gegtor/Unturned-64Bit-Server-Scripts

**Comment by educatalan02** [comment] 2020-04-19 09:34
Well you're using RocketMd Scripts. 
We're using the official Scripts.

**Comment by SDGNelson** [comment] 2020-05-13 00:07
Sorry for my delay on this. I was nervous to investigate it, so left it until the other fixes were ready.

For my test I used the latest stable release of Ubuntu, and the preview version of the next update for Unturned. I created two server launch scripts: `FirstServer.sh` and `SecondServer.sh` following this pattern:

    #!/bin/bash
    ./ServerHelper.sh -ThreadedConsole +LanServer/FirstServer

Both servers ran simultaneously without errors, and I was able to join them as a client. To be thorough I also separately tried using RocketMod v4.9.3.1 (preview) as their own servers. Perhaps it was an issue that has been fixed in the preview builds? If you can try updating and see if it works for you that would be appreciated!

@gegtor I recommend updating to use the built-in scripts and the officially supported version of RocketMod. It already has quite a few nice fixes: https://github.com/SmartlyDressedGames/RocketMod/blob/master/CHANGELOG.md

**Comment by gegtor** [comment] 2020-05-13 00:10
@SDGNelson I didn't know someone was still maintaining RocketMod 

Good job will update

**Comment by ZoomGYT** [comment] 2020-05-13 00:16
https://gyazo.com/5e8ad64942eed8bff63d387bb9a89ee5 @SDGNelson no work

**Comment by SDGNelson** [comment] 2020-05-13 00:16
@gegtor Yay! Please let me know if you run into any issues. v4.9.3.0 is included with the current release of Unturned and has a few important fixes from prior to the changelog / repo. v4.9.3.1 is on the preview branch right now.

**Comment by SDGNelson** [comment] 2020-05-13 00:19
@ZoomGYT Thanks for following up so quickly. From your other comment "What code do you use in serverhelper.sh?" I wonder if there are some changes to that script. If you delete the script and verify the install it should reinstall the latest version. Was your test on the preview branch? And did you replace the Rocket.Unturned in the Modules directory with the version from the Extras directory?

**Comment by ZoomGYT** [comment] 2020-05-13 00:21
hi Nelson, no update at all, just try with your script since you used a different one but keep on with that error, do I have to activate the server and add rocketmod extras again? @SDGNelson

**Comment by ZoomGYT** [comment] 2020-05-13 00:21
#!/bin/bash
./ServerHelper.sh -ThreadedConsole +InternetServer/ChuServer

**Comment by SDGNelson** [comment] 2020-05-13 00:30
@ZoomGYT some things that may be worth trying:
- If you temporarily disable the plugins that are not built-in to RocketMod does it work? i.e. there may be a plugin causing the crash.
- If you use the +LanServer arg rather than +InternetServer does it work? I should have tested +InternetServer as well (my bad) but it should not make a difference.
- If you are using an older version of RocketMod, in particular from the old RocketMod releases repo, it may be missing Trojaner's commit to remove the console handling. Any of the builds from the Extras directory have that fix though.
- If you can try with the "-beta preview" steamcmd option that would be great because the upcoming update has a TON of fixes.

**Comment by ZoomGYT** [comment] 2020-05-13 00:36
Nelson I will try it tomorrow and tell you, since I am from Spain and it is very late here, thank you very much for the help and you are doing a very good job. A greeting. @SDGNelson

**Comment by SDGNelson** [comment] 2020-05-13 00:37
Sounds good! I will keep an eye out for further comments. Thanks for giving them a try.

**Comment by ZoomGYT** [comment] 2020-05-13 10:47
@SDGNelson This is the next error, update everything and keep on showing this, if you want I can give you more information by discord (ZoomGYTツ#1509) and I passed the vps and you look at the errors, I leave you a link to the error. a greeting
https://pastebin.com/vKs4KitS

**Comment by SDGNelson** [comment] 2020-05-13 16:55
@ZoomGYT it looks like the error is happening with Steam in `ISteamNetworking_IsP2PPacketAvailable`. If I recall correctly, a workaround for this was replacing the `steamclient.so` file in the `linux64` directory with the one from the `steamcmd` folder. Does that fix it for you? The standalone dedicated server (appid 1110390) uses the official server redist depot to keep that always up-to-date - are you using the standalone dedicated server?

**Comment by ZoomGYT** [comment] 2020-05-13 20:46
@SDGNelson 

Hi Nelson, sorry I don't understand you correctly, this is my configuration
https://gyazo.com/22c8a582560446c918e9ac492cecad3a
https://gyazo.com/8440cbec5efb5adca956133033f7d5d2

you mean put it here?
https://gyazo.com/22c8a582560446c918e9ac492cecad3a

**Comment by SDGNelson** [comment] 2020-05-13 22:25
I mean to copy from `/home/steam/Steam/linux64/steamclient.so` to replace the `U3DS/linux64/steamclient.so` file.

Are you using the standalone dedicated server? (appid 1110390)

**Comment by ZoomGYT** [comment] 2020-05-13 22:28
Oh it worked, no, I am using the server with the guide you uploaded from a dedicated server eg a vps linux ubuntu 16.04, thank you very much Nelson and it has been a pleasure to talk to you after having 3000 hours in your game, greetings and take good care ! @SDGNelson

**Comment by SDGNelson** [comment] 2020-05-14 01:30
Thank you for the confirmation, and for your kind words! I will enable the `ServerHelper.sh` script to copy the `steamclient.so` file by default for the meantime until the official redist works properly then.

**Comment by SDGNelson** [comment] 2020-05-15 17:08
Curious to hear how you guys fare with the 3.20.5.0 update released today. The server should be more stable than ever before.

**Comment by ZoomGYT** [comment] 2020-05-15 17:13
https://gyazo.com/8a24562cee36b390319703ccff347283 @SDGNelson :/

**Comment by ZoomGYT** [comment] 2020-05-15 17:13
Is update

**Comment by SDGNelson** [comment] 2020-05-15 17:16
@ZoomGYT is that with the latest RocketMod from the Extras directory as well? If you can share the Server log file again I will take a look and see what might be going on.

**Comment by ZoomGYT** [comment] 2020-05-15 17:27
https://gyazo.com/be13fea0c2f22aa381b16da882489ed8 @SDGNelson

**Comment by SDGNelson** [comment] 2020-05-15 17:32
@ZoomGYT can you share the Server log file please? (from the Logs directory) Also, it appears you are using the old version of RocketMod rather than the one from the Extras directory.

**Comment by ZoomGYT** [comment] 2020-05-15 17:46
no I'm using the new version I just updated it
In /home/steam/Steam/steamapps/common/U3DS/Servers/Default/Rocket/Logs
@SDGNelson

**Comment by SDGNelson** [comment] 2020-05-15 17:49
In the previous screenshot it said v4.9.3.0, but perhaps that was before you updated it.

Based on your path the log should be at: `/home/steam/Steam/steamapps/common/U3DS/Logs/Server_Default.log`

**Comment by ZoomGYT** [comment] 2020-05-15 21:07
Hello Nelson after several failures, I decided to pass the script that @gegtor  created, since it is very functional and you can open several servers without any error, ask what, will these scripts be functional in the future? @SDGNelson . When updating my server in your way, it gave me an error and when I updated it, it did not update correctly, doing it from steam cmd with the appupdate, very rare things, I hope that in Unturned 2 there are no such errors, thank you very much and greetings.


https://github.com/gegtor/Unturned-64Bit-Server-Scripts

**Comment by SDGNelson** [comment] 2020-05-15 21:24
Please do *not* use the old RocketLauncher.exe method mentioned by gegtor and the linked scripts.

In my testing with the officially maintained rocketmod and official dedicated server everything works fine with multiple servers running on Ubuntu Linux. If you would please just share the logs we can hopefully track down what is going on with your setup and kill off all these unofficial workarounds.

**Comment by gegtor** [comment] 2020-05-15 21:48
@SDGNelson Maybe create something that works and people can use before bashing on my methods 

These problems come from people installing things incorrectly etc 

Maybe create something similar to my scripts without RocketLauncher that will get even Linux newbie going with install script similar to `update.sh` and elegant without the need to pass additional parameters to the script with working coloured console etc

**Comment by SDGNelson** [comment] 2020-05-15 22:14
@gegtor if anything you are bashing on me by harping on about "default scripts very unreliable" in multiple threads. "your" setup was made by Sven years ago prior to improved Linux support in the base game.

RocketLauncher does not do anything the base game does not do. Here is the source code: https://github.com/SmartlyDressedGames/RocketMod/blob/master/Rocket.Unturned.Launcher/Program.cs
It runs the server (same as the built-in `ServerHelper.sh` script) and writes the console output to a file (unnecessary because the game logs all console output anyway).

**Comment by Johnanater** [comment] 2020-05-17 21:41
I can confirm, that ServerHelper.sh does work perfectly fine on Ubuntu 18.04.4. There's no reason to use RocketLauncher.exe anymore.

I use starter script to start ServerHelper.sh for my testing servers.

`#!/bin/bash
ulimit -n 2048
export TERM=xterm

# First argument
INSTANCE_NAME=$1

# To the Unturned directory
cd server
./ServerHelper.sh -logfile 2>&1 -ThreadedConsole +secureserver/$1 `

And I run it like...
`./run.sh Server1`

I'm pretty sure `-logfile 2>&1` was a workaround for logging, but it doesn't seem to be required anymore.

**Comment by SDGNelson** [comment] 2020-05-17 22:05
Thanks for the confirmation Johnanater! If you run into any issues let me know.
`TERM=xterm` is also set by `ServerHelper.sh`, but it won't hurt to set it twice.
-logfile 2>&1 was a workaround to redirect Unity's log output to the terminal as you mention, but with `-ThreadedConsole` you are right that it should not be necessary. In the next major update `-ThreadedConsole` will become the default as well.

**Comment by TH3AL3X** [comment] 2020-05-17 23:56
![image](https://user-images.githubusercontent.com/13141042/82163311-afd42680-98aa-11ea-9e48-d647e28b3389.png)


[logs.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4641345/logs.zip)

**Comment by SDGNelson** [comment] 2020-05-18 15:36
Thanks for the logs @TH3AL3X. Unfortunately there is no indicator in them of why the server is crashing, it seems to just stop after the level is loaded and server is running.
- Are you running the startup through another script? The other script may have some difference worth comparing.
- One difference compared to Johnananter's setup is he sets `ulimit -n 2048`. If you run `ulimit -n 2048` does the server work normally?

**Comment by TH3AL3X** [comment] 2020-05-18 21:10
I tried with john script, and doesn't work, and with official one two

**Comment by SDGNelson** [comment] 2020-05-19 00:22
Which Linux distribution are you using @TH3AL3X? I can try replicating it to help track down the problem.

**Comment by TH3AL3X** [comment] 2020-05-19 19:17
> Which Linux distribution are you using @TH3AL3X? I can try replicating it to help track down the problem.

![image](https://user-images.githubusercontent.com/13141042/82368712-2a6d8500-9a16-11ea-9ac1-ab2087be5d0b.jpeg)

**Comment by SDGNelson** [comment] 2020-05-20 03:02
Well, that's fortuitous considering myself and Johnanater are using Ubuntu. Maybe it's a missing prerequisite then? - Can you run a single Linux server? (this issue was originally about multiple servers)

**Comment by TH3AL3X** [comment] 2020-05-20 07:55
Yes, I can run only one server , but I can’t start two server in the same instance

**Comment by SDGNelson** [comment] 2020-05-20 14:44
Can you email or attach the files (e.g. startup scripts, Servers folder) for the two servers? Maybe it is something I can replicate.

**Comment by TH3AL3X** [comment] 2020-05-20 15:35
`#!/bin/bash

# To mark this script as executable you may need to run "chmod +x ServerHelper.sh"

# Unity will load the steamclient file from the plugins directory, so we copy it there.
# As of 2020-05-14 there are crashes with the official redist version that do not seem
# to be present in the steamcmd version, so we use that instead if available.
redist_steamclient=linux64/steamclient.so
steamcmd_steamclient=../../../linux64/steamclient.so
unturned_steamclient=Unturned_Headless_Data/Plugins/x86_64/steamclient.so
if [[ -f $steamcmd_steamclient ]]
then
    cp -f $steamcmd_steamclient $unturned_steamclient
else
    cp -f $redist_steamclient $unturned_steamclient
fi

# Tell system where to find the steamclient.so we just copied. Without this
# command API Init will fail with an unable to find file error.
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname $0`/Unturned_Headless_Data/Plugins/x86_64/

# Terminal mode compatible with -logfile 2>&1 IO.
export TERM=xterm

# Run the server binary.
# -batchmode and -nographics are Unity player arguments.
# -logfile 2>&1 can be used to pipe IO to/from the terminal.
# "$@" appends any command-line arguments passed to this script.
./Unturned_Headless.x86_64 -ThreadedConsole +InternetServer/"$@"
`

**Comment by TH3AL3X** [comment] 2020-05-20 15:36
[startup scripts.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4657828/startup.scripts.zip)

**Comment by SDGNelson** [comment] 2020-05-20 16:31
Potentially part of the problem is that if you are using the start.sh script you included, it does not have the -batchmode and -nographics arguments. The recommended way to run a Linux server is to create a script that runs ServerHelper.sh, or run ServerHelper.sh from the terminal. Either way, something like:

    ./ServerHelper.sh -ThreadedConsole +InternetServer/MyServer

If that does not do the trick, do you have any other per-server configuration? i.e. are you testing with blank servers, or is the problem happening with a specific plugins, commands, etc setup.

**Comment by TH3AL3X** [comment] 2020-05-20 19:07
Is happening with vanilla servers too

**Comment by Gsechs** [comment] 2020-05-20 19:10
> Is happening with vanilla servers too

Vanilla as in: not having RocketMod correct?

**Comment by TH3AL3X** [comment] 2020-05-20 19:13
Aight -_-

**Comment by SDGNelson** [comment] 2020-05-21 16:02
Can you clarify about my comment please @TH3AL3X?

Is running multiple servers on Linux working for you @Gsechs?

**Comment by TH3AL3X** [comment] 2020-05-21 16:15
I've tried removing parameters and adding, and there is no way

**Comment by SDGNelson** [comment] 2020-05-21 22:45
Hmm I'm not sure what else to try for the moment considering it sounds like the setups are identical. I might try starting with a barebones Linux install to see if it happens when missing dependencies.

**Comment by TH3AL3X** [comment] 2020-05-22 23:41
I can't do those things...

**Comment by SDGNelson** [comment] 2020-05-23 02:09
To clarify: I meant that I personally will try with a barebones Linux installation.

**Comment by TH3AL3X** [comment] 2020-05-23 18:14
Also, you should report something that is not normal, I have a dedicated CPU with two cores and 8 gb ram, and there are parts of the map that when loading gives fps lag spikes, it's not normal

**Comment by Johnanater** [comment] 2020-05-24 01:27
Actually, I just tested this on Ubuntu with multiple servers (Different maps, ports, directories, etc). The second I start up another server, the first one crashes with this error:

https://pastebin.com/uvFP6g8Q

**Comment by TH3AL3X** [comment] 2020-05-24 08:26
Aight

**Comment by SDGNelson** [comment] 2020-05-25 06:20
@Johnanater by different directories do you mean that the U3DS directory was moved? It looks like it crashed due to the Linux Steam redist bug that is supposedly fixed with the newer steamclient.so. The server launch script copies the steamclient.so from steamcmd if it is inside the normal steamcmd path, but will not find it if you move the server files elsewhere. Is that the case, and if so why move the server files outside steamcmd?

**Comment by Johnanater** [comment] 2020-05-30 01:27
Ah, I see that the ServerHelper.sh was updated to now copy that. 

I only have one U3DS directory, `~/unturned/servers/`
SteamCMD is installed in `~/steamcmd/`, and I changed the U3DS directory using `+force_install_dir`

I just copied the SteamCMD `linux64/steamclient.so` to the U3DS directory and it works now. As for why I have it setup in that way, well that's just how I usually set it up SteamCMD (way before the official documentation was up). This could also be an issue for hosters that don't follow the same server directory structure.

**Comment by SDGNelson** [comment] 2020-05-30 01:46
Relieved to hear it Johnanater. Unfortunately I don't think there is a way for the startup script to detect where steamcmd is installed when using +force_install_dir, but if your script is copying the steamclient.so file going forward that should be fine.

**Comment by Johnanater** [comment] 2020-05-30 01:49
That's alright. Is there any reason why the U3DS doesn't ship with the updated steamclient.so?

**Comment by SDGNelson** [comment] 2020-05-30 01:56
Theoretically it does ship with the updated version because it uses Valve's automatic Steamworks Redist depot, so the latest files are always included from there. The `steamclient.so` included with steamcmd might be **more** up-to-date than the server redist though.

To workaround issues like this in the past I did include the latest `steamclient.so` manually prior to the standalone dedicated server, but that ran into a problem when a new redist update started causing backwards compatibility crashes with old `steamclient.so`.

My guess is that Valve's games don't actually use the `IsP2PPacketAvailable` which is why they haven't run into the crash for their big multi-instance-per-server games, or because they are using Docker for individual instances (according to their docs). 

In the next patch I removed usage of `IsP2PPacketAvailable` and directly call `ReadP2PPacket` instead in case my first guess there is correct.

**Comment by TH3AL3X** [comment] 2020-06-06 13:14
I don't know, but for some circumstances now my server, when there are a large number of people, usually ping up to 300 without reason, And it's constantly going down and up, I have tried to remove all the plugins, also to reinstall the machine completely and nothing ...

**Comment by TH3AL3X** [comment] 2020-06-06 13:15
Pd, still doesn't work to start two servers in the same instance

**Comment by JustOneMoreBlock** [comment] 2020-06-06 13:25
Here's an example of the shell script I wrote for my server in order to get 2+ servers running.

```
#!/bin/bash

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname $0`/Unturned_Headless_Data/Plugins/x86_64/
cp -f /home/Games/unturned/linux64/steamclient.so /home/Games/unturned/Unturned_Headless_Data/Plugins/x86_64/steamclient.so

steamcmd +login anonymous +force_install_dir /home/Games/unturned +app_update 1110390 validate +exit
yes | cp -rf /home/Games/steamcmd/linux64/steamclient.so /home/Games/unturned/
yes | cp -rf /home/Games/steamcmd/linux64/steamclient.so /home/Games/unturned/linux64/
```

This would go for your updater.

This is for `update-steam.sh`

```
root@ut:/home/Games/scripts# cat update-steam.sh 
md5sum /home/Games/steamcmd/linux32/steamclient.so
md5sum /home/Games/steamcmd/linux64/steamclient.so

mkdir -p /home/Games/steamcmd/
cd /home/Games/steamcmd/
curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
chmod +x steamcmd.sh
./steamcmd.sh +quit

rm -fv /lib/steamclient.so
rm -fv /lib64/steamclient.so

ln -s /home/Games/steamcmd/linux32/steamclient.so /lib/steamclient.so
ln -s /home/Games/steamcmd/linux64/steamclient.so /lib64/steamclient.so

md5sum /home/Games/steamcmd/linux32/steamclient.so
md5sum /home/Games/steamcmd/linux64/steamclient.so
```
The main part of this is to symlink an update `steamclient.so` to `lib/` as well.

Hopefully, this helps.

**Comment by TH3AL3X** [comment] 2020-06-16 18:40
Getting other errors, with that script i can open the server, but i have another problem, because can't join now, says "using modified map" and we don't have workshop or any mod

**Comment by TH3AL3X** [comment] 2020-06-16 18:55
https://i.gyazo.com/05e371662dd59011dbe082d2ab7892c8.mp4

**Comment by SDGNelson** [comment] 2020-06-17 00:08
The "using modified map" error means the client hash does not match the server. It may be worth validating both installs. That's not what this issue post is for however.

**Comment by educatalan02** [comment] 2020-08-27 23:08
This is still a thing...

**Comment by TH3AL3X** [comment] 2020-09-18 18:09
Hello again, I'm getting problems now about the servers in the same instance with those updates, it causing random crashes

**Comment by SDGNelson** [comment] 2020-09-18 19:10
@TH3AL3X are you overriding the install dir? If so, steamclient.so may be out of date. Also, have you tried with plugins disabled? It may be that one of them needs to be updated for the transport rewrite.

**Comment by TH3AL3X** [comment] 2020-09-18 19:15
> @TH3AL3X are you overriding the install dir? If so, steamclient.so may be out of date. Also, have you tried with plugins disabled? It may be that one of them needs to be updated for the transport rewrite.

Steamclient.so is updated, I will check all plugins

**Comment by TH3AL3X** [comment] 2020-09-19 21:21
Yep is something related of a plugin, but idk what plugin it is

**Comment by TH3AL3X** [comment] 2020-09-20 11:20
I updated all plugins, and still getting crash, is when i open a server, and then i open another server, the first server get crash...

**Comment by educatalan02** [comment] 2020-09-20 12:12
I got the same problem, when I open multiple servers in the same instance

**Comment by SDGNelson** [comment] 2020-09-21 17:25
Are you overriding the install dir @educatalan02? I will test out with Linux today and see if I can replicate it. If either of you can attach the Server_(name).log file there might be some details.

**Comment by educatalan02** [comment] 2020-09-21 20:55
[Server_Server1.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5258091/Server_Server1.log)
[Server_Server2.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5258092/Server_Server2.log)

**Comment by educatalan02** [comment] 2020-09-21 21:00
The Server 1 is the one crashing, altought it doesnt log anything, but it shows that: https://pastebin.com/DNrk6PHP
The Server 2 error: https://pastebin.com/tw1pzFxu

**Comment by SDGNelson** [comment] 2020-09-23 02:46
Experimented with a variety of approaches today. All of the crashes (including my personal tests) have been when calling into the Steam APIs, for example if both servers are starting up they crash when they hit SteamGameServer_Init, or some of the Networking functions if already running. This is most likely related to the game updating to Steamworks SDK 1.48a for Steam Networking Sockets. I merged the most recent Steamworks .NET unreleased version with Steamworks SDK 1.49, but that has not  resolved it. I also tested with the ready-ish Unity 2019 LTS beta and ran into the same crashes.

No good workaround for the meantime, and no leads on a workaround either. Valve uses Docker for their multi-instance servers so that might be a good option to keep them isolated.

**Comment by TH3AL3X** [comment] 2020-09-26 11:23
> Experimented with a variety of approaches today. All of the crashes (including my personal tests) have been when calling into the Steam APIs, for example if both servers are starting up they crash when they hit SteamGameServer_Init, or some of the Networking functions if already running. This is most likely related to the game updating to Steamworks SDK 1.48a for Steam Networking Sockets. I merged the most recent Steamworks .NET unreleased version with Steamworks SDK 1.49, but that has not resolved it. I also tested with the ready-ish Unity 2019 LTS beta and ran into the same crashes.
> 
> No good workaround for the meantime, and no leads on a workaround either. Valve uses Docker for their multi-instance servers so that might be a good option to keep them isolated.

After this update, is working again...

**Comment by Hagvan** [comment] 2020-10-16 01:24
So, is there any workaround or still nothing? I am on Ubuntu 20.04 LTS and trying to run 2 servers from one install. When I launch one server the other one crashes the same moment I start.

`Receiving unhandled NULL exception
#0  0x000000416a1623 in (wrapper managed-to-native) Steamworks.NativeMethods:ISteamNetworking_ReadP2PPacket (intptr,byte[],uint,uint&,Steamworks.CSteamID&,int)
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) Steamworks.NativeMethods.ISteamNetworking_ReadP2PPacket (intptr,byte[],uint,uint&,Steamworks.CSteamID&,int) [0x0000b] in <da8f7795519e4110aadf3529ccd64e1b>:0
  at Steamworks.SteamGameServerNetworking.ReadP2PPacket (byte[],uint,uint&,Steamworks.CSteamID&,int) [0x0000a] in <da8f7795519e4110aadf3529ccd64e1b>:0
  at SDG.NetTransport.SteamNetworking.ServerTransport_SteamNetworking.Receive (byte[],long&,SDG.NetTransport.ITransportConnection&) [0x00009] in <5ce47ca76aa34cf4894ad6a130f707d6>:0
  at SDG.Unturned.Provider.listenServer () [0x00010] in <5ce47ca76aa34cf4894ad6a130f707d6>:0
  at SDG.Unturned.Provider.listen () [0x00022] in <5ce47ca76aa34cf4894ad6a130f707d6>:0
  at SDG.Unturned.Provider.Update () [0x000d1] in <5ce47ca76aa34cf4894ad6a130f707d6>:0
  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) [0x0001e] in <e1319b7195c343e79b385cd3aa43f5dc>:0`

**Comment by educatalan02** [comment] 2020-10-16 07:12
The unofficial solution is install the dedicated server for only 1 server.
So if you have 2 servers install 2 times the dedicated server in different
folders

**Closed** 2020-12-31 22:00 UTC

**Comment by SDGNelson** [comment] 2020-12-31 22:01
Closing because there is not much else to say. The situation with Steam should be a bit better now because they are more aware of the server redist issue, and the SteamNetworking crash should not happen anymore now that the game uses SteamNetworkingSockets, but I am sure there are still problems on Linux. :/
