### ISSUE TITLE
Connect by IP/Port fails after update

### ISSUE THREAD

**Issue by ksdsksd** [SmartlyDressedGames/Unturned-3.x-Community#4274] opened 2023-12-22 02:24 UTC
After the update, I'm no longer able to connect to my local server(s) by favorite or IP/Port.  The server code does work, but cannot be added to favorites.
![Screenshot_20231221_205730](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/17296616/f59d0b81-7c99-4432-b62b-c1efce90f311)

**Comment by GazziFX** [comment] 2023-12-22 06:42
Try to remove LobbyManager or other plugins which changes displayed info

**Comment by ksdsksd** [comment] 2023-12-22 12:23
100% vanilla install, no mods, no plugins, running from the command line(Linux).

**Comment by Jdance-Media** [comment] 2023-12-22 13:55
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67397422/f5dc0446-5da4-467a-b44f-eede2c6418be)
Can confirm the same issue happening to most servers on one active node. Alongside that, several reports of similar 'server advertised a different' messages have popped up within the community.

**Comment by SDGNelson** [comment] 2023-12-22 21:46
There are some plugins which mix up the server's tags. For example, any server in the Client.log file with a "unable to parse net transport tag" has problems with its tags. 

Specifically with this BattlEye problem I wonder if your server is set to +LANServer? It looks like the BattlEye enabled option is ignored except for Internet server which I need to fix so that it correctly advertises as not BE-enabled.

**Comment by KarmaWSYD** [comment] 2023-12-22 22:26
I was able to replicate the BattlEye-protection mismatch status on one of my servers, notably the server in question was missing the +internetserver (as well as +lanserver, but I'm guessing that's default), client logs showed that the server advertised itself as VAC-insecure and BE-secure, but upon connecting you get a mismatch. With connection via server codes (which seem to bypass the error), the server has neither BE nor VAC enabled. I resolved the issue by adding the +internetserver flag, which immediately fixed the issue.

The server in question was Ubuntu Linux with Pterodactyl, hosted on a server I rent (so, not a LAN server, nor do I have a VPN connection to it). Curiously the server still showed up on the server masterlist just fine, and direct connecting via IP did get to the lobby screen. 

The egg used for this (which isn't the production egg I use, but per Jdance (who originally provided me a copy of the egg) is popular and has worked before the update, Is there a chance the update modified behavior when there's +internetserver isn't specified, or could this just be coincidence?

**Comment by Jdance-Media** [comment] 2023-12-22 23:04
> There are some plugins which mix up the server's tags. For example, any server in the Client.log file with a "unable to parse net transport tag" has problems with its tags.
> 
> Specifically with this BattlEye problem I wonder if your server is set to +LANServer? It looks like the BattlEye enabled option is ignored except for Internet server which I need to fix so that it correctly advertises as not BE-enabled.

Hi, several servers I have access to are having the same issue. They do not have +LANServer in the startup line, and I recently tried adding the +InternetServer line to them to see if that did anything. So far, adding the +InternetServer doesn't seem to resolve the issue.

I've gone ahead emailed you the logs for two different servers affected by the issue.

**Comment by KarmaWSYD** [comment] 2023-12-22 23:22
> [2023-12-22 21:50:09] Successfully refreshed the master server.
> [2023-12-22 21:50:14] "Server_Name" host ban flags: None
> [2023-12-22 21:50:18] Initializing ClientTransport_SteamNetworkingSockets
> [2023-12-22 21:50:18] Client Steam Networking available
> [2023-12-22 21:50:18] Client connecting to 192.168.0.1:27015
> [2023-12-22 21:50:18] Client connection with 6393721550 ready
> [2023-12-22 21:50:18] Disconnecting: server BE advertisement mismatch (Advertisement: True Response: False)
> [2023-12-22 21:50:18] Client disconnect from 6393721550 result: True
> [2023-12-22 21:50:18] Disconnected
> [2023-12-22 21:50:18] Returning to main menu
> [2023-12-22 21:50:18] Loading additive Christmas scene
> [2023-12-22 21:50:18] Refreshing Steam inventory
> [2023-12-22 21:50:18] Applying graphics settings (loaded menu)
> [2023-12-22 21:50:18] Applied graphics settings
> [2023-12-22 21:50:18] Unable to get current Steam beta name, defaulting to "public"
> [2023-12-22 21:50:18] Checking for updates on Steam beta branch "public"...
> [2023-12-22 21:50:18] Requesting popular workshop files from the past 30 day(s) for news feed
> [2023-12-22 21:50:19] Requesting Steam item store prices
> [2023-12-22 21:50:19] Server advertised a different BattlEye-protected status than what is currently active.

Adding seemingly relevant information from my client.log file (anonymized, actual IPv4, for example, is a dedicated public IP) from before the change, server logs seemingly did not acknowledge the connection attempt at all.

**Comment by SDGNelson** [comment] 2023-12-23 04:14
Thanks for the logs. To clarify about the +LANServer issue, BattlEye doesn't enable if VAC is not enabled. VAC is only enabled with +InternetServer and `Server.VAC_Secure true`. So do you have VAC disabled in the Config.json file? I tried joining your Orion Network server Jdance and the lobby screen suggests that VAC is disabled even though you have +InternetServer. If you do have VAC disabled, how come?

**Comment by Jdance-Media** [comment] 2023-12-23 04:55
Wasn't aware that the server had VAC disabled 🤦‍♂️ (not the only one who can access it). I wouldn't be able to tell you why VAC was disabled, as it seems like a no-brainer. Orion just didn't have it enabled in the Config.json for whatever reason.

It seems I'm no longer getting the message on Orion and Lucid anymore. Lucid had VAC enabled in the Config.json and then it was reported that the server was showing up VAC disabled. Now it is no longer showing up VAC disabled.

I hope I'm not tripping or something, because there was two servers showing up as VAC Disabled on the same node but had it enabled in the Config. Now it seems resolved.

I'm not sure if the problem just resolved itself because of time (perhaps Steam's end???). What I do know is that several others on the Discord bumped into 'Server advertised a different...' message.

**Comment by SDGNelson** [comment] 2023-12-23 05:13
Glad to hear that sorted it out on your Orion server!

The BE mismatch is definitely on my end (with not correctly handling VAC on/off) but other "advertised a different" might be the mixed up tags mentioned in my earlier comment. If anyone has a server currently giving a different message I'd be happy to take a look.

**Comment by Badxpatrick** [comment] 2023-12-23 12:54
![error](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/29387223/bf48592d-ec6e-4bd6-b2d1-ebb2e8221cf4)
This issue happens when max players is set to 100 is my commands.dat file. I haven't changed it from 100 max players since the update ages ago that allowed servers with 100 max players to display on the master server. Now the server description says I have 0/24 players and kicks everyone with the above error. Fixed by setting max players to 24

**Comment by ksdsksd** [comment] 2023-12-23 15:56
Yea, it's running as a +LANServer.  Setting Battleye_Secure to false in the Config.json allows it to connect again.

**Comment by SDGNelson** [comment] 2023-12-23 19:24
@Badxpatrick Do you have any plugins on your server that would be modifying the player count?

**Comment by Badxpatrick** [comment] 2023-12-23 19:26
@SDGNelson none I'm aware of. I used to use ReservedSlots before the update that hide all servers with counts over 24, but removed it afterward. I've been using 100 max players for months until this update

**Comment by SDGNelson** [comment] 2023-12-23 19:46
To test whether it's related to a plugin, could you try turning off all plugins temporarily please? If you can join with all plugins off, then I'd suggest turning them on a couple at a time to narrow down if one is calling `SteamGameServer.SetMaxPlayerCount`

**Comment by Badxpatrick** [comment] 2023-12-23 21:34
I've confirmed it was a custom-made plugin with no config related to player count. Looks like I'm about to have a word with someone. Appreciate it

**Comment by SDGNelson** [comment] 2023-12-27 20:03
Meant to reply the other day: Glad to hear it @Badxpatrick! Sounds like the .2 patch sorted out the remaining kinks, fortunately.

**Closed by SDGNelson** 2023-12-27 20:03 UTC
Labels: Pending response from issue poster
