### ISSUE TITLE
Crashes when i start the server

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#2580] opened 2021-04-29 20:22 UTC
Sometimes the server crashes when opening it, I have tried to change the script to default and the same error keeps happening..
![image](https://user-images.githubusercontent.com/13141042/116613764-60f79380-a939-11eb-8952-35913f8e34fd.png)

**Comment by TH3AL3X** [comment] 2021-04-29 20:22
`Caught fatal signal - signo:11 code:1 errno:0 addr:0x7fbf2ea07100
Obtained 35 stack frames.
#0  0x007fc0021e83c0 in funlockfile
#1  0x007fc001a83ef9 in GC_mark_from
#2  0x007fc001a88d81 in GC_mark_some
#3  0x007fc001a89e33 in GC_collect_a_little_inner
#4  0x007fc001a8a302 in GC_allocobj
#5  0x007fc001a8b134 in GC_generic_malloc_inner
#6  0x007fc001a8dfac in GC_generic_malloc
#7  0x007fc001a8e214 in GC_malloc_kind_global
#8  0x007fc001a6135f in mono_gc_register_root
#9  0x007fc001a16fab in mono_object_new_fast
#10 0x007fc001a17012 in mono_array_new_specific
#11 0x00000041c0341f in (wrapper managed-to-native) object:__icall_wrapper_ves_icall_array_new_specific (intptr,int)
#12 0x00000041d16b54 in SDG.Framework.Debug.TerminalCommandAttributeFinder:initialize ()
#13 0x00000041c5a9d4 in SDG.Unturned.Setup:Awake ()
#14 0x007fc0018a5715 in mono_print_method_from_ip
#15 0x007fc001a151cc in mono_perfcounter_foreach
#16 0x007fc001a16079 in mono_runtime_invoke
#17 0x007fc002d6ec82 in std::vector<unsigned int, std::allocator<unsigned int> >::_M_fill_insert(__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, unsigned long, unsigned int const&)
#18 0x007fc002d6d03a in std::vector<unsigned int, std::allocator<unsigned int> >::_M_fill_insert(__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, unsigned long, unsigned int const&)
#19 0x007fc002d6cf55 in std::vector<unsigned int, std::allocator<unsigned int> >::_M_fill_insert(__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, unsigned long, unsigned int const&)
#20 0x007fc002da2818 in std::vector<unsigned int, std::allocator<unsigned int> >::_M_fill_insert(__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, unsigned long, unsigned int const&)
#21 0x007fc002d551b9 in std::vector<unsigned int, std::allocator<unsigned int> >::_M_fill_insert(__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, unsigned long, unsigned int const&)
#22 0x007fc002d55644 in std::vector<unsigned int, std::allocator<unsigned int> >::_M_fill_insert(__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, unsigned long, unsigned int const&)
#23 0x007fc002d550f7 in std::vector<unsigned int, std::allocator<unsigned int> >::_M_fill_insert(__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, unsigned long, unsigned int const&)
#24 0x007fc002db8109 in std::_Rb_tree<int, std::pair<int const, int>, std::_Select1st<std::pair<int const, int> >, std::less<int>, std::allocator<std::pair<int const, int> > >::_M_erase(std::_Rb_tree_node<std::pair<int const, int> >*)
#25 0x007fc002c6cf5f in int* std::_V2::__rotate<int*>(int*, int*, int*, std::random_access_iterator_tag)
#26 0x007fc002c6cbcf in int* std::_V2::__rotate<int*>(int*, int*, int*, std::random_access_iterator_tag)
#27 0x007fc002c6c853 in int* std::_V2::__rotate<int*>(int*, int*, int*, std::random_access_iterator_tag)
#28 0x007fc002c6dc3b in int* std::_V2::__rotate<int*>(int*, int*, int*, std::random_access_iterator_tag)
#29 0x007fc002c6e287 in int* std::_V2::__rotate<int*>(int*, int*, int*, std::random_access_iterator_tag)
#30 0x007fc002c733ef in int* std::_V2::__rotate<int*>(int*, int*, int*, std::random_access_iterator_tag)
#31 0x007fc002c605d2 in int* std::_V2::__rotate<int*>(int*, int*, int*, std::random_access_iterator_tag)
#32 0x007fc002dc55f7 in PlayerMain(int, char**)
#33 0x007fc0020080b3 in __libc_start_main
#34 0x005629180ca699 in _init
./start.sh: line 36: 27082 Aborted                 ./Unturned_Headless.x86_64 -batchmode -nographics +InternetServer/"$@"`

**Comment by TH3AL3X** [comment] 2021-04-29 20:25
Probably a steamclient.so issue

**Comment by TH3AL3X** [comment] 2021-04-29 21:09
Pd, cannot start two servers in the same instance

**Comment by Trojaner** [comment] 2021-04-29 21:56
Duplicate of https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2088#issuecomment-756559143 and https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2481

**Comment by SDGNelson** [comment] 2021-04-29 21:58
Was just about to comment the same as Trojaner haha. Unfortunately no news, but Unturned will stay on the "legacy" 2019 LTS so hopefully a fix eventually gets backported.

**Closed by SDGNelson** 2021-04-29 21:58 UTC
