### ISSUE TITLE
LAN Server asks for GSLT

### ISSUE THREAD

**Issue by Kotyarendj** [SmartlyDressedGames/Unturned-3.x-Community#3619] opened 2022-12-29 00:29 UTC
For some reason whenever I launch a server with +LanServer argument, the server tells that it needs to be logged in with Game Server Login Token when trying to join even though it shouldn't. I can still join the server through 127.0.0.1 but not my IP. My friends have the same glitch too
![image](https://user-images.githubusercontent.com/65186102/209888471-e4d6766f-81ba-4f6f-bbd4-cbcc683775b1.png)

**Comment by SDGNelson** [comment] 2022-12-29 21:19
It depends on the address used to connect to the server. If you use the machine's LAN address it does not require GSLT, but if you use your public WAN address it will require GSLT.

**Comment by SDGNelson** [comment] 2023-01-12 01:23
Closing since duplicate of #3617 which should be fixed in the next update if joining through the server list.

**Closed by SDGNelson** 2023-01-12 01:23 UTC
