### ISSUE TITLE
Unturned doesn't use the IP address it's binded to

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Unturned-3.x-Community#1013] opened 2019-08-17 13:42 UTC
Scenario:
Proxy is at IP 1.1.1.1, this is what clients use to connect to. Everything is forwarded to actual server.
Actual server is at IP 1.1.1.2. This is also the default IP of the server. Ideally, people should not know this IP even exists.

Bind is done to 1.1.1.1. Works so far, on server list this IP shows up and people can connect as well.
However, after connecting, when using WireShark to inspect traffic, we can see that 1.1.1.2 (default IP) shows up for some reason, even if it was not the IP connected to. This includes both, reliable (TCP) and unreliable (UDP) packets. Almost all game traffic goes through 1.1.1.2, defeating the whole purpose of the bind. On a side note, you can still not connect through 1.1.1.2 directly, you must always use 1.1.1.1 to connect.

This could be a Steamworks related bug.

**Comment by PandahutMiku** [comment] 2019-08-17 14:47
This may be a windows only bug, but as Trojaner said essentially what happens is, Unturned uses the Main IP/Default IP for the server for sending and receiving game data. You can replicate this easily by joining any one of our servers. 

The main game data will come from .199 in this case, whilst the actual Server is hosted on .204.

Both UDP and TCP come from that IP
![image](https://user-images.githubusercontent.com/17209937/63213603-4b4a2800-c0dc-11e9-9bbb-31a7dd14b944.png)


The only data that comes from the actual IP the game server is bound to is TCP infrequently
![image](https://user-images.githubusercontent.com/17209937/63213533-8566fa00-c0db-11e9-9ca8-4004485e4dae.png)


This should also be replicable if you have a Windows Server with 2 IP's on it.
If you need to test this to any extent and cannot replicate this yourself (not the easiest thing to test), we would be more then glad to host a public test server on a preview build of the game to help.

**Comment by SDGNelson** [comment] 2019-08-17 19:51
Tracking down the game's connection process this is how the relevant code works:

Client enters the 1.1.1.1 address into server connect menu. We call SteamMatchmakingServers.PingServer which waits for ISteamMatchmakingPingResponse.

We get a gameserveritem_t in the response and construct SteamServerInfo from it. When connecting and sending packets to this server the client does not use the IP or port directly, instead SteamNetworking.SendP2PPacket takes the server's SteamID.

The server passes the bound IP to init, however there is not much documentation on the intended purpose: https://partner.steamgames.com/doc/api/steam_gameserver#SteamGameServer_Init

Perhaps the bound IP is only used for communication with Steam? If you see any flaws in this implementation feel free to point them out, and I'll be happy to make any changes.

**Comment by PandahutMiku** [comment] 2019-08-25 18:40
If you were willing to do it, it would be nice if you could make a branch of the Dedicated Server app that uses the lastest Steam API/Steam Networking that uses Steam Relay servers by default, it wouldn't be a true fix, but a workaround. 

I'm sure you already know but currently, this version of Steam Networking uses Relay servers as fall back, and they appear to work fine. 

To note, it's not possible to force the older version of Steam Networking Unturned uses to use Steam Relay servers by default, Steam doesn't share all of it's IP's so we cannot whitelist them and block everyone else and Steam itself was nice enough to confirm there is no other way.
![image](https://user-images.githubusercontent.com/17209937/63654251-f5155e80-c745-11e9-9fd8-3302f9c9b678.png)

**Comment by JustOneMoreBlock** [comment] 2019-08-25 19:08
I brought this issue up as well in #257 

The issue was closed as I didn't push the issue even though I paid about $64 in IP address at the time. Wasn't a total loss as I just moved the IP addresses to another server.

Before the update, the `bind feature` did work as intended where you can define a different IP address and have the same port for all Unturned servers.

The purpose of this was so I could mask the domain name for the "Status Page" and allowed me to easily update as-needed when adding them to voting sites.

Hosting Companies likely sold dedicated IP addresses for Unturned and now they can no longer do so, however, I don't know if this was because of Steams API or something Unturned had done.

Slightly off-topic
In a Minecraft Scenario, we can `bind` our IP addresses, set ports and even mask our domain using `A Records` and/or `SRV Records`.

While it's not needed as most Unturned players use the `Server Lists` to connect to servers unless the design was changed. Removing the `port field` from the connect area and players can easily join with `ip:port` or `domain:port`, however, if SRV support was possible and also added then the `domain:port` would just become `domain`

Minecraft Example:
| SRV Record | Setting |
| -------- | -------- |
| Name | mc, play or @ |
| Target | server.yourdomain.com |
| Protocol | _tcp |
| Service | _minecraft |
| Priority | 0 |
| Weight | 0 |
| Port | Your server port. |

Unturned Example:
| SRV Record | Setting |
| -------- | -------- |
| Name | mc, play or @ |
| Target | server.yourdomain.com |
| Protocol | _tcp |
| Service | _unturned |
| Priority | 0 |
| Weight | 0 |
| Port | Your server port. |

**Comment by PandahutMiku** [comment] 2019-08-25 19:34
> Before the update, the `bind feature` did work as intended where you can define a different IP address and have the same port for all Unturned servers.

I don't know what you mean by that, the bind features does work, our servers are all using port 27015 and different IP Addresses fine. (i.e connect to 216.155.140.202, 216.155.140.203, Port 27015, Both are on same machine) 
This is simply an issue of actual traffic using the wrong IP.

**Comment by SDGNelson** [comment] 2019-08-26 01:34
I definitely like the idea of using the new Steam relay networking API, and it's on my mind for when I can get to the netcode rewrites. My plan is to have an interface implemented by generic sockets, SteamP2P, and the new Steam API. In the future once Linux servers are improved it could potentially be used for hosting Unturned servers in Valve's datacenters as well.

**Comment by SDGNelson** [comment] 2019-11-19 03:21
Closing since this issue was originally a bug report, but supporting the newer Steam API is still a possibility. #1233

**Closed by SDGNelson** 2019-11-19 03:21 UTC
