### ISSUE TITLE
Windows Server 2016 Crash

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#764] opened 2019-04-16 01:09 UTC
The server is crashing in Windows Server 2016. 
Here's the Crash error 
[Crash_2019-04-16_030324.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3082605/Crash_2019-04-16_030324.zip)

**Comment by termsgames** [comment] 2019-04-16 08:32
Do you have the rocket.log?

**Comment by educatalan02** [comment] 2019-04-16 10:44
There's nothing printed in the rocket.log

**Comment by Bradler26** [comment] 2019-04-21 17:00
I also get these crashes as well on windows server 2016. here is my crash log
[Crash_2019-04-20_104342.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3101417/Crash_2019-04-20_104342.zip)

The crash is weird as all my plugins that run on a separate thread continue to work on the logs until eventually the server fully crashes and that file is made.

On a side note, @educatalan02 are you using chatmaster2 by any chance?

**Comment by Trojaner** [comment] 2019-04-21 18:50
@Bradler26 your crash is completely different and caused by Battleye.
Meanwhile, educatalans crash is caused by Unturned / Unity itself.

**Comment by Bradler26** [comment] 2019-04-21 18:52
Hmmm ok. Do you have any idea on how to fix this or is it a battleye issue and must I contact them?

**Comment by archie426** [comment] 2019-04-21 19:00
As you seem to be the only one experiencing this Brad, I would try reinstalling.

**Comment by Bradler26** [comment] 2019-04-21 19:15
Re-installing battleeye? I've just had another one with some different
[Crash_2019-04-21_125604.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3101510/Crash_2019-04-21_125604.zip)
 data so maybe this can help more.

**Comment by Trojaner** [comment] 2019-04-21 20:19
The latest one you have posted *could* be the same reason whats causing educatalans crash.
If educatalan is using ChatMaster with async chat enabled I know what exactly is causing it.
If he does not use ChatMaster or async chat, ChatMaster can not cause it.

**Comment by Bradler26** [comment] 2019-04-21 20:21
In order to test, I have both had Async on and off and I still get it. I do feel like it can be CM as it only happened after you tried a rework but it isn't caused by async

**Comment by Trojaner** [comment] 2019-04-21 20:21
If its not async chat, there is no way ChatMaster is causing it...

**Comment by Bradler26** [comment] 2019-04-21 20:23
Hmmm ok. Maybe a windows update as we both use Windows 2016?

**Comment by Bradler26** [comment] 2019-04-21 20:25
If this helps here are my last 10 crashes.
[Crashes.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3101567/Crashes.zip)

**Comment by educatalan02** [comment] 2019-04-21 21:22
My crash is caused by the library System.Management v4

**Comment by educatalan02** [comment] 2019-04-21 21:22
When I load this library the server crash. And I'm not using ChatMaster2

**Comment by Bradler26** [comment] 2019-05-26 20:22
Is this still happening for you? if so do you have any workshop?

**Comment by Trojaner** [comment] 2019-05-26 21:01
Please upload your crashes including crash.dmp and error.log (but only from the latest Unturned update!). I have figured out how to debug crash dumps.

**Comment by Bradler26** [comment] 2019-07-04 09:12
Quite late but I didnt notice you said you could debug these crashes so here is my latest one from 2 days ago. 
[crashes.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3358584/crashes.zip)

**Comment by Trojaner** [comment] 2019-07-04 10:42
Here is the extracted crash call stack:
![grafik](https://user-images.githubusercontent.com/1809172/60660766-1c942d00-9e61-11e9-912c-aa29ea000881.png)

```
	UnityPlayer.dll!physx::PxsBroadPhaseContextSap::batchUpdateFewUpdates(unsigned int,struct physx::PxcBroadPhasePair * &,unsigned int &,unsigned int &)	Unknown
 	UnityPlayer.dll!physx::BroadPhaseBatchUpdateWorkTask::runInternal(void)	Unknown
 	UnityPlayer.dll!physx::PxsBroadPhaseContextSap::updatePPU(class physx::PxBaseTask *)	Unknown
 	UnityPlayer.dll!physx::Cm::BaseTask::run(void)	Unknown
 	UnityPlayer.dll!PhysxJobFunc()	Unknown
 	UnityPlayer.dll!JobQueue::Exec(struct JobInfo *,__int64,int)	Unknown
 	UnityPlayer.dll!JobQueue::ExecuteOneJob(void)	Unknown
 	UnityPlayer.dll!CompletionTask::ProcessAllPhysicsTasks(void)	Unknown
 	UnityPlayer.dll!PhysicsManager::Simulate(float)	Unknown
 	UnityPlayer.dll!PlayerLoop(void)	Unknown
 	UnityPlayer.dll!PerformMainLoop()	Unknown
 	UnityPlayer.dll!MainMessageLoop()	Unknown
 	UnityPlayer.dll!UnityMainImpl(struct HINSTANCE__ *,struct HINSTANCE__ *,wchar_t *,int)	Unknown
 	UnityPlayer.dll!UnityMain()	Unknown
 	Unturned.exe!00007ff6c77713ee()	Unknown
 	[Frames may be missing, no binary loaded for kernel32.dll]	
 	[External Code]	
```

It looks like the physics engine caused the crash, maybe a workshop mod is responsible for it?

Related issue:
https://issuetracker.unity3d.com/issues/crash-in-physx-pxsbroadphasecontextsap-batchupdate-after-indeterminate-time-in-play-mode

Although it says it fixed in 2017.1, it looks like this is a regression.

Maybe @SDGNelson can use it to debug it more.

**Comment by Bradler26** [comment] 2019-07-04 11:27
Yep I'm sure it is a mod. It's just trying to find what mod it is now. Is there any way to get the item/vehicle ID or some details?

**Comment by Trojaner** [comment] 2019-07-04 11:43
No, impossible

**Comment by Bradler26** [comment] 2019-07-04 11:49
Is it even possible for Nelson to add some form of debugging or is that also impossible?

**Comment by Trojaner** [comment] 2019-07-04 11:50
No because the crash is native and happens in Unity's code, not in Nelsons code.

**Comment by SDGNelson** [comment] 2019-08-01 06:14
Update on this: my hope for a variety of these native crashes is to update to 2018.4 LTS in either August or October.

**Closed** 2019-08-07 07:53 UTC
