### ISSUE TITLE
[Map Editor Help] A wall of pixels appears in the scope, even when there is nothing in sight

### ISSUE THREAD

**Issue by makeloffve** [SmartlyDressedGames/Unturned-3.x-Community#3538] opened 2022-11-26 14:35 UTC
I am using a custom map. but I found something confusing my vision.
In some areas, when I turn on the scope, there is a wall of pixels in front of me, even though there are no objects in front of me, like this:
1. Confused area, unscoped：
![2](https://user-images.githubusercontent.com/12797737/204094129-3b257995-9574-4789-9cac-935ef1cfcf42.jpg)
2. Confused area, scoped：
![1](https://user-images.githubusercontent.com/12797737/204094177-b221aca0-9c7e-4e38-b0cc-fb7389697418.jpg)
3. Normal area, scoped:
![3](https://user-images.githubusercontent.com/12797737/204094186-8ad72157-d1ac-46a1-8954-70527a1e836a.jpg)

**Comment by GazziFX** [comment] 2022-11-26 14:41
Can you share workshop link of map and describe which places cause bug

**Comment by makeloffve** [comment] 2022-11-27 05:27
> Can you share workshop link of map and other used mods. Which places cause bug?

Here is the link of the map: [https://steamcommunity.com/sharedfiles/filedetails/?id=2891514820](link), it's a collection.

**Comment by GazziFX** [comment] 2022-11-27 12:46
I can confirm I have same issue, so its not just graphics bug, and also this map has a lot of erros of missing objects
```
Unable to find object for GUID 7ad52619-38bd-475a-859f-d1dbb2b05aa1, nor by legacy ID 38308
Default buildable object ID 1101 in region (27, 28) loaded as Landmine (this is probably an ID conflict)
```

**Comment by makeloffve** [comment] 2022-11-28 01:59
> I can confirm I have same issue, so its not just graphics bug, and also this map has a lot of erros of missing objects
> 
> ```
> Unable to find object for GUID 7ad52619-38bd-475a-859f-d1dbb2b05aa1, nor by legacy ID 38308
> Default buildable object ID 1101 in region (27, 28) loaded as Landmine (this is probably an ID conflict)
> ```

thanks for your help, I will close the issue.

**Comment by makeloffve** [comment] 2022-11-28 05:45
Normal when setting `Scope Quality` to Off, Once opened  `Scope Quality`, wall of pixels appears
![1](https://user-images.githubusercontent.com/12797737/204202785-c7b17ced-b9af-48f4-8c48-e4e00a152d9a.jpg)

**Comment by makeloffve** [comment] 2022-11-28 05:48
> I can confirm I have same issue, so its not just graphics bug, and also this map has a lot of erros of missing objects
> 
> ```
> Unable to find object for GUID 7ad52619-38bd-475a-859f-d1dbb2b05aa1, nor by legacy ID 38308
> Default buildable object ID 1101 in region (27, 28) loaded as Landmine (this is probably an ID conflict)
> ```

**Comment by makeloffve** [comment] 2022-11-28 06:54
> Default buildable object ID 1101 in region (27, 28) loaded as Landmine (this is probably an ID conflict)

I have solved the error:
 `Unable to find object for GUID 7ad52619-38bd-475a-859f-d1dbb2b05aa1, nor by legacy ID 38308
Default buildable object ID 1101 in region (27, 28) loaded as Landmine (this is probably an ID conflict)`

but problems still exist. so I don't think it was caused by this error.

and @SDGNelson what should I check?

**Comment by GazziFX** [comment] 2022-11-28 10:26
I think some of mods caused it, or maybe its invisible object. Disabling all mods solves it

**Comment by UsernameIsUnavailible** [comment] 2022-11-28 11:13
Its a mod issue from CE1. Afaik Nardo won't fix this

**Comment by makeloffve** [comment] 2022-11-28 13:51
> Afaik Nardo won't fix this

Thanks for your help! I am sure its a bug from Mod City Expansion2, and will report it to Nardo soon.

**Closed** 2022-11-28 13:52 UTC

**Comment by UsernameIsUnavailible** [comment] 2022-11-28 14:24
> > Afaik Nardo won't fix this
> 
> Thanks for your help! I am sure its a bug from Mod City Expansion2, and will report it to Nardo soon.

Its a bug from CE1.. Which Nardo won't fix due to him losing CE1 files, If its CE2 then I've never seen it before..
