### ISSUE TITLE
Cant scroll

### ISSUE THREAD

**Issue by Tairiku-Ookami** [SmartlyDressedGames/Unturned-3.x-Community#2222] opened 2020-12-13 13:12 UTC
I know you keep closing these because theres already a report but you HAVE to fix the bug where you cant scroll over item slots. This is literally a game breaking bug and every single person hates it. I am almost about to quit unturned myself over this dumb mechanic. It makes inventory management especially in fire fights 1000x harder. Please fix ASAP

**Comment by SDGNelson** [comment] 2020-12-13 17:08
As you mentioned, this is a duplicate of #2211 so I will close it.

For the moment it is still possible to use the scroll wheel if hovering over empty space or the scroll bar itself.

Unfortunately it is a limitation of uGUI, so fixing it will be messy. I will need to fork uGUI to change how the scroll wheel is handled.

**Closed by SDGNelson** 2020-12-13 17:08 UTC
