### ISSUE TITLE
2 issues with linux servers

### ISSUE THREAD

**Issue by jatapa** [SmartlyDressedGames/Unturned-3.x-Community#944] opened 2019-07-26 19:00 UTC
Now I am not sure if this happens to everybody both linux and windows but after the latest update my servers have had these 2 problems.

1. Running commands from console does not work.

2. The servers will freeze right after they are up or after some time and after that nobody can connect to them.

Also tried without plugins and atleast the first issue still happens

**Comment by Mithallas** [comment] 2019-07-26 19:04
same here

**Comment by aman7** [comment] 2019-07-26 19:19
yes its happening with me too.

**Comment by Trojaner** [comment] 2019-07-26 19:21
Related to #932

**Comment by Ascivv1** [comment] 2019-07-26 20:54
I am also having this happen to me as well

**Comment by SDGNelson** [comment] 2019-07-26 22:53
For the meantime: add -NoDefaultConsole to the command-line.

I'll probably do some more work on a Linux implementation of the console IO in the future, but in the meantime if it's blocking other input workarounds (e.g. Trojaner's straightforward solution in #932) then the best workaround is to add -NoDefaultConsole to the command-line.

**Comment by Ascivv1** [comment] 2019-07-26 22:58
What if I am using a RocketMod script? How do I do this?

**Comment by SDGNelson** [comment] 2019-07-26 23:02
If you post the script as a gist I can direct exactly, but there are a few options:

1. If calling the ServerHelper.so script, -NoDefaultConsole could be added to the command-line arguments in there, or added to the arguments passed to the script.

2. If the custom script passes command-line arguments then -NoDefaultConsole could simply be added to the arguments passed to the script.

3. If the custom script calls Unturned_Headless.x86_64 directly then -NoDefaultConsole can be added to the line that calls it.

**Comment by Trojaner** [comment] 2019-07-26 23:21
If anyone uses https://github.com/ImperialPlugins/unturned-docker/ and docker, you can also just attach -NoDefaultConsole to the docker command:
```
docker run -it -p 27015:27015 -p 27016:27016 -e SERVER_TYPE=rm4 --restart unless-stopped --name myserverinstance imperialplugins/unturned -NoDefaultConsole 
```

**Comment by Mithallas** [comment] 2019-07-26 23:59
`#!/bin/bash
# This script starts a Unturned 3 server on Linux machines
# To start servers with this script, place it next to Unturned.exe
# Syntax: start.sh <instance name>
# Author: fr34kyn01535

export MONO_IOMAP=all

#CONFIG
INSTANCE_NAME=$1
STEAMCMD_HOME="$PWD/../steamcmd"
UNTURNED_HOME="$PWD"

#COLORS
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLLOW='\033[0;33m'
NC='\033[0m'

#Steam checks
STEAMCMD_API=$STEAMCMD_HOME/linux64/steamclient.so
UNTURNED_API=$UNTURNED_HOME/lib
printf "Steam: "
if [ -f $STEAMCMD_API ]; then
	if diff $STEAMCMD_API $UNTURNED_API >/dev/null ; then
		printf "${GREEN}UP TO DATE${NC}\n\n"
	else
		cp $STEAMCMD_API $UNTURNED_API
		printf "${YELLLOW}UPDATING${NC}\n\n"
	fi
else
	printf "${RED}NOT FOUND${NC}\n\n"
fi

cd $UNTURNED_HOME

if [ -f RocketLauncher.exe ]; then
	ulimit -n 2048
	export LD_LIBRARY_PATH=$UNTURNED_HOME/lib:$LD_LIBRARY_PATH
	mono RocketLauncher.exe $INSTANCE_NAME
else
	echo "RocketLauncher not found."
fi
`

**Comment by Trojaner** [comment] 2019-07-27 00:04
The RocketLauncher doesn't support passing arguments to Unturned.

**Comment by Ascivv1** [comment] 2019-07-27 00:17
[RM Scripts.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3437681/RM.Scripts.zip)

Here is my scripts folder (Couldn't send .bat so I had to use .zip)

**Comment by Trojaner** [comment] 2019-07-27 00:44
You are using the same scripts as Mith with RocketLauncher.
You can not use -NoDefaultConsole.

**Comment by Ascivv1** [comment] 2019-07-27 00:48
How can I use -NoDefaultConsole?

**Comment by Mithallas** [comment] 2019-07-27 00:54
you put it in the 
./Unturned_Headless.x86_64 -batchmode -nographics -NoDefaultConsole "$@"
line within your ServerHelper.sh
although I did that and still got SIGILL

**Comment by Trojaner** [comment] 2019-07-27 01:11
You don't need to edit the ServerHelper.sh (and I dont recommend doing so)
When executing the ServerHelper.sh just add the -NoDefaultConsole argument to it.

e.g.
./ServerHelper.sh -NoDefaultConsole +secureserver/myserver

**Comment by Ascivv1** [comment] 2019-07-27 01:13
But what do I do if I want to start the RocketMod script with -NoDefaultConsole?

**Comment by HanaForward** [comment] 2019-07-27 08:28
same here, ubuntu 18.04
i try to fix RocketLauncher,but no effect。
if add  -NoDefaultConsole  to RocketLauncher arguments ， console does not work too and worse

**Comment by HanaForward** [comment] 2019-07-27 08:30
@Trojaner  use ServerHelper or other shell
linux console can ouput and input？

**Comment by aman7** [comment] 2019-07-27 09:32
so for the linux users only way left is to use docker? since RocketLauncher doesnt takes any arguments.

**Comment by TH3AL3X** [comment] 2019-07-27 09:45
I have the same problem

**Comment by Eiromplays** [comment] 2019-07-27 10:25
So I will need to switch to docker or?

**Comment by KyeNormanGill** [comment] 2019-07-27 10:33
Using 
```
./ServerHelper.sh -NoDefaultConsole -logfile 2>&1 +secureserver/Rocket | tee Servers/Rocket/Server.log
```
Still console doesn't work, i don't have enough experience with docker to use it for my server. Any ETA on a fix for this?

**Comment by Trojaner** [comment] 2019-07-27 10:41
> But what do I do if I want to start the RocketMod script with -NoDefaultConsole?

You can't, it's that simple.

> so for the linux users only way left is to use docker? since RocketLauncher doesnt takes any arguments.

> So I will need to switch to docker or?

No one ever claimed you must use docker?!

> ./ServerHelper.sh -NoDefaultConsole -logfile 2>&1 +secureserver/Rocket | tee Servers/Rocket/Server.log

What exactly does not work?
Did you also use export TERM=xterm before that?

**Comment by aman7** [comment] 2019-07-27 10:52
which file is calling ./ServerHelper.sh, i dont see it in my Start.sh
`#!/bin/bash
GAME_INSTALL_DIR="$PWD"
server=$1

cd $GAME_INSTALL_DIR
ulimit -n 2048
LD_LIBRARY_PATH=$GAME_INSTALL_DIR/lib64:$GAME_INSTALL_DIR/Unturned_Headless/Plugins/x86_64 mono Rocket.Unturned.Launcher.exe $1
`

**Comment by Trojaner** [comment] 2019-07-27 10:54
You are using the RocketLauncher which is *not* using ServerHelper...

**Comment by aman7** [comment] 2019-07-27 10:56
so what is the other way to use ServerHelper and not the RocketLauncher. what should be the Start script.

**Comment by Trojaner** [comment] 2019-07-27 10:58
I have posted the related start scripts at least 2 times *facepalm*

**Comment by gegtor** [comment] 2019-07-27 11:04
```
senpai@scw-gifted-goldberg:~/Unturned_Server$ ./ServerHelper.sh -NoDefaultConsole +secureserver/SV1
Set current directory to /home/senpai/Unturned_Server
Found path: /home/senpai/Unturned_Server/Unturned_Headless.x86_64
Mono path[0] = '/home/senpai/Unturned_Server/Unturned_Headless_Data/Managed'
Mono config path = '/home/senpai/Unturned_Server/Unturned_Headless_Data/MonoBleedingEdge/etc'
Preloaded 'libsteam_api.so'
Preloaded 'steamclient.so'
Logging to /home/senpai/.config/unity3d/Smartly Dressed Games/Unturned/Player.log
CAppInfoCacheReadFromDiskThread took 10 milliseconds to initialize
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Bad thread local
senpai@scw-gifted-goldberg:~/Unturned_Server$```

It crashes like this

**Comment by Trojaner** [comment] 2019-07-27 11:05
Can you also add -logifle 2>&1 so we can actually get console output.
Dont forget to type `export TERM=xterm` before that.

**Comment by gegtor** [comment] 2019-07-27 11:07
`./ServerHelper.sh -logifle 2>&1 -NoDefaultConsole +secureserver/SV1`

Same thing happens with logfile argument

**Comment by Trojaner** [comment] 2019-07-27 11:08
You have a typo in your logfile argument.
The output must be different when typed correctly.

**Comment by HanaForward** [comment] 2019-07-27 11:09
-logfile 2>&1

**Comment by gegtor** [comment] 2019-07-27 11:13
Dumm me i didn't even looked what i'm typing in

Output works now

To be sure i started clean server and it stops here:
```
[registered] /tphere (Rocket.Unturned.Commands.CommandTphere/tphere)
Other mapping to: Rocket.Unturned.Commands.UnturnedCommands/unadmin / Rocket.Unturned.Commands.CommandUnadmin/unadmin
[registered] /unadmin (Rocket.Unturned.Commands.CommandUnadmin/unadmin)
[registered] /v (Rocket.Unturned.Commands.CommandV/v)
[registered] /vanish (Rocket.Unturned.Commands.CommandVanish/vanish)
This server will automatically save every 1800 seconds
UnloadTime: 1.376000 ms
isHolidayActive called before backend realtime was available!
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Current backend date: 1/1/1970 12:00:42 AM
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Halloween: [10/27/2018 12:00:01 AM, 11/1/2018 11:59:59 PM]
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Christmas: [12/10/2018 12:00:01 AM, 12/31/2018 11:59:59 PM]
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

isHolidayActive called before backend realtime was available!
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Setting up 1 worker threads for Enlighten.
  Thread -> id: 7f89218ed700 -> priority: 1 
Bad thread local
```

**Comment by KyeNormanGill** [comment] 2019-07-27 11:21
Do i run `export TERM=xterm` as a seperate command before running the server? I did exactly what gegtor did, but input doesn't work. Output was always fine. Just input.

**Comment by HanaForward** [comment] 2019-07-27 11:22
@SDGNelson  can you modify it back? please

**Comment by gegtor** [comment] 2019-07-27 11:22
Okay it seems like i had other server running in the background and that caused the `Bad thread local` error

It works now

**Comment by gegtor** [comment] 2019-07-27 11:25
> export TERM=xterm

Do
~export TERM=xterm
Then
~./ServerHelper.sh -logfile 2>&1 -NoDefaultConsole +secureserver/<server-name>

**Comment by Trojaner** [comment] 2019-07-27 11:27
I can confirm that console input is currently broken even with -NoDefaultConsole.

**Comment by HanaForward** [comment] 2019-07-27 11:28
I hope to cancel this update.

**Comment by gegtor** [comment] 2019-07-27 11:35
@HanaForward 

There were much worse updates than this

Even if everything is on fire there is no such thing as rollback update for Nelson

**Comment by aman7** [comment] 2019-07-27 12:33
> 
> 
> @KyeNormanGill
> 
> Do
> `~export TERM=xterm`
> Then
> `~./ServerHelper.sh -logfile 2>&1 -NoDefaultConsole +secureserver/<server-name>`

are you able to run multiple instance?

**Comment by HanaForward** [comment] 2019-07-27 12:36
@gegtor   wow
just hope Nelson can rollback update  hhhh

**Comment by jatapa** [comment] 2019-07-27 13:51
@HanaForward no need for that just do what trojaner said it's not that hard

**Comment by aman7** [comment] 2019-07-27 13:56
> 
> 
> @HanaForward no need for that just do what trojaner said it's not that hard

good thing is its working, but it crashes when we run more than 1 instance, also console is not working, and nobody have confirmed about the freezing issue. so there should be a patch/rollback/workaround.

**Comment by HanaForward** [comment] 2019-07-27 14:57
The servers will freeze right after they are up or after some time and after that nobody can connect to them.
same here

**Comment by Ascivv1** [comment] 2019-07-27 15:08
I haven't gotten a single freeze since using > ./ServerHelper.sh -logfile 2>&1 -NoDefaultConsole +secureserver/<server-name>

**Comment by Trojaner** [comment] 2019-07-27 15:25
> good thing is its working, but it crashes when we run more than 1 instance

Did you also change the port?

**Comment by aman7** [comment] 2019-07-27 15:30
yes, and as i remember if you start the second instance on same port, it doesnt effect the 1st instance, just 2nd instance doesnt start.

**Comment by gegtor** [comment] 2019-07-27 18:10
I can also confirm that no freezes occurred with `./ServerHelper.sh -logfile 2>&1 -NoDefaultConsole +secureserver/`

And i also confirm that multiple instances are broken with this script^

**Comment by Trojaner** [comment] 2019-07-27 19:27
Posting crash logs would be useful

**Comment by Mithallas** [comment] 2019-07-27 19:52
[UnityDebug_Server_euro1.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3438537/UnityDebug_Server_euro1.log)

**Comment by Mithallas** [comment] 2019-07-27 19:56
Find it odd that Ascivv1 linux servers are working using trojaner's start script...maybe a certain distro works?

**Comment by SDGNelson** [comment] 2019-07-27 20:09
Been looking into it this afternoon, also ran into a case where the console became unresponsive. I'll also add "export TERM=xterm" to the ServerHelper.sh script. Interestingly with the logfile redirect and default console enabled it somewhat works e.g. you get the red ? for bad commands, but does not play nicely with the file output.

I don't believe any changes that would affect running multiple instances or modify the previous console behavior (with -NoDefaultConsole anyway) were made, so I'm going to read back through all the commits from this update.

**Comment by jatapa** [comment] 2019-07-27 20:15
@Mithallas he does it by having every server in it's own folder like you have to install unturned for every server yoi have if you do it that way

**Comment by SDGNelson** [comment] 2019-07-27 20:23
The only related change was that previously Console.WriteLine was always called during CommandWindow.log, and somewhat related is that the log files now share read/write access - but there is a log file for each server instance. I presume the when running multiple server instances you're using multiple server IDs e.g. +SecureServer/A and +SecureServer/B (otherwise they will clobber each other). 

Other than that there were not any changes to running multiple instances or console IO when compared to the previous linux version. (Obviously a lot of the consle IO code was rewritten, but with -NoDefaultConsole the linux behavior is identical aside from the Console.WriteLine difference.)

**Comment by aman7** [comment] 2019-07-27 20:54
> 
> 
 I presume the when running multiple server instances you're using multiple server IDs e.g. +SecureServer/A and +SecureServer/B (otherwise they will clobber each other).
> 
i have made scripts like this for all my servers, but the time i start 2nd instance, 1st instance crashes and i get these errors.
https://pastebin.com/EDGDJ9Tb

**Comment by SDGNelson** [comment] 2019-07-27 21:20
Thanks for sharing that log: searching "_L_unlock_13 null exception" comes up with several other unity games which all ran into similar crashes on linux, but the native library varies e.g. physx, std containers, steamworks, etc. Their posts all seem to be edited to "it just started working" after validate game or installing misc stuff. Maybe try updating your system packages e.g. equivalent of "yum update" / "apt-get update"?

**Comment by KyeNormanGill** [comment] 2019-07-27 22:36
I'm still not able to get input to work, through ubuntu console.
I ran `export TERM=xterm`
 then
 `./ServerHelper.sh -logfile 2>&1 -NoDefaultConsole +secureserver/Rocket`. 
Which started the server up fine. But i still can't run any commands.

**Comment by Trojaner** [comment] 2019-07-27 22:51
Same here, I do not get input as well.

@SDGNelson 
I had this SteamAPI_ISteamNetworking_IsP2PPacketAvailable issue before this patch too. It's not related to the last update.

**Comment by SDGNelson** [comment] 2019-07-27 23:02
Right now I'm waiting for a linux-only update to finish building that restores the old Console.WriteLine behavior in-case that fixes it, as in windows testing somehow flushing console output is required to get new input lines.

One thing I realized however is where does the linux input get sent to command input in the first place? Since the vanilla game is not listening for standard input except in the newer console implementation does that mean rocket is sending input?

**Comment by Trojaner** [comment] 2019-07-27 23:06
https://github.com/RocketMod/Rocket.Unturned/blob/legacy/Rocket.Unturned/U.cs#L236
This is the only way how RocketMod handles input. The RocketLauncher doesn't do any magic, I believe it only redirects stdin like if we started the Unturned executable directly. Input also used to work if we do not use RocketLauncher or -logfile at all as it seems.

For Linux flushing console would be great too as piping with tee and grep cause issues at the moment because of that.

**Comment by SDGNelson** [comment] 2019-07-27 23:09
That doesn't explain how input is getting to onCommandWindowInputted from onInputCommitted however. 😕 I wonder if something custom somewhere is referring to CommandWindow.input which was left behind accidentally, so I've marked those obsolete but they will be created now and onInputText is bound again.

**Comment by SDGNelson** [comment] 2019-07-27 23:11
Yeah your edit there explains it! 😄 
Below that line it checks CommandWindow.input and invokes CommandWindow.input.onInputText externally with standard input. In this coming patch that should work fine again since CommandWindow.input is getting created again.

**Comment by SDGNelson** [comment] 2019-07-27 23:16
I won't do it yet in the interest of keeping it a small stable update, but for the next update I will integrate that old threaded console stuff officially. #957 
Update should be out within the next 45 min, and only requires a linux dedicated server update (no client changes, hash changes or version changes).

**Comment by Ascivv1** [comment] 2019-07-27 23:21
How do we upgrade the dedi server specifically?

**Comment by Trojaner** [comment] 2019-07-27 23:23
```
login anonymous
app_update 1110390
```

**Comment by Ascivv1** [comment] 2019-07-28 00:37
Is the update out yet?

**Comment by KyeNormanGill** [comment] 2019-07-28 01:05
Thankyou @SDGNelson you legend

**Comment by SDGNelson** [comment] 2019-07-28 02:44
Was away, but yep the update's been out. One other note is that you do not need to specify "-NoDefaultConsole" anymore, as the Linux default console in the current version is empty aside from matching the old Console.WriteLine behavior.

**Comment by Mithallas** [comment] 2019-07-28 02:56
do we still need to start servers with serverhelper or should we be able to go back to using the rocket start.sh?

**Comment by Trojaner** [comment] 2019-07-28 02:57
RocketLauncher should work fine again but if you want a future proof
solution you should use the ServerHelper

Mithallas <notifications@github.com> schrieb am So., 28. Juli 2019, 05:56:

**Comment by Ascivv1** [comment] 2019-07-28 22:34
Rocket start script just freezes when I try to start the server. ServerHelper.sh works fine though

**Comment by Mithallas** [comment] 2019-07-29 05:33
rocket start script works for me

**Comment by SDGNelson** [comment] 2019-07-29 06:10
In the .1 patch TERM=xterm is in the ServerHelper.so script, and if a server startup command is not specified the dedicated server will warn and explain the different options.

With vanilla you can also specify -ThreadedConsole on linux, but output redirect or other trickery is required for now.

**Closed** 2019-08-01 05:47 UTC

**Comment by Mithallas** [comment] 2019-08-16 21:45
my linux server just freezed up like it did when this post was opened.

**Comment by aman7** [comment] 2019-08-16 21:51
same is happening with me.
