### ISSUE TITLE
bug seeds

### ISSUE THREAD

**Issue by eumodded** [SmartlyDressedGames/Unturned-3.x-Community#1989] opened 2020-09-20 23:23 UTC
seeds almost instant grow i tested it on 4 server on works on all with maxskills

https://youtu.be/nYgnG8pXIlw

**Comment by PandahutMiku** [comment] 2020-09-21 00:40
Are you sure this isn't a quirk/setting of the server you are playing on? Are they your servers, and did you try running with no plugins? I cannot replicate this on my own server with max skills, it just slowly goes up like normal.

**Comment by eumodded** [comment] 2020-09-21 01:10
I tryed it on a vanille server 
But i Will do more testing tomorrow

**Comment by SDGNelson** [comment] 2020-12-31 19:29
Closing because it was probably config (and I could not reproduce at the time either), but feel free to comment and I will re-open.

**Closed by SDGNelson** 2020-12-31 19:29 UTC
