### ISSUE TITLE
Night vision scope and bullet holes

### ISSUE THREAD

**Issue by Yusuf225** [SmartlyDressedGames/Unturned-3.x-Community#2475] opened 2021-03-14 19:39 UTC
So basically when you shoot your gun and the little bullet hole appears it appears with a green night-vision tint. However, when you scope in it appears without a night-vision tint. See the video below. (Sorry for not being able to scope in 100% my mouse isn't the greatest) https://youtu.be/jIL-oR7E3F4

**Comment by SDGNelson** [comment] 2021-03-14 20:57
Thanks for the report, but closing because duplicate of #2421. Unfortunately this is a bit of a mess and I have not decided how to handle it yet.

**Closed by SDGNelson** 2021-03-14 20:57 UTC
