### ISSUE TITLE
Vehicles glitch/debugger's beret

### ISSUE THREAD

**Issue by schelchok** [SmartlyDressedGames/Unturned-3.x-Community#2198] opened 2020-12-08 07:56 UTC
https://drive.google.com/file/d/1BVmQu6A_H_odoNgnIDMGf1GpFP88fRCK/view
Can you consider this vehicles glitch? I think it's very
seriously bug because you can flip any vehicles without carjack. Thanks for
responding! Also, i wanna my beret, bereeeeet

**Comment by DiFFoZ** [comment] 2020-12-08 08:07
Duplicate of #2102

**Comment by iBowie** [comment] 2020-12-08 08:21
I think it's just russian's mentality, but let's not get in to this topic. I've posted quite a lot issues here, but I never ask for beret because all these issues don't worth it.

**Comment by schelchok** [comment] 2020-12-08 10:07
> I think it's just russian's mentality, but let's not get in to this topic. I've posted quite a lot issues here, but I never ask for beret because all these issues don't worth it.

Why don't worth? Wdym?

**Comment by schelchok** [comment] 2020-12-08 10:09
> Duplicate of #2102. Also, why many Russians trying to get a beret?

Idk lmao. But it's srs glitch

**Comment by SDGNelson** [comment] 2020-12-17 23:35
As mentioned by DiFFoZ, this is a known issue - "between a rock and a hard place" type situation.

**Closed by SDGNelson** 2020-12-17 23:35 UTC
