### ISSUE TITLE
After update 3.22.16.0 some players can't connect and are stuck in queue #1

### ISSUE THREAD

**Issue by gegtor** [SmartlyDressedGames/Unturned-3.x-Community#3442] opened 2022-09-30 18:30 UTC
This issue is currently being discussed at Unturned official Discord

After update 3.22.16.0 some players can't connect and are stuck in queue #1

**Comment by gegtor** [comment] 2022-09-30 19:09
Yes it's happening on my network of 23 servers 

They are stuck in the queue screen even on empty or half full servers

**Comment by SDGNelson** [comment] 2022-09-30 19:11
Have you already tried disabling plugins? Would recommend the usual of enabling a couple at a time to narrow down the cause.

If you can attach the Client.log from a player stuck in the queue or the Server.log there might be a clue.

**Comment by gegtor** [comment] 2022-09-30 19:16
I doubt it's plugin related as reports of the same issue on Discord state that it happens even on vanilla servers
Also I never saw this issue in the past and it popped up only today after the update

Here are client and player logs I found on Unturned official Discord because I myself can't replicate the issue 
[Player.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9687057/Player.log)
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9687058/Client.log)

<img width="996" alt="Screenshot 2022-09-30 at 21 15 15" src="https://user-images.githubusercontent.com/10978723/193341024-cb7ea69f-7624-4d15-9def-14aa4caf1fda.png">
You can find the discussion about it here

**Comment by gegtor** [comment] 2022-10-01 02:45
These logs aren't from my server but sure

Try this server
IP: S5.RAID-CITY.COM
Port: 27055

**Comment by Rattman1233** [comment] 2022-10-01 03:33
hey, im the guy who started that discussion on discord, heres some info that might/might not be useful and fixes weve already tried:
- i run the server from my pc, not from dedicated hardware
- it was happening before the most recent update
- modifying draw distance has not worked
- disabling battleye has not worked
- the server used to work completely flawlessly 
- the first time i noticed the bug was on august 17 (this was the first time the server had been up in a while)
- switching maps and wiping groups.dat doesnt work
if need be i can send the server files and put the server up for you to try to reproduce the bug on, im about to head to sleep so in about 9 hours i can up the server (it also uses my personal IP so id prefer to keep that as private as possible)

**Comment by Akos60** [comment] 2022-10-01 07:37
I tried to join the server mentioned above and I have the same issue. I tried the following:

- Disable all cosmetics and gun skins
- Use a new steam account

Here are my log files:
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9689820/Client.log)
[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9689821/Client_Prev.log)
[Player.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9689823/Player.log)
[Player-prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9689824/Player-prev.log)

**Comment by SDGNelson** [comment] 2022-10-01 21:56
I tried joining the S5.RAID-CITY.COM server and got as far as authenticating with server, but did not receive the "accepted" response. 

Is S5.RAID-CITY.COM your server @gegtor? Since Akos mentioned it worked fine with a VPN: is your server in or around the RU region? There have been reports that RU traffic is flaky recently. Otherwise my guess is that a plugin on the server is patching one of the methods related to accepting new clients. There might be an exception if you can share the log file, but otherwise I would still recommend testing without plugins.

@Rattman1233 if you would be more comfortable could you email me your server's IP privately please? (nelson@smartlydressedgames.com) I could try connecting and see if it gets stuck in the same place.

@Akos60 Do you have a server experiencing the same problem?

**Comment by gegtor** [comment] 2022-10-01 22:02
@SDGNelson Yes I own RAID-CITY

Our servers are hosted in Germany and recently our data center had an issue with it's connectivity because of severed fiber cable
https://status.hetzner.com/incident/d2b7730f-06ed-415a-b988-f25876ff86f3 
I think they are still fixing stuff and we are experiencing 4-10% packet loss 
Can packet loss be the reason for failed authentication?

This outage coincided with Friday update

**Comment by Rattman1233** [comment] 2022-10-01 23:30
@SDGNelson alright, i shot you an email with the IP.

**Comment by Akos60** [comment] 2022-10-02 07:57
@SDGNelson I'm just an admin on RAID-CITY experiencing the same issue.

**Comment by SDGNelson** [comment] 2022-10-02 20:57
Maybe it is related to that data center outage then. The messages are sent in reliable mode, but if all of them are getting dropped - maybe on a specific route - there is nothing the game can do.

**Comment by Rattman1233** [comment] 2022-10-04 00:51
alright, so with the logs from my server nelson determined that the reason my server had this problem was that it was set to third person only. i dont know if thats whats causing other peoples issues, but setting my server to first person solved it for me

**Comment by gegtor** [comment] 2022-10-04 04:43
I can confirm now this was a strange networking issue

This ticket can be closed

**Comment by SDGNelson** [comment] 2022-10-04 04:53
Glad to hear it is all sorted out!
The third-person-only issue will be fixed for the next update as well.

**Closed by SDGNelson** 2022-10-04 04:53 UTC
