### ISSUE TITLE
When you enter a vehicle you stay where you've entered from

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2148] opened 2020-12-04 19:47 UTC
Vehicle UI also stays
https://www.youtube.com/watch?v=mQCL0TNQpPY

**Comment by SDGNelson** [comment] 2020-12-04 19:48
Can you attach your Client.log file please? Looks like there must be an exception somewhere

**Comment by iBowie** [comment] 2020-12-04 19:50
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5645106/Client.log)

**Comment by SDGNelson** [comment] 2020-12-04 19:57
Thanks for the log. It looks like the gun HUD bug caused by the rangefinder is causing an exception when entering the vehicle. Should be fixed in the .1 patch because the rangefinder bug will be fixed there

**Closed by SDGNelson** 2020-12-04 19:57 UTC
