### ISSUE TITLE
Server fails to load after update.

### ISSUE THREAD

**Issue by ksdsksd** [SmartlyDressedGames/Unturned-3.x-Community#4224] opened 2023-11-24 18:16 UTC
Caught exception loading levels in legacy per-server workshop Maps folder (/Servers/Default/Workshop/Maps):
Access to the path '/Servers/Default/Workshop/Maps' is denied.
  at System.IO.FileSystem.CreateDirectory (System.String fullPath) [0x00191] in <2161c9885dd04ff291b79db9349c4b9b>:0 
  at System.IO.Directory.CreateDirectory (System.String path) [0x0002c] in <2161c9885dd04ff291b79db9349c4b9b>:0 
  at SDG.Unturned.ReadWrite.createFolder (System.String path, System.Boolean usePath) [0x00018] in <c54ea8a9e34e46a7928fb025002c666b>:0 
  at SDG.Unturned.Level.ScanKnownLevels () [0x00307] in <c54ea8a9e34e46a7928fb025002c666b>:0 
Permission denied
NullReferenceException: Object reference not set to an instance of an object
  at SDG.Unturned.CommandWindow.LogError (System.Object text) [0x0001e] in <c54ea8a9e34e46a7928fb025002c666b>:0 
  at SDG.Unturned.UnturnedLog.internalException (System.Exception e) [0x00027] in <c54ea8a9e34e46a7928fb025002c666b>:0 
  at SDG.Unturned.UnturnedLog.internalException (System.Exception e) [0x0003a] in <c54ea8a9e34e46a7928fb025002c666b>:0 
  at SDG.Unturned.UnturnedLog.exception (System.Exception e) [0x0000f] in <c54ea8a9e34e46a7928fb025002c666b>:0 
  at SDG.Unturned.UnturnedLog.exception (System.Exception e, System.String message) [0x00006] in <c54ea8a9e34e46a7928fb025002c666b>:0 
  at SDG.Unturned.Level.ScanKnownLevels () [0x0039d] in <c54ea8a9e34e46a7928fb025002c666b>:0 
  at SDG.Unturned.Level.getLevels (SDG.Unturned.ESingleplayerMapCategory categoryFilter) [0x00000] in <c54ea8a9e34e46a7928fb025002c666b>:0 
  at SDG.Unturned.Assets.AddMapSearchLocations () [0x00000] in <c54ea8a9e34e46a7928fb025002c666b>:0 
  at SDG.Unturned.Assets+<LoadAllAssets>d__104.MoveNext () [0x001af] in <c54ea8a9e34e46a7928fb025002c666b>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <8aebd7627ade4efeae84aca54d1d32ad>:0

**Comment by SDGNelson** [comment] 2023-11-24 18:20
Thanks for the report, but closing as duplicate of #4222

**Closed by SDGNelson** 2023-11-24 18:20 UTC
