### ISSUE TITLE
[NPC] Is it possible to create an NPC with two conditions with only one needed to be do, like with an "or" or it's equivalent?

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#2056] opened 2020-10-30 01:07 UTC
I'm trying to make an NPC who will only give out quests depending on whether the player has completed enough civilian quests signified by a flag. I also want it to be achieved through a reputation, so is it possible to do something like this or it's equivalent?

Message_1_Conditions 2
Message_1_Condition_0_Type Flag_Short
Message_1_Condition_0_ID 
Message_1_Condition_0_Value 1
Message_1_Condition_0_Logic Equal
Message_1_Condition_0_Or
Message_1_Condition_1_Type Reputation
Message_1_Condition_1_Value 25

**Comment by SDGNelson** [comment] 2020-10-30 16:05
Duplicate of #2055

**Closed by SDGNelson** 2020-10-30 16:06 UTC
