### ISSUE TITLE
Map I made myself 

### ISSUE THREAD

**Issue by RubbleTV** [SmartlyDressedGames/Unturned-3.x-Community#4328] opened 2024-01-28 11:31 UTC
![299804995-47d9f8e1-f144-4c9f-ac0b-0128d1e36b68.png](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/83584625/6c2d37b2-b8a0-49a0-a5c4-49e37beef3d7)

Workshop Log

[2022-05-03 16:33:57] Loading workshop items for 0 installed apps for user [a:1:3801673830]:
[2022-05-03 16:34:10] [AppID 1110390] Loaded workshop items in "C:\steamcmd\steamapps\workshop" (0 installed, 0 needed)

[2023-02-06 13:11:54] Loading workshop items for 1 installed apps for user [a:1:3819286949]:

[2023-02-06 13:18:46] Loading workshop items for 1 installed apps for user [a:1:3364135259]:

[2024-01-26 20:00:55] Client version: 1705108307
[2024-01-26 20:00:55] Loading workshop items for 1 installed apps for user [a:1:2828676421]:

By the way my new map id is 3146526712

**Comment by SDGNelson** [comment] 2024-01-29 16:40
Closing as duplicate of #4326, responded there.

**Closed by SDGNelson** 2024-01-29 16:40 UTC
