### ISSUE TITLE
black textures for OSX users

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#561] opened 2019-01-31 17:22 UTC
Not sure what could be a problem but most of the OSX users see textures in complete black (including some of vanilla objects like boulders)

**Comment by SDGNelson** [comment] 2019-02-04 16:36
This would be caused by missing the per-platform masterbundle variants, e.g. *_mac.masterbundle. Do you know which vanilla boulders are having issues? Personally in my testing the mac version is all working properly.

**Comment by baranmod** [comment] 2019-02-07 12:09
Using hawaii and russia boulders, black ones are hawaii I believe

**Comment by SDGNelson** [comment] 2019-02-07 18:27
Loaded them up this morning on a 2017 macbook air running the latest osx and they displayed correctly (unfortunately or fortunately).

There was an issue with black roads on France which will be fixed in the next update

**Comment by SDGNelson** [comment] 2019-02-11 17:39
Closing for the meantime. Haven't received any direct reports of black shaders from OSX users in the past couple weeks aside from the France objects which were fixed, but I'll keep an eye out.

**Closed by SDGNelson** 2019-02-11 17:39 UTC
