### ISSUE TITLE
Map bugs help

### ISSUE THREAD

**Issue by ZoomGYT** [SmartlyDressedGames/Unturned-3.x-Community#1610] opened 2020-04-14 22:35 UTC
Hello! I have uploaded my map to whorkshop and when I use it in singleplayer it works perfect but when I do it in my vps the map is bugged and I don't know what happens, I have removed and re-uploaded the map, the errors are these:
(There are about 15 equal lines)
(Filename: Line: 0)
(Filename:  Line: 0)

BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "PlayLife V1/Objects/144/Nav"

[VIDEOO]  https://youtu.be/8zTociaDVGk

I have the asset mods pack installed and I have tried to remove it to put it and it still does not go

**Comment by ZoomGYT** [comment] 2020-04-14 22:37
https://youtu.be/8zTociaDVGk

**Comment by CyberAndrii** [comment] 2020-04-15 08:09
Duplicate of #1609

**Comment by SDGNelson** [comment] 2020-04-15 20:01
Closing because (as CyberAndrii mentioned) it is a duplicate issue.

**Closed by SDGNelson** 2020-04-15 20:01 UTC
