### ISSUE TITLE
Airdrops glitched after today's update

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1494] opened 2020-03-06 23:38 UTC
Apparently, players can't access airdrops now. At first I thought its related to airdrops dropping on side, but now I see that airdrops which land vertically - are not accessible too.

**Comment by SDGNelson** [comment] 2020-03-06 23:54
Just gave this a test on vanilla server and they seem to be accessible. There were a lot of changes to airdrops for an upcoming event, so there is a bug related to the visual cleanup on client which will be patched. If they are inaccessible though I suspect it's plugin related. Are any plugins hooking the Carepackage component?

**Comment by baranmod** [comment] 2020-03-07 00:31
I guess it could be a plugin. Using one to edit spawn tables for airdrops. Will check it out. Thanks

**Comment by baranmod** [comment] 2020-03-07 22:02
All good now, except one thing. When crate lands - some duplicated crate with parachute appears, "bouncing" around the area. Is it this visual bug you mentioned before?

**Comment by SDGNelson** [comment] 2020-03-08 00:38
Yep that's the visual bug. I would have put out a patch for it yesterday, but considering it's the only bug reported so far and relatively rare (only in MP with the occasional airdrop) I decided to wait until Monday.

What ended up being the cause of the bug? It sounds like a useful option to include in vanilla.

**Comment by baranmod** [comment] 2020-03-09 11:33
As a non developer - can't tell exact reason. What developer told me is that some changes been done to methods used by plugin.

**Comment by SDGNelson** [comment] 2020-03-09 18:17
This should be fixed in the patch now.

**Closed by SDGNelson** 2020-03-09 18:17 UTC
