### ISSUE TITLE
ask for SDG Devkit

### ISSUE THREAD

**Issue by ruabota** [SmartlyDressedGames/Unturned-3.x-Community#4453] opened 2024-05-08 09:04 UTC
where can i get it? during map production i need those hook

**Comment by MoltonMontro** [comment] 2024-05-08 09:49
I'm not sure what "those hook" is referring to. But the devkit was merged into the normal level editor quite a while ago now. A majority of the features from the devkit are available in the normal level editor.

**Comment by ruabota** [comment] 2024-05-08 10:59
<img width="470" alt="c25be49ccdfc3063ab3e145c520d7805" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/169245406/f7b0a2f2-63ca-419c-a2ec-e76ca356401b">

**Comment by MoltonMontro** [comment] 2024-05-08 11:09
The ambience volume is available from the Volumes section of the level editor. (So are other volumes!)

**Comment by ruabota** [comment] 2024-05-08 12:26
I know that the hook has been moved into normal level editor, but that is some problems during development that i need  this hook("AmbianceVolume"), and i haven't find it in Project.unitypackage

**Comment by ruabota** [comment] 2024-05-08 12:28
i even rollback unturned to 2017 edition, but i haven't find it too

**Comment by Jdance-Media** [comment] 2024-05-08 20:34
> I know that the hook has been moved into normal level editor, but that is some problems during development that i need this hook("AmbianceVolume"), and i haven't find it in Project.unitypackage

Those types of modhooks are not officially supported ones. Use https://github.com/olie304/UnturnedScripts.
Put the scripts in your main Assets folder.

**Comment by ruabota** [comment] 2024-05-09 16:36
> > I know that the hook has been moved into normal level editor, but that is some problems during development that i need this hook("AmbianceVolume"), and i haven't find it in Project.unitypackage
> 
> Those types of modhooks are not officially supported ones. Use https://github.com/olie304/UnturnedScripts. Put the scripts in your main Assets folder.

that script can not use alone, it need something to work

**Comment by SDGNelson** [comment] 2024-05-09 17:33
Sorry to say that yes, it sounds like you're looking for some scripts that aren't officially supported, as Jdance-Media mentioned (thanks!).

Some modders have managed to re-create enough of components from the base game to be serialized in asset bundles (like in the repo linked), however there may be unexpected behavior if used in unintended ways. We can only officially support the scripts that were intended to be used in asset bundles, which are the scripts included in the project package.

**Closed by SDGNelson** 2024-05-09 17:33 UTC
