### ISSUE TITLE
Error when launching the server on linux

### ISSUE THREAD

**Issue by gamper1** [SmartlyDressedGames/Unturned-3.x-Community#236] opened 2018-03-16 21:53 UTC
`General: Quit due to provider exception: GameServer API initialization failed!
[registered] /admins (Rocket.Unturned.Commands.UnturnedCommands/admins)
[registered] /airdrop (Rocket.Unturned.Commands.UnturnedCommands/airdrop)
[registered] /animal (Rocket.Unturned.Commands.UnturnedCommands/animal)
[registered] /ban (Rocket.Unturned.Commands.UnturnedCommands/ban)
[registered] /bans (Rocket.Unturned.Commands.UnturnedCommands/bans)
[registered] /bind (Rocket.Unturned.Commands.UnturnedCommands/bind)
[registered] /chatrate (Rocket.Unturned.Commands.UnturnedCommands/chatrate)
[registered] /cheats (Rocket.Unturned.Commands.UnturnedCommands/cheats)
[registered] /cycle (Rocket.Unturned.Commands.UnturnedCommands/cycle)
[registered] /day (Rocket.Unturned.Commands.UnturnedCommands/day)
[registered] /debug (Rocket.Unturned.Commands.UnturnedCommands/debug)
[registered] /experience (Rocket.Unturned.Commands.UnturnedCommands/experience)
[registered] /filter (Rocket.Unturned.Commands.UnturnedCommands/filter)
[registered] /flag (Rocket.Unturned.Commands.UnturnedCommands/flag)
[registered] /gamemode (Rocket.Unturned.Commands.UnturnedCommands/gamemode)
[registered] /give (Rocket.Unturned.Commands.UnturnedCommands/give)
[registered] /gold (Rocket.Unturned.Commands.UnturnedCommands/gold)
[registered] /hide_admins (Rocket.Unturned.Commands.UnturnedCommands/hide_admins)
[registered] /kick (Rocket.Unturned.Commands.UnturnedCommands/kick)
[registered] /kill (Rocket.Unturned.Commands.UnturnedCommands/kill)
[registered] /loadout (Rocket.Unturned.Commands.UnturnedCommands/loadout)
[registered] /log (Rocket.Unturned.Commands.UnturnedCommands/log)
[registered] /map (Rocket.Unturned.Commands.UnturnedCommands/map)
[registered] /maxplayers (Rocket.Unturned.Commands.UnturnedCommands/maxplayers)
[registered] /mode (Rocket.Unturned.Commands.UnturnedCommands/mode)
[registered] /modules (Rocket.Unturned.Commands.UnturnedCommands/modules)
[registered] /name (Rocket.Unturned.Commands.UnturnedCommands/name)
[registered] /night (Rocket.Unturned.Commands.UnturnedCommands/night)
[registered] /owner (Rocket.Unturned.Commands.UnturnedCommands/owner)
[registered] /password (Rocket.Unturned.Commands.UnturnedCommands/password)
[registered] /permit (Rocket.Unturned.Commands.UnturnedCommands/permit)
[registered] /permits (Rocket.Unturned.Commands.UnturnedCommands/permits)
[registered] /perspective (Rocket.Unturned.Commands.UnturnedCommands/perspective)
[registered] /players (Rocket.Unturned.Commands.UnturnedCommands/players)
[registered] /port (Rocket.Unturned.Commands.UnturnedCommands/port)
[registered] /pve (Rocket.Unturned.Commands.UnturnedCommands/pve)
[registered] /quest (Rocket.Unturned.Commands.UnturnedCommands/quest)
[registered] /queue_size (Rocket.Unturned.Commands.UnturnedCommands/queue_size)
[registered] /reputation (Rocket.Unturned.Commands.UnturnedCommands/reputation)
[registered] /resetconfig (Rocket.Unturned.Commands.UnturnedCommands/resetconfig)
[registered] /save (Rocket.Unturned.Commands.UnturnedCommands/save)
[registered] /say (Rocket.Unturned.Commands.UnturnedCommands/say)
[registered] /shutdown (Rocket.Unturned.Commands.UnturnedCommands/shutdown)
[registered] /slay (Rocket.Unturned.Commands.UnturnedCommands/slay)
[registered] /spy (Rocket.Unturned.Commands.UnturnedCommands/spy)
[registered] /sync (Rocket.Unturned.Commands.UnturnedCommands/sync)
[registered] /teleport (Rocket.Unturned.Commands.UnturnedCommands/teleport)
[registered] /time (Rocket.Unturned.Commands.UnturnedCommands/time)
[registered] /timeout (Rocket.Unturned.Commands.UnturnedCommands/timeout)
[registered] /unban (Rocket.Unturned.Commands.UnturnedCommands/unban)
[registered] /unpermit (Rocket.Unturned.Commands.UnturnedCommands/unpermit)
[registered] /vehicle (Rocket.Unturned.Commands.UnturnedCommands/vehicle)
[registered] /votify (Rocket.Unturned.Commands.UnturnedCommands/votify)
[registered] /weather (Rocket.Unturned.Commands.UnturnedCommands/weather)
[registered] /welcome (Rocket.Unturned.Commands.UnturnedCommands/welcome)
[registered] /whitelisted (Rocket.Unturned.Commands.UnturnedCommands/whitelisted)
[registered] /more (Rocket.Unturned.Commands.CommandMore/more)
[registered] /admin (Rocket.Unturned.Commands.CommandAdmin/admin)
[registered] /broadcast (Rocket.Unturned.Commands.CommandBroadcast/broadcast)
[registered] /compass (Rocket.Unturned.Commands.CommandCompass/compass)
[registered] /effect (Rocket.Unturned.Commands.CommandEffect/effect)
[registered] /exit (Rocket.Unturned.Commands.CommandExit/exit)
[registered] /god (Rocket.Unturned.Commands.CommandGod/god)
[registered] /heal (Rocket.Unturned.Commands.CommandHeal/heal)
[registered] /help (Rocket.Unturned.Commands.CommandHelp/help)
[registered] /home (Rocket.Unturned.Commands.CommandHome/home)
[registered] /i (Rocket.Unturned.Commands.CommandI/i)
[registered] /item (Rocket.Unturned.Commands.CommandI/item)
[registered] /investigate (Rocket.Unturned.Commands.CommandInvestigate/investigate)
[registered] /p (Rocket.Unturned.Commands.CommandP/p)
[registered] /permissions (Rocket.Unturned.Commands.CommandP/permissions)
[registered] /rocket (Rocket.Unturned.Commands.CommandRocket/rocket)
[registered] /tp (Rocket.Unturned.Commands.CommandTp/tp)
[registered] /tphere (Rocket.Unturned.Commands.CommandTphere/tphere)
[registered] /unadmin (Rocket.Unturned.Commands.CommandUnadmin/unadmin)
[registered] /v (Rocket.Unturned.Commands.CommandV/v)
System.SystemException: Error running gmcs: Cannot find the specified file
  at Mono.CSharp.CSharpCodeCompiler.CompileFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00000] in <filename unknown>:0
  at Mono.CSharp.CSharpCodeCompiler.CompileAssemblyFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00000] in <filename unknown>:0
  at Mono.CSharp.CSharpCodeCompiler.CompileAssemblyFromFile (System.CodeDom.Compiler.CompilerParameters options, System.String fileName) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0
[registered] /vanish (Rocket.Unturned.Commands.CommandVanish/vanish)
Steam can not be initialized: Steamworks GameServer is not initialized.
Error in MulticastDelegate PluginsLoaded: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Steamworks GameServer is not initialized.
  at Steamworks.InteropHelp.TestIfAvailableGameServer () [0x00000] in <filename unknown>:0
  at Steamworks.SteamGameServer.SetKeyValue (System.String pKey, System.String pValue) [0x00000] in <filename unknown>:0
  at Rocket.Unturned.U.<Initialize>m__5 () [0x00000] in <filename unknown>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <filename unknown>:0
  at Rocket.Core.Extensions.MulticastDelegateExtension.TryInvoke (System.MulticastDelegate theDelegate, System.Object[] args) [0x00000] in <filename unknown>:0
This server will automatically save every 1800 seconds
General: Community Module has been unloaded `

some help please? i am sorry if i might've posted this in the wrong place

**Comment by Jonnyfencing1** [comment] 2018-03-17 13:05
This issue has already been discussed

**Comment by Trojaner25** [comment] 2018-03-17 13:29
Duplicate of #172 
A fix is also posted there
Please  close this issue.

**Comment by andreipaul951** [comment] 2018-03-31 19:45
that one is really long , could you paste the fix there please ?

**Comment by Jonnyfencing1** [comment] 2018-03-31 19:46
If you want the fix you'll have to read through it

**Comment by andreipaul951** [comment] 2018-03-31 19:51
Come on man , i don't know very good english too, could you help me ?

**Comment by Jonnyfencing1** [comment] 2018-03-31 19:51
No the answer is there

**Comment by andreipaul951** [comment] 2018-03-31 19:52
thanks for being a fag

**Comment by Jonnyfencing1** [comment] 2018-03-31 20:18
Your Welcome

**Comment by gamper1** [comment] 2018-04-01 16:52
stop talking bad to each other , i fixed it with help of some friend ...  but players can't connect

**Comment by Jonnyfencing1** [comment] 2018-04-01 16:53
I haven't spoken a bad word to him @gamper1

**Comment by gamper1** [comment] 2018-04-01 17:26
you didn't ... he did , but for some reason he deleted the messages or something 
anyway:
when i do debug this is what i get: 
debug
Server State
90114063097899013 167.99.143.71:27015
Bytes sent: 0B
Bytes received: 0B
Average bytes sent: 0B
Average bytes received 0B
Packets sent: 0
Packets received: 0
Average packets sent: 0
Average packets received: 0
Updates per second: 120%
Ticks per second: 100%
Active zombies: 0
Active animals: 1
 some help ?

**Comment by PrimeOpalGamer** [comment] 2018-04-02 00:34
Port FWD maybe?

**Comment by gamper1** [comment] 2018-04-02 06:07
No need to fwd i am on vps

**Comment by PrimeOpalGamer** [comment] 2018-04-02 10:47
i would still check it using "canyouseeme.org" a port checker because with mine the port isn't free and im running a VPS VM also, and new to Linux (Ubuntu 14.04)so I'm going to have my friend that knows it show me how to Port FWD and the VPS VM that he is running is also at a data center,, never had any problems running it at his house with Port FWD

**Comment by Trojaner25** [comment] 2018-04-02 10:52
This isnt a port issue. As already explained its a bug of the game and a workaround exists.
#172

**Comment by PrimeOpalGamer** [comment] 2018-04-02 11:23
yes i understand but for me right now it is a port FWD issue im just sharing my end also, and I've read over #172 30 time just to get my fresh installed server to run

**Comment by gamper1** [comment] 2018-04-02 12:58
@Trojaner25 In that post they are talking about the steamclient.so thing that wasn't a problem from me , my server does not send or gets any bytes

**Comment by PrimeOpalGamer** [comment] 2018-04-02 13:27
and with my instance everything is starting correctly i just cant direct connect at all, or Internet tab ether

**Comment by gamper1** [comment] 2018-04-02 16:53
Yeah same problem as me , what should we do?

**Comment by PrimeOpalGamer** [comment] 2018-04-02 17:21
well I'm having the owner of the VM (tho he is slacking around) try to route the Public IP into the VM correctly so the VM can be seen at lease by the game/internet (I'm trying to push my server out within the next 24-48 hours also,,) i will update once I've found out what all he has done

**Comment by gamper1** [comment] 2018-04-02 18:51
for me the ports are open, but isn't working

**Comment by PrimeOpalGamer** [comment] 2018-04-04 13:26
need to have a network bridge in place so the VM can be accessed through the public IP, not only your private network for games

**Comment by Trojaner25** [comment] 2018-04-05 20:32
@gamper1 No one will help you with that attitude

**Comment by PrimeOpalGamer** [comment] 2018-04-05 20:44
my dude, dang we both share the same problem, the i was using his VPS at a data center and he is also partly using Digital Ocean for his stuff, and i agree @Trojaner25 , like if you didn't want me to be talking and explaining my side of the same problem then Deuces

**Comment by gamper1** [comment] 2018-04-06 18:09
I am getting triggered becaude you keep telling me about your ports ,but somrone who knows what a cloud center and what linux is ,will not even care about ports. For me the problem is *(was) with mono , i had the actual version ,and the server works fine now that i am using a older mono version .
This section is called issues , but nobody is helping someone , this page seems like a tumor on github....

**Comment by Trojaner25** [comment] 2018-04-07 07:58
"issues" is for bug reporting. Its not your personal help site. Thats why no one will help you here.

**Comment by Jonnyfencing1** [comment] 2018-04-08 09:53
I completely agree with @Trojaner25 as well as due to the fact that this has been answered before #172

**Closed** 2018-05-04 19:37 UTC
