### ISSUE TITLE
Please FIx it Bug

### ISSUE THREAD

**Issue by idkprivacy** [SmartlyDressedGames/Unturned-3.x-Community#2216] opened 2020-12-12 12:30 UTC
https://www.youtube.com/watch?v=1YUVbdCw_Gk&feature=youtu.be

heres the video about me making it so you were be able to Scroll down while hovering over the items on the ground well u cant do that now but u have to go to the side and scroll or manual hold that arrow and drag it down to go down and up to go up So please fix it and please make it so you can spam click while your in your inventory.

**Comment by educatalan02** [comment] 2020-12-12 12:55
Similar to #2215

**Comment by SDGNelson** [comment] 2020-12-12 22:11
Duplicate of https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2211#issuecomment-743361330

**Closed by SDGNelson** 2020-12-12 22:11 UTC
