### ISSUE TITLE
Client stuck at loading map screen when server is shutdown

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#4036] opened 2023-07-29 11:45 UTC
To catch this issue, need a server with a big map and bundle (e.g. Buak). After that, do what on the video.

https://www.youtube.com/watch?v=niby7N0MdAg

Note at 0:30 of video that screenshot was changed and the game lagged. This is because Steam noticed that we dropped connection with server and disconnect it, but we still load assets and then the map.

Logs:
```
[2023-07-29 10:56:13] Initializing ClientTransport_SteamNetworkingSockets
[2023-07-29 10:56:13] Client Steam Networking available
[2023-07-29 10:56:13] Client connecting to xxx:27016
[2023-07-29 10:56:13] Client connection with YYY ready
[2023-07-29 10:56:13] Server specified 1 workshop item(s), querying details
[2023-07-29 10:56:14] Server's allowed IP for Workshop downloads: xxx
[2023-07-29 10:56:14] Server has 1 valid workshop item(s), of which 1 need to be downloaded
[2023-07-29 10:59:02] Workshop item installed: 3000549606
[2023-07-29 10:59:02] Workshop File "Buak" (3000549606) added asset search location "C:\Program Files (x86)\Steam\steamapps\workshop\content\304930\3000549606\Buak\Bundles"
[2023-07-29 10:59:02] Workshop item downloaded: 3000549606
[2023-07-29 10:59:02] Already registered newly downloaded workshop item '3000549606', so ignoring this callback
[2023-07-29 10:59:02] Client UGC waiting for assets to finish loading...
... (From here video timestamp 0:30)
[2023-07-29 10:59:55] Client connection problem detected locally (5003) "Connection dropped"
[2023-07-29 10:59:55] Disconnecting: Client transport failure: "Lost connection to host or Steam network."
[2023-07-29 10:59:55] Disconnected
[2023-07-29 10:59:56] Returning to main menu
[2023-07-29 10:59:56] Loading additive default menu
[2023-07-29 10:59:57] Refreshing Steam inventory
[2023-07-29 10:59:57] Applying graphics settings (loaded menu)
[2023-07-29 10:59:57] Applied graphics settings
[2023-07-29 10:59:57] Requesting 3 Steam community announcements
[2023-07-29 10:59:57] Unable to get current Steam beta name, defaulting to "public"
[2023-07-29 10:59:57] Checking for updates on Steam beta branch "public"...
[2023-07-29 10:59:57] Requesting popular workshop files from the past 30 day(s) for news feed
[2023-07-29 10:59:57] Requesting Steam item store prices
[2023-07-29 10:59:57] Lost connection to host or Steam network.
[2023-07-29 10:59:57] Menu UI ready
[2023-07-29 10:59:57] Received popular workshop files
[2023-07-29 10:59:57] Requesting workshop file details for news feed (2981121870)
[2023-07-29 10:59:57] Received Steam community announcements
[2023-07-29 10:59:57] Game version is up-to-date
[2023-07-29 10:59:57] Long delay between Updates: 1.893069s
[2023-07-29 10:59:58] Received workshop file details for news feed
[2023-07-29 10:59:58] Item store using fallback culture Russian (Russia) for Steam currency code RUB
[2023-07-29 10:59:58] Received Steam item store prices - Discounted: 0 All: 302
[2023-07-29 10:59:58] Received Steam item store live config - New: 0 Featured: 3
[2023-07-29 11:00:03] Linking spawns because changes were detected
[2023-07-29 11:00:03] Link spawns: 1 children, 172 sorted/normalized and 50 parents
[2023-07-29 11:00:03] Loading new assets took 60.3240085s
[2023-07-29 11:00:03] Adding 5247 asset(s) from origin Vanilla Built-in Assets to server mapping
[2023-07-29 11:00:03] Adding 4713 asset(s) from origin Workshop File "Buak" (3000549606) to server mapping
[2023-07-29 11:00:03] Loading server level (Buak)
[2023-07-29 11:00:03] Unlocked Steam achievement "Buak_Visited"
[2023-07-29 11:00:03] Survival
[2023-07-29 11:00:05] Unable to find consolidated version of shader Particles/Standard Unlit for material Fireflies in Buak_Fireflies Object/Model_0
[2023-07-29 11:00:06] Failed to load content reference 'Assets/BuakMasterbundle/Material_Palettes/Buak_Paint_Buckets/Bucket_Paint_00_A.mat' from master bundle 'buak.masterbundle' as Material
[2023-07-29 11:00:09] Unable to find consolidated version of shader Particles/Standard Unlit for material Moths in Buak_Moths Object/Model_0
[2023-07-29 11:00:21] Loading 64 landscape tiles
[2023-07-29 11:00:30] Found 12096 foliage v2 tiles
[2023-07-29 11:00:30] Found 25 foliage used assets in header
[2023-07-29 11:00:31] Long delay between Updates: 10.32485s
[2023-07-29 11:00:31] 0 texture(s) in Standard (Decalable) group
[2023-07-29 11:00:31] 253 texture(s) in Standard (Specular setup) (Decalable) group
[2023-07-29 11:00:31] 7 texture(s) in Custom/Card group
[2023-07-29 11:00:31] 14 texture(s) in Custom/Foliage group
[2023-07-29 11:00:31] Level texture atlas generation took: 390ms
[2023-07-29 11:00:36] Mesh 'Microwave_1' has more materials (2) than subsets (1)
... (removed log Mesh 'Microwave_1' has more materials (2) than subsets (1) multiple times)
[2023-07-29 11:00:37] Level static batching took: 5411ms
[2023-07-29 11:00:37] Long delay between Updates: 5.436125s
[2023-07-29 11:00:38] Level "Buak" not using hardcoded special events
```
or full log:
[ClientFull.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/12207021/ClientFull.log)

**Comment by sunnamed434** [comment] 2023-07-29 16:28
I've had the same issue today on PEI map

**Comment by CyberAndrii** [comment] 2023-07-29 18:55
Duplicate of https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3965

**Comment by SDGNelson** [comment] 2023-07-29 19:38
Sorry about this, CyberAndrii is correct that this is still on my to-investigate list. It *should* eventually timeout on the client but maybe not. I've been kind of lazy in July but intend to catch up on all of the to-investigates in a bigger next update.

**Comment by SDGNelson** [comment] 2023-08-10 00:29
Thanks for the report! I think what happened here is the OnClientTransportFailure callback is happening at a point when disconnection isn't handled properly, namely when workshop is downloading/installing/loading and/or the level is loading. Ordinarily the game ignores timeouts during these - in part because there can be long hitches - but the underlying Steam Networking Sockets library can still disconnect in the meantime. Interrupting loading will/would be a nightmare right now, so for the next update I've changed it to defer the failure handling until the current uninterruptible state completes.

**Closed** 2023-10-13 18:28 UTC
Labels: Resolved on preview branch
