### ISSUE TITLE
"invisible" items (item icon not loading) and flickering on attachment menu.

### ISSUE THREAD

**Issue by Lion4K** [SmartlyDressedGames/Unturned-3.x-Community#4405] opened 2024-03-30 03:00 UTC
I tried asking on Discord, but, no one said anything there, so I'm bringing this here.

I started playing the game again after some time, and noticed that several and at random, so, not always the same, item icons aren't being rendered, leaving an "invisible" item on the screen (their models renders just fine).
Also, this affect the main menu shop and cosmetics menu as well.

And, for some reason, there's a flickering on the attachments menu, effectively preventing me from selecting attachments.
sometimes the flicker is there, sometimes is not (usually when I join the server or start the world), and sometimes the flicker "slows down" allowing me to select an attachment if I try repeatedly clicking on it for a few seconds. Totally at random too.

I tried:
verifying the game cache
unsubscribing from all workshop items 
uninstalling and removing ALL files from steamapps\unturned, workshop contents, etc, etc
lowering resolution
disabling and or lowering all graphical settings
increasing and decreasing the display's refresh speed
limiting the FPS both in game and via RivaTuner
 ~~selling my soul to the closest entity~~

but, nothing worked. unfortunately.

So, here am I asking for help.

If there's any other information I can provide to help getting to the root of this, just ask for, also, logs if needed, or something like that, idk.

I'm gonna include some images and a short video about the flickering.

https://cdn.discordapp.com/attachments/1222332768248266782/1223463066772050031/Unturned_2024-03-29_23-41-27.mp4?ex=6619f1c5&is=66077cc5&hm=313cb5f26beb835cb657550a1fd70caccc320573bde740cbd058482bf80f8ee1&

https://cdn.discordapp.com/attachments/1222332768248266782/1223462553716396193/image.png?ex=6619f14b&is=66077c4b&hm=6f62eaaa056a667ee95f1b1879496c20698ad38fe024f14e9700be5de6b8d8c5&

https://cdn.discordapp.com/attachments/1222332768248266782/1223462301504507935/image.png?ex=6619f10f&is=66077c0f&hm=c6930702d625d725f1d31d5acab7a53f4f4defe71176006d74178426f8a2ecbd&

https://cdn.discordapp.com/attachments/1222332768248266782/1222708115149947002/image.png?ex=661732ab&is=6604bdab&hm=cedae80f1566772d6447b660db01213c710d0f4ac39ebb63b6b4267f028ced9d&

https://cdn.discordapp.com/attachments/1222332768248266782/1222708020505743360/image.png?ex=66173294&is=6604bd94&hm=dbfb94666805b7379f61894f538178586f5ea75f06eb23db0df078f779fd564e&

**Comment by SDGNelson** [comment] 2024-03-30 03:34
Sorry about this. You're on macOS right?
Do you have -Glazier= specified in your launch options for Unturned in Steam?
Do you have item icon anti-aliasing enabled?

**Comment by Lion4K** [comment] 2024-03-30 03:49
Oh no I don't game on Mac, this is on my AMD PC.

PC Specs if it matter at all:
AMD A520 Platform PCIe 3.0
R5 5500
RX 7600
32GB 3200MHz
1TB NVMe
1TB SSD
1TB HDD

**Comment by Lion4K** [comment] 2024-03-30 03:51
Also, I don't know that Launch argument, -Glazier, what does it does? should I add it?
And yes, ALL graphical options activated / on Ultra, including the icon AA, but I had tested with it disabled

**Comment by SDGNelson** [comment] 2024-03-30 18:39
I have an AMD GPU as well and haven't been running into this. 😕 🤔 After it happens again could you attach both the Client.log and Player.log files please? There might be some kind of related error. (Client.log is game and Player.log is engine.) The ones mentioned in this support article: https://support.smartlydressedgames.com/hc/en-us/articles/12144393042324-Reporting-a-crash

You shouldn't need the launch option, but if you last played a while ago it might have been set back then. Can you double check it's *not* set in Unturned's launch options please?

**Comment by Lion4K** [comment] 2024-03-30 23:28
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/14813563/Client.log)
[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/14813566/Client_Prev.log)
[Player.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/14813567/Player.log)
[Player-prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/14813568/Player-prev.log)


yeah it wasn't there the command line. 

(unrelated, but, do you remember me? like, from the beginning)

**Comment by Lion4K** [comment] 2024-03-31 15:25
I tested with the -force-vulkan argument and the game seems way snappier and no more flickering.
I can't remember if the default is OpenGL or D3D thou.


Happy Easter!

**Comment by SDGNelson** [comment] 2024-03-31 19:10
Thanks for the logs. Unfortunately no graphics-related errors, but there were several exceptions I will investigate, including one GUI exception that could be related.

I'm afraid my memory isn't as good as I wish it was - my memory is unreliable to say the least - but I do remember you've long been a member of the community and that you've made quite a few posts.

Glad to hear Vulkan seems to be working well for you. Fingers crossed that maybe that will clear up the issue. 🤞 

Happy Easter!

**Comment by Lion4K** [comment] 2024-03-31 19:41
Oh good there's something in the logs, otherwise would be hard to chase a ghost.

I'm asking because I used to have you on Steam as a Friend but someday you yeeted me lol.

Yeah after some hours I don't seem to be having any problems anymore, hopefully it will persist.

**Comment by Lion4K** [comment] 2024-03-31 19:55
Yeah, one can't just praise something can one?
Just because I praised it, it started acting up again.

But I noticed that it only happens when Im facing a certain direction (?!?) ill try to pin this one down

**Comment by SDGNelson** [comment] 2024-04-01 15:45
From [this account](https://steamcommunity.com/id/0x4E656C736F6E/)? Sorry, if that's the case then it wasn't anything personal, at some point to help with work-life balance I started removing Unturned contacts from my Steam account friend lists in favor of communicating through work channels like email, GitHub, support site, etc. Still something I'm working on.

If I can get some fixes to those exceptions - particularly the GUI one - into the next update then hopefully that'll resolve it.

**Comment by Lion4K** [comment] 2024-04-02 01:10
Nope, from [this other account](https://steamcommunity.com/profiles/76561198237219890) we used to hang on TeamSpeak when the map DevTest was the only map there was. BTW that one should make a come back, loved that map. I know it's an Arena Map now, but it was a cool map to survive in it.

**Comment by SDGNelson** [comment] 2024-04-02 15:26
Oh, I'm sorry to say that's definitely not one of my accounts. It is possible we hung out on TeamSpeak - I recall spending a lot of time on TeamSpeak around 2014 and earlier - but that account you linked is someone pretending to be me.

**Comment by Lion4K** [comment] 2024-04-03 01:05
huh, that's really strange.
I recall the day where if memory serves me well, we (you, Zami, Sven, me and there were other ppl too) on TS and a gang blew up an ATM a block away from my house, but the shock wave it made was so loud that everyone stopped talking trying to understand what happened, and I said something along the lines of that not being the first time and be careful when visiting Brazil lol that was like 10 years ago or something.

But, about the logs, did you see something? also I tried this argument -NoDeferAssets that seems to be keeping the assets loaded at all times, but I didn't noticed any increase in RAM usage, it still using a little under 4GB. is the game 32bit only? I think not because it also ran on MacOS 12 and that's 64bit only, but the Windows build could be different idk.
But with both -force-vulkan -NoDeferAssets arguments it seems to be holding better, if you wanna see more logs just say the word.

**Comment by SDGNelson** [comment] 2024-04-03 20:21
Yikes! Wow, that would be a long time ago now. I think my memory starts improving around 2017-2018 which would be a few years later.

`-NoDeferAssets` loads every Unity asset from the asset bundle at startup when otherwise certain assets are loaded later as-needed. I doubt this would affect the flickering item icons. And yes, Unturned still has both 32-bit and 64-bit versions, so you would have the 64-bit version installed.

The potential fixes related to the logs you uploaded are on the preview branch, but I'm not sure when it will be released onto the main branch yet.

**Comment by Lion4K** [comment] 2024-04-04 01:04
But would I have it on Windows too? seeing that it still can load 32bit apps (unlike MacOS).
I ask because I notice that despite having 32GB the game NEVER crosses the 4GB limit which would be characteristic of a 32bit app.
Anyway is there a way to enforce the 64bit version?

**Comment by GazziFX** [comment] 2024-04-04 04:23
> I ask because I notice that despite having 32GB the game NEVER crosses the 4GB limit which would be characteristic of a 32bit app.
> Anyway is there a way to enforce the 64bit version? 

Some mods take up to 8-10GB 💀

**Comment by Lion4K** [comment] 2024-04-04 12:18
> > I ask because I notice that despite having 32GB the game NEVER crosses the 4GB limit which would be characteristic of a 32bit app.
> > Anyway is there a way to enforce the 64bit version? 
> 
> Some mods take up to 8-10GB 💀
> And also 64 bit has more SIMD extensions and allows to process more data per instruction

8-10GB in RAM?

**Comment by SDGNelson** [comment] 2024-04-04 16:03
Yes, you almost certainly have the 64-bit version installed. If you want to double-check that it can use more than 4 GB you could install a few curated maps.

**Comment by Lion4K** [comment] 2024-04-04 21:47
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/10391955/a03d6da3-4aeb-445c-bac7-73ef9eacdde4)

Or check in Task Manager

**Comment by Lion4K** [comment] 2024-04-07 15:08
Idle curiosity I have since ever, I thought of opening a new issue, but, nah.
Why can't we look totally down while swimming? 
like, we can look the same amount as if on prone position, but there's no floor to block our sight while swimming.

**Comment by SDGNelson** [comment] 2024-04-08 14:22
The issue tracker isn't really the intended place for general questions, but I do know the view pitch restriction on swimming is unpopular and I might adjust it as part of some movement updates this year. (input/movement was the 2nd most popular request)

**Comment by Lion4K** [comment] 2024-04-09 12:28
> The issue tracker isn't really the intended place for general questions

I know, sorry, but, I also knew that asking anywhere else I'd probably never get an answer and tossing another issue at your way wouldn't be good for metrics (I think?!).




> but I do know the view pitch restriction on swimming is unpopular and I might adjust it as part of some movement updates this year. (input/movement was the 2nd most popular request)

It has been like this since ever, why is it the way it is? by design or was a mistake? I know some people would probably complain if it changes now, after all, September (right?) the 3.0 reaches 10 years (wow). I miss DevTest (i know it's an arena map now, but I'd like if it made back as a standard map with all the new features the game amassed over the last decade.

**Comment by SDGNelson** [comment] 2024-04-09 18:33
Nah no metrics here. The pitch limit was "by design" yes.

**Comment by Lion4K** [comment] 2024-04-12 01:56
I see.
Well I wouldn't change it now. after all of this time.

If you have the spare time, would you put Devtest map on workshop for us? like, updated with all of the newer features.
It's an awesome map to play alone or a small server.

**Comment by SDGNelson** [comment] 2024-04-12 18:03
Unfortunately, I don't have a copy of the original survival version of the map. Perhaps you'd be interested in modifying the current arena version back into a survival map though?

**Comment by Lion4K** [comment] 2024-04-13 03:53
That's something that can be done? Like, isn't the map locked down or something?
I know I have backed up 2 Festive PEI map's into workshop before, because why not, but, never tried editing them. 
If it's possible id surely try to revive it.

**Comment by SDGNelson** [comment] 2024-04-13 17:38
Yeah! Any map can be edited by creating a file called ".unlocker" in the map folder. The main reason for locking maps is to prevent players from accidentally modifying them and then being unable to join servers.

**Comment by Lion4K** [comment] 2024-04-15 18:07
Oh, btw, I Just Saw something that made me wonder.

Why don`t we have an Android version of the game?

What I just saw was a "launcher" that could run the PC version on Android, it`s on the play store and all.

OFC that would mean a Ton of work, or is It? Because There`s this game called CloneHero that IS a clone of guitar hero, that also runs on Unity, and has a very "Just enough" port for Android, the only thing It really support IS enough touchscreen to allow you to map a guitar controller or a keyboard or a gamepad. You could potentially release something like that, that Just runs enough to give Android users this abslute gem of a game. Or better yet, recruit whoever made this port atempt into your ranks, pretty sure they would have a Lot to do with the official tools in hand.

**Comment by SDGNelson** [comment] 2024-04-16 19:12
If supporting mobile nowadays it would ideally be something I worked on officially. It wouldn't fit into my workload at the moment, however.

**Comment by Lion4K** [comment] 2024-04-17 20:23
Yeah I imagine it does. Idk how's the budget going, but if possible, you may wanna check the person who made the launcher I was referring to.
https://play.google.com/store/apps/details?id=com.SmartlyDressedGames.Unturned

Also, unrelated, but, I can't for the love of anything, find anything about the text formatting on server description and stuff.

I really wanted to make this:
![image-3.png](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/10391955/2bc82eb5-26fd-4738-b47c-d9b7b425e1a4)
That I saw in another server but I have no idea how nor where to find information.
I've asked on discord but no one there seems to know or wanna teach me, so might as well ask here.

**Comment by SDGNelson** [comment] 2024-04-18 16:55
Here's our documentation page for rich text which links to the relevant tags available: https://docs.smartlydressedgames.com/en/stable/data/rich-text.html

The link you shared says it doesn't exist, but it would be concerning if someone is using our company and game name directly. That said, I do know there have been a few community projects to play Unturned on mobile.

**Comment by Lion4K** [comment] 2024-04-19 04:10
> The link you shared says it doesn't exist

I've recorded [this video](https://photos.app.goo.gl/NAJG8zpehY7Gjk6L7) with what's on the store page. Has an email account if you wanna pursue it personally, also if you want the APK file I can upload it.

**Comment by Lion4K** [comment] 2024-04-19 04:12
>but it would be concerning if someone is using our company and game name directly. 

They must be eager to join the SDG Team

**Comment by Lion4K** [comment] 2024-04-19 04:16
> Here's our documentation page for rich text which links to the relevant tags available: https://docs.smartlydressedgames.com/en/stable/data/rich-text.html


I saw that before, but I don't really understand it, also, I don't see any examples on the links showing something that resembles the image I captured.
Also, how am I supposed to use it? I'm kinda lost

**Comment by SDGNelson** [comment] 2024-05-09 16:40
Hey sorry! This update today includes a couple minor adjustments including a fix to an exception in the log you had attached, so if we're lucky maybe you won't be running into it anymore. 🤞 

Sorry to say we don't have an official reference for rich text beyond Unity's docs, so it may be worth experimenting with the different tags. When clicking on the individual tags in their docs they also have examples of how to use each one.

**Closed** 2024-06-11 15:27 UTC
Labels: Revisit after next update
