### ISSUE TITLE
Revert patch.

### ISSUE THREAD

**Issue by Leandrozz** [SmartlyDressedGames/Unturned-3.x-Community#2178] opened 2020-12-05 19:55 UTC
I think we would all agree that the best idea and decision to take atm is to revert the friday patch to the last game version. The game is literally unplayable. AND not only that but everything that came with this patch has only difficulted the release and development of MANY servers that were going to be released after or during the update. 

The F6 editor does not work. AT ALL. The FPS are literally insanely low and lets not even talk about the UI and the new fonts.

Do something for the first time and rollback the patch, it wasnt a good idea, at all.

**Comment by jatapa** [comment] 2020-12-05 20:04
ok first thing first if there was a rollback (but there won't be) it would not be the first time also the bugs will get fixed and you will get used to the new UI after playing a while

**Comment by PandahutMiku** [comment] 2020-12-05 20:21
To expand a bit more, most of the issues are cosmetic or not game-breaking.

The interaction bug is already fixed, the only other "important" bug I know of right now is the issue with scrolling in storage, but that only happens on low resolutions and will probably be fixed today.

FPS has gone down for some people, particularly when opening menus, but I wouldn't call it "insanely low", and with time it's going to be patched as well. The whole reason this update happened was to move on from the old imgui system, not realistic to stay on it forever. 

Plugins/servers have already mostly updated for this update, and rolling back would just cause more confusion/issues for them. Just gotta relax a bit and let the bugs be fixed, or be helpful and report bugs with your client.log or replication steps.

(Also, f6 works fine on vanilla servers, I think the issue is something to do with modded servers, there's an[ issue open in this github for the f6 menu](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2152), but no one has provided a client.log of the issue occurring yet)

There was a public beta for this as well, too few people tried it out to find more of the rare bugs or minor cosmetic stuff, now just gotta wait for them to get ironed out.

**Comment by WCPistolPete** [comment] 2020-12-05 20:39
Too few people tried it out? I saw a laundry list of items before the patch was released. Most of the complaints were about the UI. Can't test multiplayer server FPS when there is no beta server.

**Comment by SDGNelson** [comment] 2020-12-17 23:38
Btw regarding WCPistolPete's comment, the "laundry list of items before the patch was released" had been fixed on the beta branch and discussed with the reporters before uGUI was released on the main branch. I fully expected it to be a smooth update

**Closed by SDGNelson** 2020-12-17 23:38 UTC
