### ISSUE TITLE
In-game chat messed up after recent update

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#213] opened 2018-02-16 18:31 UTC
![update](https://user-images.githubusercontent.com/14231707/36323091-67a45fbc-1358-11e8-8682-a46bb4e7e104.png)

**Comment by ghostpro228** [comment] 2018-02-16 18:58
my log
[Setting breakpad minidump AppID = 304930
Stacktrace:

  at (wrapper managed-to-native) object.__icall_wrapper_mono_object_isinst (object,intptr) <0x00004>
  at (wrapper managed-to-native) object.__icall_wrapper_mono_object_isinst (object,intptr) <0x00004>
  at (wrapper stelemref) object.stelemref (object,intptr,object) <0x0007d>
  at SDG.Unturned.ChatManager.askChat (Steamworks.CSteamID,byte,string) <0x006b1>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___CSteamID_sbyte_object (object,intptr,intptr,intptr) <0x00073>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (object,object[],System.Exception&) <0x00004>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (object,object[],System.Exception&) <0x00004>
  at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x0012a>
  at System.Reflection.MethodBase.Invoke (object,object[]) <0x00025>
  at SDG.Unturned.SteamChannel.receive (Steamworks.CSteamID,byte[],int,int) <0x00308>
  at SDG.Unturned.Provider.receiveServer (Steamworks.CSteamID,byte[],int,int,int) <0x00383>
  at SDG.Unturned.Provider.listenServer (int) <0x0007b>
  at SDG.Unturned.Provider.listen () <0x0004e>
  at SDG.Unturned.Provider.Update () <0x000d2>
  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) <0x00040>

Native stacktrace:

	/home/Unturned/Unturned_Headless_Data/Mono/x86/libmono.so(+0x89957) [0xf59e1957]
	[0xf77bf410]
	[0xf77bf430]
	/lib/i386-linux-gnu/libc.so.6(gsignal+0x47) [0xf74bc687]
	/lib/i386-linux-gnu/libc.so.6(abort+0x143) [0xf74bfab3]
	/home/Unturned/Unturned_Headless.x86() [0x85311b9]
	/home/Unturned/Unturned_Headless_Data/Mono/x86/libmono.so(+0xbb828) [0xf5a13828]
	/home/Unturned/Unturned_Headless_Data/Mono/x86/libmono.so(+0x21a92) [0xf5979a92]
	[0xf77bf410]
	/home/Unturned/Unturned_Headless_Data/Mono/x86/libmono.so(+0x7f223) [0xf59d7223]
	/home/Unturned/Unturned_Headless_Data/Mono/x86/libmono.so(+0xc6acd) [0xf5a1eacd]
	/home/Unturned/Unturned_Headless_Data/Mono/x86/libmono.so(mono_class_init+0x1cd) [0xf5a25886]
	/home/Unturned/Unturned_Headless_Data/Mono/x86/libmono.so(mono_class_is_assignable_from+0x3b) [0xf5a27d3c]
	/home/Unturned/Unturned_Headless_Data/Mono/x86/libmono.so(mono_object_isinst+0x5d) [0xf5a85214]
	[0xf3266f1b]
	[0xf56c02fe]
	[0xdfc51692]
	[0xdfc6cefc]
	/home/Unturned/Unturned_Headless_Data/Mono/x86/libmono.so(+0x25a5b) [0xf597da5b]
	/home/Unturned/Unturned_Headless_Data/Mono/x86/libmono.so(mono_runtime_invoke+0x66) [0xf5a7eddd]
	/home/Unturned/Unturned_Headless_Data/Mono/x86/libmono.so(mono_runtime_invoke_array+0x53a) [0xf5a8384e]
	/home/Unturned/Unturned_Headless_Data/Mono/x86/libmono.so(+0xebe08) [0xf5a43e08]
	[0xf286a863]
	[0xf286a67b]
	[0xf286a546]
	[0xdfc6c5b9]
	[0xdfc97e34]
	[0xdfc0b8c4]
	[0xdfbb8a47]
	[0xf1468dfb]
	[0xf56c6eb9]
	/home/Unturned/Unturned_Headless_Data/Mono/x86/libmono.so(+0x25a5b) [0xf597da5b]
	/home/Unturned/Unturned_Headless_Data/Mono/x86/libmono.so(mono_runtime_invoke+0x66) [0xf5a7eddd]
	/home/Unturned/Unturned_Headless.x86() [0x85440ed]
	/home/Unturned/Unturned_Headless.x86() [0x852d9c0]
	/home/Unturned/Unturned_Headless.x86() [0x81d00e2]
	/home/Unturned/Unturned_Headless.x86() [0x83cae10]
	/home/Unturned/Unturned_Headless.x86() [0x83b31c2]
	/home/Unturned/Unturned_Headless.x86() [0x806c292]
	/lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0xf74a7af3]
	/home/Unturned/Unturned_Headless.x86() [0x80710e9]

Debug info from gdb:


=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================](url)

**Comment by Trojaner25** [comment] 2018-02-16 19:12
This is an issue caused by my ChatMaster plugin, apparently Nelson did some changes to the SteamCall to add support for the formatting tags (so the Unturned update broke the plugin).

I will update the plugin.
Please close the issue as this is related to a plugin, not Unturned.

**Comment by ghostpro228** [comment] 2018-02-16 19:13
I do not use this ChatMaster

**Comment by baranmod** [comment] 2018-02-16 19:14
Its not. well maybe it is, but then its related to all plugins as I am not using chatmaster plugin

**Comment by Trojaner25** [comment] 2018-02-16 19:14
I have to correct myself.
ChatMaster and *other* plugins, which also alter chat, cause this.

**Comment by Trojaner25** [comment] 2018-02-16 19:14
Maybe its even RocketMod itself.

**Comment by Trojaner25** [comment] 2018-02-16 19:16
Edit: confirmed.
All plugins which alter chat in a specific way need to be updated.
Also Rocket itself has to be updated.

Please transfer this issue to RocketMod

**Comment by Trojaner25** [comment] 2018-02-16 19:18
@SDGNelson can you keep the old SteamCall for a while and just make it as wrapper to the new one?

**Comment by Trojaner25** [comment] 2018-02-16 20:48
[Rocket_Fix.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/1732773/Rocket_Fix.zip)

As the official Rocket build is broken, I will publish the fixed version here.
Based on commit: https://github.com/RocketMod/Rocket.Unturned/commit/5f6671cb1dfbf5f29007caec49dac0efa7f07a61

Reminder, if you use chat altering / modifying plugins (eg ChatMaster, ChatControl etc), you will have to update them too.

**Comment by Trojaner25** [comment] 2018-02-17 11:59
The official RocketMod build now includes the fix.

https://rocketmod.net/downloads

**Closed** 2018-02-17 12:53 UTC
