### ISSUE TITLE
the third person mode is broken

### ISSUE THREAD

**Issue by Happy12222** [SmartlyDressedGames/Unturned-3.x-Community#4010] opened 2023-07-17 19:55 UTC
In this video I show the problem
https://youtu.be/EyGeXCTUktk

**Comment by ItsRodrigoAl** [comment] 2023-07-18 11:27
Already report it but with a bigger list about those issues: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3677

Sadly seems like this won't be fixed :/

**Comment by SDGNelson** [comment] 2023-07-20 16:10
To clarify: this is actually not a bug. The third-person aiming different is because it shoots towards your where your 2D crosshair intersects the world, otherwise it would be impossible to shoot in third-person. (all third-person games do this)

**Closed by SDGNelson** 2023-07-20 16:10 UTC
