### ISSUE TITLE
model of the Tire item should probably be updated to match the new wheels

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#4567] opened 2024-07-04 05:50 UTC
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/8be09f35-95d3-48d6-ac8b-9077a9e3875e)
wouldnt call this a *bug* exactly, but would probably help to have the item match the new wheel model. but im not too sure on this one. leaving here incase it went unnoticed.

**Comment by MoltonMontro** [comment] 2024-07-04 06:34
Duplicate of https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/4545

**Comment by diddlyono** [comment] 2024-07-04 08:39
oh didnt see that my fault

**Comment by SDGNelson** [comment] 2024-07-04 15:16
No worries, thanks Molt and Diddlyono!

**Closed by SDGNelson** 2024-07-04 15:16 UTC
