### ISSUE TITLE
Cant scroll over item slots

### ISSUE THREAD

**Issue by Tairiku-Ookami** [SmartlyDressedGames/Unturned-3.x-Community#2215] opened 2020-12-12 12:29 UTC
You literally can't scroll the inventory when your mouse is over an item slot. This almost makes the game unplayable. This needs to be fixed ASAP.

**Comment by SDGNelson** [comment] 2020-12-12 22:11
Duplicate of https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2211#issuecomment-743361330

**Closed by SDGNelson** 2020-12-12 22:11 UTC
