### ISSUE TITLE
[Servers] FPS lag spikes

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1770] opened 2020-05-29 07:59 UTC
FPS lagging to everyone when some parts of map loads, it's something of structures, but i did a recent wipe...

![image](https://user-images.githubusercontent.com/13141042/83236015-1bfc3780-a193-11ea-973f-046dce2f3d5d.png)
![image](https://user-images.githubusercontent.com/13141042/83236123-4d750300-a193-11ea-9698-011633126742.png)

[![](http://img.youtube.com/vi/jA7eCRuTI2E/0.jpg)](http://www.youtube.com/watch?v=jA7eCRuTI2E"")

**Comment by SDGNelson** [comment] 2020-12-31 20:43
Closing because this is a duplicate of the older issue, it will be the main goal in 2021. More details here: https://blog.smartlydressedgames.com/unturned-in-2021/

**Closed by SDGNelson** 2020-12-31 20:43 UTC
