### ISSUE TITLE
UI effects not clearing anymore with tellEffectClearByID

### ISSUE THREAD

**Issue by Ankumo** [SmartlyDressedGames/Unturned-3.x-Community#2097] opened 2020-11-20 20:04 UTC
Am I missing something? It was working just fine before the updates. Shall we use tellUIEffectVisibility only now or it's just a bug?

**Comment by muertoof** [comment] 2020-11-20 20:06
I guess this is some а bug

**Comment by PandahutMiku** [comment] 2020-11-20 20:09
Was talked about a bit in #2095. The issue that was made for is fixed now though, although this one still remains.

**Comment by Ankumo** [comment] 2020-11-20 20:16
Yep, if you spawn UI effect with methods like tellEffectPoint it's clearing successfully with tellEffectClearByID, but now with tellUIEffect ones

**Comment by SDGNelson** [comment] 2020-11-20 20:16
So the problem is that UI effects were accidentally never being pooled due to some stupid naming that is now fixed. At this point there are certainly UIs that depend on the current behavior, so for a patch this afternoon there will be tracking specifically for UI gameobjects so these cleanup methods work again.

**Comment by SDGNelson** [comment] 2020-11-20 21:21
Should be fixed in the 3.20.15.2 patch which is on the preview branch now. Hopefully that is the last of the issues. I will wait just a little bit longer in case anything else comes up.

**Comment by baranmod** [comment] 2020-11-20 21:35
public test branch?

**Comment by SDGNelson** [comment] 2020-11-20 21:46
Yep

**Comment by baranmod** [comment] 2020-11-20 21:56
can confirm that UI works good now :)

**Comment by kotyk7** [comment] 2020-11-20 22:06
I can confirm that too, is there an ETA for pushing that fix into the main branch?

**Comment by SDGNelson** [comment] 2020-11-20 22:15
Glad to hear that it's working again. It should be on the default branch about ~15 min ago

**Comment by kotyk7** [comment] 2020-11-20 22:17
Thank you for the fix, updating my server now.

**Comment by kotyk7** [comment] 2020-11-20 22:54
Everything works for me as it worked before this update that came out today, that broke the UI.
Thanks for fixing the game Nelson, and the FPS everywhere. I've got a 40% FPS boost on a not optimized, modded with like 30 mods of assets map. <3

**Closed** 2020-12-17 23:55 UTC
