### ISSUE TITLE
Player.look.areSpecStatsVisible does not working correctly

### ISSUE THREAD

**Issue by Tortellio** [SmartlyDressedGames/Unturned-3.x-Community#1488] opened 2020-02-29 22:58 UTC
When i press Left Shift + F7 as Admin, it always return false, never return true

**Comment by erik7302** [comment] 2020-02-29 23:18
its a clientside variable and its not relayed to the server(for now)

**Comment by rube200** [comment] 2020-03-01 01:20
Duplicate of #1487

**Closed** 2020-12-31 19:58 UTC
