### ISSUE TITLE
Can you add a new function for plugins? 

### ISSUE THREAD

**Issue by HellGodness** [SmartlyDressedGames/Unturned-3.x-Community#902] opened 2019-07-04 15:32 UTC
Hi! Can you add a function that allows track absolutely any input key, like UnityEngine.Input.GetKeyDown(Key).

**Comment by Trojaner** [comment] 2019-07-04 17:11
Duplicate of https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/395

**Comment by SDGNelson** [comment] 2019-07-07 14:45
The plugin hotkeys were added as a compromise on this sort of request: they can be re-bound by the player, and shown in the UIs and chat. Sending the full keyboard state would be a security concern especially in the eyes of players.

**Closed by SDGNelson** 2019-07-07 14:45 UTC
