### ISSUE TITLE
v3.29.1.0 Update broke Russia map on Linux servers (Again)

### ISSUE THREAD

**Issue by gegtor** [SmartlyDressedGames/Unturned-3.x-Community#611] opened 2019-02-22 20:32 UTC
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/538

v3.29.1.0 Update causes the same old Stacktrace error with Russia map

Full stacktrace: https://pastebin.com/nNHry1ks

**Comment by SDGNelson** [comment] 2019-02-24 21:58
This crash appears to be caused by setting the terrain SplatPrototypes on the dedicated server, whereas previously it was caused by setting Alphamaps. Interestingly the splat prototypes are set before the alphamaps, so I'm not sure why we wouldn't have had this problem before.

Right now the game sets some placeholder empty Texture2D.blackTexture splat prototypes, so I'll double-check that nothing else depends on those and disable them on the dedicated server.

**Comment by SDGNelson** [comment] 2019-02-24 22:29
Patch will most likely be later today

**Comment by gegtor** [comment] 2019-02-24 22:30
Awesome! Thanks

**Comment by gegtor** [comment] 2019-02-25 07:44
@SDGNelson I still get SIGABRT in V3.29.2.0

https://pastebin.com/U7vNj6g1

**Comment by SDGNelson** [comment] 2019-02-25 08:17
Seems to have been a few posts about linux mono native crashes lately, I'll re-open and link

**Comment by SDGNelson** [comment] 2019-02-25 08:20
#612

**Comment by gegtor** [comment] 2019-02-25 13:57
v3.39.2.1 Update didn't fix it (Duno if it had to)

But still here is 3.39.2.1 stacktrace if it useful to you https://pastebin.com/n50jndZ3

**Comment by aman7** [comment] 2019-02-25 20:17
it did fix some issue but didnt fixed it fully, servers are still getting frozen, and also the same errors as above.

**Comment by D-AIRY** [comment] 2019-02-27 04:34
The same problem. Sometimes it gives additional info about out-of-memory (having about 30gb ram free), attached below:
[oom.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2908597/oom.txt)

**Comment by SDGNelson** [comment] 2019-02-28 23:06
Preview branch now has the .2 patch which reverts to the previous version of .NET/mono. If you could opt-into it to verify that it's working again for you that would be super helpful, you can specify the branch on the SteamCMD command-line with the "-beta" flag e.g. "-beta preview" 🤞

**Comment by gegtor** [comment] 2019-02-28 23:25
@SDGNelson 
🎉🎉🎉**v3.29.2.2**🎉🎉🎉
🎉🎉🎉 **Russia fires up** 🎉🎉🎉

Tested Washington / Russia on 3 different servers

Server starts correctly and players can join

Not sure about stability because I had only 20 min to test it but I'm quite confident that everything is okay now

Roll out the update 😁

**Comment by Trojaner** [comment] 2019-02-28 23:35
Please do not roll out the update.
This would be disastrous for us plugin developers. A lot of work done recently would just vanish into nothing.

**Comment by MeedicBear** [comment] 2019-02-28 23:42
Please don't roll back

**Comment by rube200** [comment] 2019-02-28 23:44
I'm from Saturday to sleep about 5h a day to make a plugin from scratch, because of the last update and to optimize it, I'm at the end where I only need to correct the small details, in case you reverse the update, I'm going to lose one week. In addition to the other developers who will also lose their work.

**Comment by aviadmini** [comment] 2019-02-28 23:53
Instead of figuring out what actually happens
Instead of checking whether that happens to vanilla game/modded
Despite saying that linux is second class citizen
Instead of looking into why everyone is meddling with 32-bit on linux
etc etc etc

Oh well, please roll back to Early Access as well then, as it would represent state of it the best

**Comment by PandahutMiku** [comment] 2019-03-01 00:06
Please do not roll back and try looking into other ways to fix this issue. As Trojaner has said, a lot of work has already been done to support .NET 4.6.1. Around this time of the year Unturned already slows down as well (Shown by last 30 days on this chart https://steamcharts.com/app/304930) and we really don't need more downtime that would most likely further hurt the player count. Surely we could look for a better solution which would fix the root cause of this instead of just reverting back

**Comment by SYlucas** [comment] 2019-03-01 00:10
GH

**Comment by Gsechs** [comment] 2019-03-01 00:16
I agree with the previous comment. 

I also noticed that this is a rough time for Unturned's concurrent player count.  I think there are definitely other solutions such as using Unity 2018.  Not to mention that this would likely cause quite a lot of disturbance for a lot of plugin developers. 
😎

**Comment by thereis** [comment] 2019-03-01 00:24
Please, do not roll back! The newest update let us developers to bring alot of features and customizations with the newest .net version.

Also, enable to display the servers with more than 24 people for everyone ;)

**Comment by SDGNelson** [comment] 2019-03-01 01:47
Well, the issue is without a doubt the newer .NET/mono (crashes on linux) vs the old one (fine on all platforms). It's "experimental" in Unity 2017.4, so it's not like they'll say "oh ok, we'll put the stable 2019.x version into the next 2017 LTS release". I'm very sorry for any lost progress if we do have to roll back, but 2018.4 is not an option either. Trying out the experimental version was purely by plugin developers request, but the needs of the player base as a whole outweigh that.

For the moment I've reached out to a few of the server networks asking if they use the Linux server, and if so if it's been stable for them. If they're all using the stable Windows server, or the Linux server has been working fine, then maybe it is okay to keep this version for those brave enough to use the Linux server?

**Comment by Trojaner** [comment] 2019-03-01 02:00
> (...) but 2018.4 is not an option either.
Is there any specific reason for this? E.g. assetbundles not compatible again? If its just because you don't want to go through update hell again, I understand that.

There are 3 options which I can see:

**Letting Unity fix it.**
- Since you are using an LTS release which still gets updates (I believe until 2019 Q4), I see Unity responsible to fix this issue. 

**Enforcing *Wine* / Steam Play on Linux and dropping native Linux builds completely.**#
- Some games are known to run better on Wine or Steam Play than their native ports. I will check this option out and test stuff when I find some time.

**Revert back to .NET 3.5**
- ...and making all developers cry

**Comment by joemisfit** [comment] 2019-03-01 04:18
Hello @SDGNelson ,

I understand that Linux has issues with the new .net update and the majority of us would rather you find a fix to get Linux working with the newest updates rather than reverting what all we've done thus far in progress within the community. A lot of developers and essentially programmers have spent time updating plugins, workshops, discord bots, the connections for them, and many other aspects of their servers to comply and work properly with what was needed to be fixed, even though some if not most of them are rollback compatible, it just would be sad to see what all we've been through in upgrading to have reverted back in feature progress over such a small bug that can be fixed with help of several developers teaming up with yourself to brainstorm on the issues at hand to solve essentially the causes as to why Unturned is broken with the newest .net updates.

I hope you'd take into consideration what all we've spoken here within the thread before pursuing an actual rollback as it would essentially cause most of us to have to change several aspects of our servers with downtime while several modifications will need to take place, which overall affects most communities on all spectrums.

Thank you.

**Comment by JustOneMoreBlock** [comment] 2019-03-01 06:39
THIS IS NOT A FIX

So, I've been in Linux all day reading a bunch of strace's, and few things keep popping out at me.

```
open("/usr/lib/mono/gac/policy.2.0.System/0.0.0.0__b77a5c561934e089/policy.2.0.System.dll", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/home/Games/unturned/System.dll", 0x7ffe18f7e2d0) = -1 ENOENT (No such file or directory)
stat("/home/Games/unturned/System.exe", 0x7ffe18f7e2d0) = -1 ENOENT (No such file or directory)
stat("/home/Games/unturned/System/System.dll", 0x7ffe18f7e2d0) = -1 ENOENT (No such file or directory)
stat("/home/Games/unturned/System/System.exe", 0x7ffe18f7e2d0) = -1 ENOENT (No such file or directory)
open("/usr/lib/mono/gac/System/2.0.0.0__b77a5c561934e089/System.dll", O_RDONLY) = 3
```

None of these exist, and should be using System.dll from the Managed/ folder anyway. Anyway, I attempted to symlink `System.dll` and even the entire folder from `Managed` and provided the following error.

```
Can't find custom attr constructor image: /home/Games/unturned/System.dll mtoken: 0x0a000001

Unhandled Exception:
System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  at Rocket.Unturned.Launcher.RocketLauncher.Main (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  at Rocket.Unturned.Launcher.RocketLauncher.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

Since I'm running on CentOS 7 x64, and running `Mono JIT compiler version 3.12.1` I figured I'll do a search of `System.dll` on the system.

```
[root@pvp unturned]# locate System.dll
/home/Games/unturned/Unturned_Data/Managed/System.dll
/home/Games/unturned/Unturned_Headless_Data/Managed/System.dll
/usr/lib/mono/2.0/System.dll
/usr/lib/mono/4.0/System.dll
/usr/lib/mono/4.5/System.IO.Compression.FileSystem.dll
/usr/lib/mono/4.5/System.dll
/usr/lib/mono/gac/System/2.0.0.0__b77a5c561934e089/System.dll
/usr/lib/mono/gac/System/2.0.0.0__b77a5c561934e089/System.dll.mdb
/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll.mdb
/usr/lib/mono/gac/System.IO.Compression.FileSystem/4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
/usr/lib/mono/gac/System.IO.Compression.FileSystem/4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll.mdb
```

```
cd /home/Games/unturned/
ln -s /usr/lib/mono/2.0/System.dll .
```
Well, it didn't crash, responded to saving the world, and responded in the client. Wasn't able to join. :(

This provides SO MANY ERRORS. But, it doesn't crash.

Current Error:
```
DivideByZeroException: Attempted to divide by zero. - SDG.Unturned.LightingManager.updateLighting () (at <b6f53656616b4fdd9d9d28953c558538>:0)
SDG.Unturned.LightingManager.onLevelLoaded (System.Int32 level) (at <b6f53656616b4fdd9d9d28953c558538>:0)
SDG.Unturned.Level+<init>c__Iterator0.MoveNext () (at <b6f53656616b4fdd9d9d28953c558538>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <102dc60ee5974486865758606d7385d4>:0)
```

Normally I'd assume this is from the Lightining.dat file. Tried removing it, and didn't work. :(


[morelogs.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2918176/morelogs.log)
[strace_1.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2918177/strace_1.log)
[strace_2.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2918178/strace_2.log)
[strace_3.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2918179/strace_3.log)

¯\_(ツ)_/¯

**Comment by SDGNelson** [comment] 2019-03-01 08:31
Released .2 which fixes a few misc issues, but keeping the .NET upgrade 👍

**Comment by Bradler26** [comment] 2019-03-01 09:45
Thanks for keeping the current version of .net but please if possible don't change it. As many plugin devs mentioned they have worked endlessly to get their plugins migrated over. Some have even began work on new plugins that utilizes the features of the new .net

I personally have been very happy with your latest work and sure, there have been bugs and hardships but overall it will boost the game in the long term. Any extra changes will affect the already low playerbase (due to the time of year plus recent updates causing server downtime)

Doing another update will ruin all servers for another few days. 90% of the playerbase plays multiplayer and if servers go down the playerbase goes down as well...

**Comment by Trojaner** [comment] 2019-03-01 13:44
https://github.com/Trojaner/unturned-wine

I have managed to run Unturned Windows Build on Linux using Wine.

However there is a bug that prevents it from working correctly:

```
EntryPointNotFoundException: AllocConsole
  at (wrapper managed-to-native) SDG.Unturned.ConsoleOutput:AllocConsole ()
  at SDG.Unturned.ConsoleOutput..ctor () [0x00006] in <491015b431a743d9bf5a9bd7f52497bb>:0
  at SDG.Unturned.CommandWindow..ctor () [0x00037] in <fa52c3fc37c54e189f49994f187e446b>:0
  at SDG.Unturned.Dedicator.awake () [0x0003f] in <fa52c3fc37c54e189f49994f187e446b>:0
  at SDG.Unturned.Setup.Awake () [0x00011] in <fa52c3fc37c54e189f49994f187e446b>:0

ArgumentNullException: Value cannot be null.
Parameter name: type
  at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00003] in <cfc149f8218b496788d84$  at System.Activator.CreateInstance (System.Type type, System.Object[] args) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0
  at SDG.Unturned.Assets.loadFile (SDG.Unturned.Assets+ScannedFileInfo file) [0x000cc] in <fa52c3fc37c54e189f49994f187e446b>:0
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
SDG.Unturned.Assets:loadFile(ScannedFileInfo)
SDG.Unturned.<loadAllFilesScanned>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Failed to find reader for: System.Guid
Failed to find reader for: System.Type

DirectoryNotFoundException: Could not find a part of the path 'C:\users\root\DedicatedServer\Servers\server\Bundles'.
  at System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) [0x000f7] in <cfc149f8218b496788d8493c87de777a>:0
  at System.IO.FileSystemEnumerableIterator`1[TSource].HandleError (System.Int32 hr, System.String path) [0x00006] in <cfc149f8218b496788d8493c87de777a>:0
  at System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () [0x00054] in <cfc149f8218b496788d8493c87de777a>:0
  at System.IO.FileSystemEnumerableIterator`1[TSource]..ctor (System.String path, System.String originalUserPath, System.String searchPattern, System.IO.SearchOption searchOption, System.IO.SearchResultHandler`1[TSource] resultHandler, System.Boolean checkHost) [0x000d6$  at System.IO.FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) [0$  at System.IO.Directory.InternalGetFileDirectoryNames (System.String path, System.String userPathOriginal, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) [0x00000] in $  at System.IO.Directory.InternalGetFiles (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0
  at System.IO.Directory.GetFiles (System.String path, System.String searchPattern) [0x0001c] in <cfc149f8218b496788d8493c87de777a>:0
  at SDG.Unturned.Assets.scanFolder (System.String path, System.Boolean usePath, System.Boolean loadFromResources, System.Boolean canUse, SDG.Unturned.AssetDirectory directory, SDG.Unturned.EAssetOrigin origin, System.Boolean overrideExistingIDs, SDG.Unturned.MasterBund$  at SDG.Unturned.Assets+<dedicatedServerUgcLoadingStep>c__Iterator2.MoveNext () [0x0026d] in <fa52c3fc37c54e189f49994f187e446b>:0
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00027] in <dec06e59a8644684a220ee8e93af2a2a>:0
```

**Comment by gegtor** [comment] 2019-03-01 13:54
I'm very sceptical about using Wine

I'm running my server network for about 7 months now and unturned native server worked really well with rocket and everything else it's also quite efficient and runs Russia at 50 TPS on 1 core 2GB ram

Introducing Wine would mean more complexity and lower performance (And is just another workaround, not a fix)

The ideal solution is to work hard on Linux version and resolve many issues that pilled up over the years (get 64bit build working, resolve steam api error, etc)

**Comment by Trojaner** [comment] 2019-03-01 13:56
> Introducing Wine would mean more complexity and lower performance (And is just another workaround, not a fix)

I already made some scripts, its basically 2 commands to install and set it up. Also people hosting on Linux should know how to use such scripts.

Regarding performance, as said earlier, some games even have better performance on Wine than their native ports.

**Comment by gegtor** [comment] 2019-03-01 14:04
What I mean is not that it would be harder to manage such server 

It's just every time something brakes on Linux we find (i'm sorry) a shitty workaround

**Comment by Trojaner** [comment] 2019-03-01 14:06
> It's just every time something brakes on Linux we find (i'm sorry) a shitty workaround

Thats exactly why Wine is the solution. No more Linux breaking, no more Linux workarounds. Why? Because it will exactly the same as on Windows.

**Comment by Johnanater** [comment] 2019-03-02 01:54
If you do plan on removing native Linux support, be sure BattlEye works with it on the client. 😉

**Comment by Edbtvplays** [comment] 2019-03-02 15:12
For Unturned, Linux has always been unstable with these type of issues arising regularly. The community have found there own workarounds for different Mono and other glitches trying to make it stable enough for servers to run with little help from Nelson in most cases. These work arounds are far from ideal and often break when unturned is updated. It makes unturned hosting on Linux even more complicated than it should be forcing people to host there servers on windows machines. However, Windows is expensive ( a whole seperate license for a VPS or Dedicated machine people want to host on) , Uses a lot of resources and in general is not ideal for most unturned server hosters Especially like me who hosts a large volume of unturned or other game servers on one node. Linux is Free , Uses little to no server resources meaning you can have more servers on a single node unlike windows. 

What I am saying in essence is that Unturned has gotten little to no support for Linux especially serverside.I personally and many others want this to change. Most other games such as Gmod, Rust, CS:GO , Ark and many many more server software run perfectly stabily on Both Linux and Windows. So why can’t unturned. 

Wine is not a solution it is simply a work around. We want something more permement. None of the games I mentioned above don’t need wine to run there server software. So why should Unturned? Rust is made in Unity. We want a solution from you Nelson the developer of this game we all love to play and develop on and not from the  community who are simply finding temporarily work arounds to your mishaps (i do appreciate the community’s fix arounds, I wouldn’t be able to host servers without you guys) 

Please consider addressing this before Unturned 3.0 reaches A time when it won’t be updated anymore as 4.0 will take priority. I also do hope that unturned 4.0 will have better Linux support in general with it being as supported as windows. 

Thanks, 
Edbtvplays

**Comment by gegtor** [comment] 2019-03-02 15:35
This is exactly what I was saying ^ 

+1 rep

**Comment by educatalan02** [comment] 2019-03-03 12:01
@Edbtvplays  I already got Unturned Servers running with Ubuntu 16.04.
**That's my Steps:**
[Unturned Server Linux 16.04 Steps.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2923070/Unturned.Server.Linux.16.04.Steps.txt)

**Comment by Johnanater** [comment] 2019-03-03 19:23
Also, can confirm it works on Ubuntu 18.04.2 LTS. Just install mono-runtime instead of mono-devel.

**Comment by CozmicHosting** [comment] 2019-03-03 20:40
@educatalan02 Just tried that with my 16.04 Ubuntu machine and it didn't work same error i have been getting.We are also trying to use the pterodactyl panel.We are using a panel for our Unturned clients.

**Comment by Edbtvplays** [comment] 2019-03-03 21:56
> @educatalan02 Just tried that with my 16.04 Ubuntu machine and it didn't work same error i have been getting.We are also trying to use the pterodactyl panel.We are using a panel for our Unturned clients.

Peterodactyl has nothing to do with the error. If anyone is curious Peterodactyl Panel Runs using docker and we get the same errors as outside of docker so the panel has nothing to do with this bug.

**Comment by CozmicHosting** [comment] 2019-03-03 22:00
Yes I know that I was just saying what I was using,for a panel and I get
the same error either way I try to do it.

**Comment by strongunturned** [comment] 2019-03-04 05:52
Will there be a fix for this problem, or will we go to windows?

**Comment by Trojaner** [comment] 2019-03-04 10:09
There are distributions and set ups which are working. Just some bigger maps do not work (e.g. Russia).
You should experiment a bit.

**Comment by joemisfit** [comment] 2019-03-04 11:30
Windows for server solutions is indeed pricey that I'll admit however there are plenty of work arounds, If you are tech savvy. As for Linux I don't recall Nelson ever offering much support towards it because not too many individuals use it as intended, nor do many folks use Linux as a standalone or vm o.s.

**Comment by Edbtvplays** [comment] 2019-03-04 14:07
> There are distributions and set ups which are working. Just some bigger maps do not work (e.g. Russia).
> You should experiment a bit.

But Russia is one of the main maps in unturned and is officially supported by nelson and unturned so it needs to be fixed. i know there are others that work but big maps such as russis don't

**Comment by Edbtvplays** [comment] 2019-03-04 14:11
> Windows for server solutions is indeed pricey that I'll admit however there are plenty of work arounds, If you are tech savvy. As for Linux I don't recall Nelson ever offering much support towards it because not too many individuals use it as intended, nor do many folks use Linux as a standalone or vm o.s.

Linux is very popular in VMS and as standalone on dedicated servers for hosting solutions alot of people use it as there PC operating system it is way more popular than windows is? and nelson should support linux for the reasons I listed above. and yes there are workarounds but they dont always work and always break. Nelson needs to address linux as its his game and not the community.

**Comment by gegtor** [comment] 2019-03-04 14:16
My whole server network is based on Russia map getting 24/24 constantly 

Also
**OVH Linux VPS: 3.56$
OVH basic Windows VPS: 15.57$**

**Comment by CozmicHosting** [comment] 2019-03-04 14:19
I think linux should get more support as well as its alot easier for people
to host it with linux instead of paying for a windows machine or having to
buy a licence.

**Comment by aman7** [comment] 2019-03-04 17:10
yes please tell use when you going to fix this issue, its really hard checking all server if they are up or frozen. and please also decide if you going to support linux or not, because it is start of the month, i got invoices and will decide to continue with or not.

**Comment by Trojaner** [comment] 2019-03-04 17:39
At this moment it is the plugin developers lobby against the server owners/hosters lobby. Both have good arguments on their respective side.

To be honest, I would not want to be in Nelsons place right now. Regardless of the choice he makes, someone will be upset and angry.

**Comment by CozmicHosting** [comment] 2019-03-04 17:47
Yeah but if you think about it if theres no servers to play on where will
the servers come from some of the popular networks are having to pay more
since windows machines cost more than linux.

**Comment by gegtor** [comment] 2019-03-04 17:50
Is there really no way to fix Russia on new **Mono / .NET** ?

Or is this issue purely Unity fault and has to be resolved with them

**Comment by CozmicHosting** [comment] 2019-03-04 17:55
I cant get any unturned server to work on my linux machine just crashes.

**Comment by Edbtvplays** [comment] 2019-03-04 17:57
> At the moment this is all about the plugin developers lobby against the server owners/hosters lobby. Both have good arguments on their respective side.
> 
> To be honest, I would not want to be in Nelsons place right now. Regardless of the choice he makes, someone will be upset and angry.

Well i think Nelson could fix the issue for all by not downgrading the Mono and instead searching for the root cause of the issue and bringing it up with Mono or unity and he could also make linux more stable and better supported for all. If its a Mono issue bring it up with Mono

**Comment by Trojaner** [comment] 2019-03-04 17:58
> Is there really no way to fix Russia on new Mono / .NET ?
There are ways, but question is if they are feasible. For example, upgrading Unity again might fix it, but is not feasible.

At the moment I can not think of anything but "Linux vs new .NET".

>Well i think Nelson could fix the issue for all by not downgrading the Mono and instead searching for the root cause of the issue and bringing it up with Mono or unity and he could also make linux more stable and better supported for all. If its a Mono issue bring it up with Mono

Problem is that the "root cause" is in Unity code, not in Unturned code. Nelson himself can not fix this, at he could find some workaround at max.

**Comment by Edbtvplays** [comment] 2019-03-04 17:59
so even if he brought it up with unity they could not fix as the unity version could not be updated?

**Comment by gegtor** [comment] 2019-03-04 18:00
@CozmicHosting Current state looks something like this

**Washington** etc Works but crashes every few hours
**Russia France** etc Crashes on server start

If you can't start Washington and join issue lies in your server config or packages and even fixed unturned won't work

**Comment by SDGNelson** [comment] 2019-03-04 18:04
Yeah this is stressful :(
One option I'm looking into is having an old-mono version for Linux, I wonder are you already downloading a specific Linux depot i.e. the Unturned_Headless Linux32 depot?

**Comment by gegtor** [comment] 2019-03-04 18:09
@SDGNelson Currently, our update scripts use 304930 app_id

In this case 304937 right?

**Comment by strongunturned** [comment] 2019-03-04 18:23
@SDGNelson Yes, we did this, also tried to increase and decrease the version of mono, the error remained

**Comment by Trojaner** [comment] 2019-03-04 18:28
@strongunturned Unity uses its own mono implementation. This is not bound to the mono you install on your Linux system. Only Nelson can set the mono version of Unturned.

**Comment by strongunturned** [comment] 2019-03-04 18:31
@Trojaner Thanks I'll know. My whole flood is connected with the fact that we do not know what to do, wait for a fix or switch to windows. 

I wish Nelson patience and success in correction. I apologize for my flood

**Comment by SDGNelson** [comment] 2019-03-05 04:22
3.29.2.4 patch is using the previous mono version for the Headless server! (among other fixes)
If need be we can also have previous mono versions for the non-headless and 64-bit versions.

**Comment by gegtor** [comment] 2019-03-05 06:49
🎉 It's working 🎉

Thanks for everything

**Comment by justosius** [comment] 2019-03-05 08:43
Lets hope 4.0 will support only single os. Less is more.

**Comment by Edbtvplays** [comment] 2019-03-05 08:46
> Lets hope 4.0 will support only single os. Less is more.

why would you want that. that is the worst idea. All shoukd be supported Windows Mac and linux so everyone can enjoy unturned ad the server managaing side of it.

**Comment by Trojaner** [comment] 2019-03-05 18:06
@SDGNelson Is it possible to provide 2 builds of the headless server, one with .NET 4.6.1 and one with .NET 3.5? Maybe using the brach feature or using different app ids?

**Comment by Edbtvplays** [comment] 2019-03-05 19:57
> 3.29.2.4 patch is using the previous mono version for the Headless server! (among other fixes)
> If need be we can also have previous mono versions for the non-headless and 64-bit versions.

Now plugins which have already been updated won't be supported on linux and this is a majority of plugins  essentially not fixing the issue. as most servers use plugins and rocketmod. The issue is the same as before but servers can now be started.

**Comment by SDGNelson** [comment] 2019-03-13 06:48
In 3.29.3.0 the headless linux server mono version is optional now

**Comment by Kenzim** [comment] 2019-03-17 19:04
Yo Nelson, 
Using ubuntu 18.04 host os
ubuntu 16.04 docker images
installed lldb and gdb to get rid of initial errors with new depot (304937)
now getting ```Debug info from gdb:
Could not attach to process. If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user. For more details, see /etc/sysctl.d/10-ptrace.conf
/tmp/mono-gdb-commands.QNaKzm:1: Error in sourced command file:```
Changed the config to 0, so that it should be able to bind processes, still cant. 
Any ideas?

**Comment by Kenzim** [comment] 2019-03-17 19:05
full trace : https://ptero.co/catulobami.sql

**Closed** 2019-03-25 13:39 UTC
