### ISSUE TITLE
Broken legs when teleporting

### ISSUE THREAD

**Issue by PARTOVIY** [SmartlyDressedGames/Unturned-3.x-Community#2890] opened 2021-11-19 18:49 UTC
When teleporting, there is a chance of breaking the legs and returning back to the old position.

**Comment by SDGNelson** [comment] 2021-11-19 18:57
Which teleport are you using? This is odd because if you return to the old position that would suggest the server did not actually teleport, but on the other hand it is odd because if the server did not move then the legs would not have broken.

**Comment by PARTOVIY** [comment] 2021-11-19 19:36
Here are videos showing the error

https://www.youtube.com/watch?v=-yzuo-hag3I&feature=youtu.be

**Comment by SDGNelson** [comment] 2021-11-19 19:44
Thanks for the video. Does it happen if you use the /teleport command instead of /tp?

**Comment by PARTOVIY** [comment] 2021-11-19 19:56
It still returns, but much less.

**Comment by SDGNelson** [comment] 2021-11-19 20:10
Hmm I do have a suspicion: I think the server physics might not be using the updated position depending when teleport is called. In general the teleport could probably use a rework to fully use the new movement. For the meantime I will see about forcing the position update for a patch.

**Comment by MrKanYT** [comment] 2021-11-21 16:33
I have a similar problem, but on a large scale. When teleporting to a location or player, teleports back several times. Many plugins that use different methods to teleport the player work strangely. Is it possible to fix this somehow?

**Comment by DiFFoZ** [comment] 2021-11-21 18:33
We don't see these problems on our servers.

**Comment by MrKanYT** [comment] 2021-11-21 18:54
As far as I understand, this does not happen if you stop for a couple of seconds before teleporting. https://youtu.be/M2w30H2ViyU

**Comment by SDGNelson** [comment] 2021-11-22 00:15
I tried teleporting around a lot (something like 50 times) yesterday but was not able to reproduce it. 😕
Are you using the vanilla teleport DiFFoZ?

**Comment by DiFFoZ** [comment] 2021-11-22 07:12
> Are you using the vanilla teleport DiFFoZ?

Yes

**Comment by PARTOVIY** [comment] 2021-11-23 07:38
When will you fix this bug? I cannot open the server because of it.

**Comment by SDGNelson** [comment] 2021-11-24 00:43
Yesterday I double-checked with 250ms lag, and today I tried with the server forced to a very low update rate. With or without Rocket I have not been able to reproduce it, and I also triple-checked that none of the default Rocket code is doing anything weird with teleportation or manually setting the player position.

The only thing I can think is that some plugin(s) are doing something unexpected like custom movement anti-cheat, or relying on the old client-authoritative movement, or teleporting the client without teleporting on the server.

If you try disabling your plugins does it happen? If it works normally without plugins, then you could try re-enabling a few at a time to narrow it down. Or if it does happen without plugins then if you can tell me about your setup maybe I can reproduce.

**Comment by PARTOVIY** [comment] 2021-11-24 09:02
I removed all plugins, but the problem still persists.
Tell me what files you need for debugging

https://youtu.be/9HVS_z-CvEI

**Comment by PARTOVIY** [comment] 2021-11-24 09:15
Now I put a PEI map instead of a mod, and the problem disappeared, but what should I do with the map?

**Comment by PARTOVIY** [comment] 2021-11-24 11:31
I completely reinstalled the server and still this problem persists. Even using the command / teleport

**Comment by PARTOVIY** [comment] 2021-11-24 12:09
Here is the mod map where these errors occur.

https://steamcommunity.com/sharedfiles/filedetails/?id=2123872854

**Comment by muertoof** [comment] 2021-11-24 12:19
the same crap when I use teleportToBed() or teleportToLocationUnsafe()

**Comment by SDGNelson** [comment] 2021-11-24 16:31
Thanks @PARTOVIY for giving that a try, I loaded up your map and was able to reproduce it when teleporting to the factory! Not sure yet what is causing it but will figure out today.

**Comment by PARTOVIY** [comment] 2021-11-24 17:17
Thanks for your feedback, I hope this can be quickly fixed

**Comment by SDGNelson** [comment] 2021-11-24 22:33
So. Sigh. The speculative fix from my earlier comment was not actually in the patch. 😧 That explains a lot. Sorry for all the hassle. ☹️

**Comment by PARTOVIY** [comment] 2021-11-25 20:32
Nelson, I didn't quite understand the comment. When will the fix for this issue be released?

**Comment by SDGNelson** [comment] 2021-11-26 00:13
It will be in tomorrow's update!

**Closed** 2022-06-01 05:57 UTC
