### ISSUE TITLE
Game not closing on Quit, rather staying open and crashing

### ISSUE THREAD

**Issue by RBMKBlaze** [SmartlyDressedGames/Unturned-3.x-Community#4284] opened 2023-12-24 10:06 UTC
Logfile (before quiting):
```
[2023-12-24 09:45:49] Applying graphics settings (changed water quality)
[2023-12-24 09:45:49] Applied graphics settings
[2023-12-24 09:45:49] Applying graphics settings (changed water quality)
[2023-12-24 09:45:49] Applied graphics settings
[2023-12-24 10:02:09] Quit game: clicked quit from in-game pause menu
[2023-12-24 10:02:09] Application quitting
[2023-12-24 10:02:09] Saved convenient data
[2023-12-24 10:02:09] Skipped saving blocked players
[2023-12-24 10:02:09] Disconnecting: application quitting
[2023-12-24 10:02:09] Submitted 1 item property update(s)
[2023-12-24 10:02:09] Shutting down BattlEye client
[2023-12-24 10:02:09] BattlEye client shutdown result: True
[2023-12-24 10:02:09] Client disconnect from 2823127475 result: True
[2023-12-24 10:02:09] Cancelled auth ticket
[2023-12-24 10:02:09] Disconnected
[2023-12-24 10:02:10] Finished quitting
```

Sometimes when i click Quit, my game isnt the focused window anymore rather minimizes, after tabbing back in it seems like its in a suspended/not responding state, after sending any input it crashes (UnityCrashHandler comes into play, it doesnt straight up close).

**Comment by SDGNelson** [comment] 2023-12-24 19:50
If you send input to any window the OS thinks isn't responding the OS will offer to force quit it. Looks like the game itself thinks it finished game-related quit activities in less than a second, so unclear why it's not closed. How long did you wait before clicking on it?

**Comment by RBMKBlaze** [comment] 2023-12-25 21:09
> If you send input to any window the OS thinks isn't responding the OS will offer to force quit it. Looks like the game itself thinks it finished game-related quit activities in less than a second, so unclear why it's not closed. How long did you wait before clicking on it?

Also the game didnt fully exit, i was still able to hear ambient noises, such as the burning torch in my base, the crickets,birds im not sure about shooting tho, will see tommorow.

**Comment by SDGNelson** [comment] 2023-12-27 19:59
Unfortunately, this might be a "won't fix" because I can't reproduce it, it has an easy workaround, and AFAIK it isn't happening for most players. It's too bad there wasn't an error in the log. 😞

**Closed** 2023-12-27 19:59 UTC
