### ISSUE TITLE
Muzzle emits only 1 particle

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1533] opened 2020-03-21 22:00 UTC
Have no idea if I am doing something wrong or its supposed to be limited. If I want a muzzle to emit i.e. 50 particles - in game it always emits only 1

Basically this is what I see in editor: https://streamable.com/qm35q
And this is what I get in game: https://streamable.com/m277k

**Comment by FalkenJr** [comment] 2020-03-22 03:15
It's """supposed""" to be limited, because the way the game handles muzzle effects requires one and only one particle system with fairly specific settings to work

A similar issue also exists with shell ejection effects, and the only solution I've been able to figure out is quite convoluted and hard to explain (I'm not sure if I even remember how I did it, it's that bad)

**Comment by SDGNelson** [comment] 2020-03-22 15:48
When you equip a gun the game spawns the muzzle effect, and each time you shoot it calls `ParticleSystem.Emit(1)`. I think the workaround for FalkenJr was to use a sub-emitter that spawns more particles? 

Given that a few modders have run into this it might be worth bringing up-to-date. I'll have to see if there is a straightforward way to trigger the burst(s) without restarting the system.

**Comment by FalkenJr** [comment] 2020-03-24 18:50
My workaround was a sub-emitter that emitted a completely nonexistent particle (render mode set to None) that would then emit several child Effect particle systems. The settings required to make them work properly are somewhat specific, mainly in the Emission drop down:
The 'master' particle system works like so:
![image](https://user-images.githubusercontent.com/23371589/77463768-89c76400-6ddc-11ea-9d7c-adf6c09dedca.png)
..and the 'child' particle systems have to have the same burst settings, but with their probability value set to anywhere above 0.00 (I used 1.00.)
Having the probability set to 0.00 on the 'master' effect prevents it from activating when spawned, but `ParticleSystem.Emit` will force it to fire an effect regardless. The 'master' effect then calls the 'child' systems and the effect plays hopefully as intended.

**Comment by SDGNelson** [comment] 2023-01-12 00:44
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.

**Closed by SDGNelson** 2023-01-12 00:44 UTC
