### ISSUE TITLE
Can no longer swap items

### ISSUE THREAD

**Issue by Tairiku-Ookami** [SmartlyDressedGames/Unturned-3.x-Community#2162] opened 2020-12-05 13:39 UTC
I can no longer pick up an item and drag it onto another item to swap their places in my inventory. This was such a useful feature please fix.

**Comment by SDGNelson** [comment] 2020-12-05 16:08
Sorry for the trouble, will be fixed in the .2 patch this morning (duplicate of #2155)

**Closed by SDGNelson** 2020-12-05 16:08 UTC
