### ISSUE TITLE
masterbundle overides not working after update.

### ISSUE THREAD

**Issue by jeremyvos11** [SmartlyDressedGames/Unturned-3.x-Community#3886] opened 2023-05-26 19:21 UTC
overriding vanilla items are not working when the update hit.
the item will be invisible and not usable by others.

**Comment by jeremyvos11** [comment] 2023-05-26 19:25
so i overwritten the vanilla antibiotics medical item, and when the update hit, it was invisible and not usable anymore.

**Comment by Jdance-Media** [comment] 2023-05-26 22:00
@jeremyvos11 Hi, are you using a `\` (backslash) in the overrides instead of a `/` (forward-slash)? It seems that the game now ignores/is unsuccessful when using blackslashes. For example, some masterbundles were not working when the `Asset_Prefix` was using blackslashes.

@SDGNelson I'm not sure if this blackslash issue applies to everything, but it seemed to apply to masterbundles, according to ZoliWorks. I know of quite a few mods that still use blackslashes, so might be worth looking into.

**Comment by SDGNelson** [comment] 2023-05-26 22:36
OP: could you attach the Client.log file after trying to load the item please? There might be an error message.

Multiple mods that were using backslashes in Asset_Prefix? I'm not sure why that would have changed because off the top of my head that shouldn't have worked in the first place - AFAIK Unity only supports forward slash in asset paths.

**Comment by Jdance-Media** [comment] 2023-05-26 22:52
It seems this tutorial is using backslashes, https://steamcommunity.com/sharedfiles/filedetails/?id=2859603823 Off the top of my head I did remember of instances of finding mods that used backslashes in overrides. Not sure about the `Asset_Prefix` though. I'm gonna go ahead and do some tests to confirm. 👍

*20 minutes later*

I changed one of my masterbundles to use backslashes in the `Asset_Prefix` and set the branch to unity-2019. 
`Asset_Prefix Assets\LastPoint`
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67397422/ddd3c356-8150-47ab-99b0-bb574568df91)
Backslashes did in fact work in the `Asset_Prefix` on the unity-2019 branch.

I switched back to the typical branch and backslashes result in my tower not being spawned in when pressing `E`.
`Asset_Prefix Assets\LastPoint`
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67397422/33085618-c3de-4687-8361-151b5de8058d)

**Comment by jeremyvos11** [comment] 2023-05-26 22:59
> 

i'm using backslashes for a long time now, after the update hit, it did not work anymore, so when you told me to use forward once, i changed it and now it works again, making it so it works both ways would be awsome

**Comment by Jdance-Media** [comment] 2023-05-26 23:37
Example of a mod using backslashes that was created in 2022.
https://steamcommunity.com/sharedfiles/filedetails/?id=2713981875
According Mr. Hamburger it was working before, but after this update, nada.
It has `Asset_Prefix Assets\40sbuildingsMasterBundle`

**Comment by SDGNelson** [comment] 2023-05-26 23:39
Thanks for the investigation! It looks like I added support for escaped newlines in unquoted strings on April 19th. I thought that was in the dat parser rewrite update, but instead it was a few days afterward. This is for text that had `\n` in it as a new line. The rewrite did have escapes for `\"` and `\n` but only in quoted strings.

One option for backwards compatibility would be to treat `\` without a recognized next character as backslash, but that may be problematic in the future because there are some other escape sequences that might be useful like `\t` or `\u+####`.

If there are a lot of mods using `\` then the unrecognized escape workaround might be necessary. I guess we'll see how many creators bring it up. 🤔

**Comment by JpVanillaVehicles** [comment] 2023-05-27 01:00
I'm guessing it'll be an issue with older mods that don't get support now, updating it is not much of an issue, all my mods broke for a while but it's fixable, but who knows how many mods will be affected by this D:

**Comment by JpVanillaVehicles** [comment] 2023-05-27 01:09
Well and every commission I've made so far has the backlash so that's going to be annoying to fish, tbh

**Comment by Jdance-Media** [comment] 2023-05-27 01:29
Advisory list for players, I've had a program sort through a bunch of popular mods so far. I went through a lot of mods only to get eight, most were just people using the wrong type of slash for comments 🤣. Perhaps it is fine to make backslashes obsolete.
<details>
  <summary>Advisory List, includes mods affected.</summary>
https://steamcommunity.com/sharedfiles/filedetails/?id=2972744435 (had the issue, received an update to fix it, confirmed by Jp).
https://steamcommunity.com/sharedfiles/filedetails/?id=2726825602 (will be receiving an update from Jp).
https://steamcommunity.com/sharedfiles/filedetails/?id=2910303283 (another Zoliworks mod).
https://steamcommunity.com/sharedfiles/filedetails/?id=2152811193 (likely getting fixed by Jp).
https://steamcommunity.com/sharedfiles/filedetails/?id=2152811193 (likely getting fixed by Jp).
https://steamcommunity.com/sharedfiles/filedetails/?id=2152811193 (yet another Jp mod, lol).
https://steamcommunity.com/sharedfiles/filedetails/?id=2073926683 (I swear, this update only affects Jp).
https://steamcommunity.com/sharedfiles/filedetails/?id=2210332740 (Jp, again).
</details>

**Comment by ZoliWorks** [comment] 2023-05-27 11:43
Same here, I remember seeing them in some vanilla example so half my mods use \ slashes while the other half use / slashes

Seems like a lot of people are in the same boat and a lot of discussions are popping up in modding servers or even unturned official asking why their mods suddenly broke. It's not something hard to fix but there are cases where the author doesnt want to fix it, wont let people re-upload a fixed version, wont upload the fixed version themselves so the mod becomes unusable. This generally shouldnt be an issue but it can be if the mod is widely used and no longer supported by the author.

Backwards compatibility would be nice

**Comment by P9ndx** [comment] 2023-05-27 12:02
Basically all my mods use \ and so do most of the most I have used/seen. To be honest I thought you had to use \ otherwise it wouldn't work. **Please** do add backwards compatibility as it already broke so many mods that I and other players cant use anymore.

**Comment by jeremyvos11** [comment] 2023-05-27 12:26
i also found out that it also occurs when giving out reward trough npc’s via a quest, this means when talking to the npc for starting gear it should give you a reward, but this time it wil not give you anything since the \ was removed, so this means the mods that use this future is unavailable.

**Comment by SDGNelson** [comment] 2023-05-27 19:08
My apologies to everyone negatively affected by this. Later this afternoon I will release a patch to parse unrecognized escape sequences as-is and log a message with the line number. Note that this means certain existing paths are still incompatible:
`path\of\asset` is parsed as `path\of\asset` because neither `\o` or `\a` are valid escapes, but `path\to\asset` is parsed as `path    o\asset` because `\t` is a tab. The escapes supported (and used in vanilla assets) are: `\"`, `\t`, `\n`, `\\`

**Comment by SDGNelson** [comment] 2023-05-27 21:55
🤞 fingers crossed hopefully everything is working okay🤞

**Closed** 2023-05-29 17:41 UTC
Labels: Resolved on preview branch
