### ISSUE TITLE
PSA: 3.20.17 on the Preview Branch

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#2203] opened 2020-12-09 04:46 UTC
You can preview the next update on the public test branch.

Hopefully this will be the last of the UI issue sorted out. There are still a few things to do before Friday, but the known performance issues and bugs should be resolved.

Personally I do not see much of a difference between the uGUI default font (liberation sans) and IMGUI (arial), but the font has been changed to Arial.

### Added
- Per-storage horizontal inventory scrollbar.
- Light theme only color preference for rarity backdrops.

### Changed
- Revised text coloring and contrast throughout UI.
- Replaced uGUI default font with the IMGUI default font.
- Improved scaling of inventory grid sprites.
- Optimized creating and destroying basic UI elements by pooling them.
- Optimized initialization UI components before reparenting them.
- Improved performance opening large storage by time-slicing the item UI creation.
- Improved nearby inventory performance by time-slicing the refresh.
- Text chat entry field uses color preference rather than admin/gold colors.
- Loading screen bar uses foreground color preference rather than difficulty color.

### Fixed
- Hide menus off-screen for a single frame when they are enabled to hide uGUI activation artifacts.
- Second line of Chinese text in chat being truncated.
- Right-clicking outside item popup box now closes the popup.
- Several straggling hotkeys triggering while typing in text fields.
- Plugin UIs visible while finishing loading.
- Pooled UI list using cached viewport height causing a hitch after big data change.
- Exception in UI when picking up destroyed items.
- Hitch after death caused by skills menu refresh.
- Exception updating item icon after item was destroyed.
- Potential negative explosion damage multiplier.
- Right-click highlight for buttons.
- Removies entries from spawn tables editor.
- Vertical offset of drowning status icon.
- Buildable attachment to train carriages.
- Pressing escape to cancel pending chat message.
- Swapping items of different slot types within grid.

**Comment by aladairmaxwell** [comment] 2020-12-09 07:33
I've downloaded public test branch and there are no Arial font.

**Comment by aladairmaxwell** [comment] 2020-12-09 07:41
![image](https://user-images.githubusercontent.com/69295711/101599522-f2a64900-3a0a-11eb-8485-6344cb10d604.png)
Found that oxygen icon is above others. Is it ok?

**Comment by aladairmaxwell** [comment] 2020-12-09 07:56
Good to see Arial is back. I didn't like Liberation Sans at all. But why game logo is still the same?
![image](https://user-images.githubusercontent.com/69295711/101601031-326e3000-3a0d-11eb-8285-0aa9458915f8.png)

**Comment by Divisioniz** [comment] 2020-12-09 09:16
Found that the hotkey's are not working as intended, When binding items they bind in reverse order.
1st Medkit was supposed to bind to "key" no. 3
2nd Medkit was supposed to bind to "key" no. 4
3rd Medkit was supposed to bind to "key" no. 5
4th Medkit was supposed to bind to "key" no. 6
It the same for the rest of the keys.
![Screenshot 2020-12-09 114651](https://user-images.githubusercontent.com/47481002/101608548-e58f5700-3a16-11eb-88da-f7d756a90453.png)

**Comment by Divisioniz** [comment] 2020-12-09 09:20
Its gets worse.
![Uploading Screenshot 2020-12-09 121846.png…]()

**Comment by Divisioniz** [comment] 2020-12-09 09:20
It gets worse.
![Screenshot 2020-12-09 121846](https://user-images.githubusercontent.com/47481002/101610172-ede89180-3a18-11eb-85dc-cefea0929910.png)

**Comment by SDGNelson** [comment] 2020-12-09 16:14
@aladairmaxwell Thanks for the report about the oxygen icon, will fix. As for the logo it is using Arial.

@Divisioniz Thanks for the report! Will investigate... 🤔

**Comment by schelchok** [comment] 2020-12-09 17:30
> It gets worse, I tried to bind the Medkit's now its binding the Military Drums.
> ![Screenshot 2020-12-09 121846](https://user-images.githubusercontent.com/47481002/101610172-ede89180-3a18-11eb-85dc-cefea0929910.png)
> 
> Update: Its only a visual glitch inside the inventory, If you look at the hotbar its normal.
> ![Screenshot 2020-12-09 125529](https://user-images.githubusercontent.com/47481002/101614295-d52eaa80-3a1d-11eb-94f9-73dfa5e5e690.png)

Haha, hola Divi

**Comment by Pablo8241** [comment] 2020-12-09 21:26
Here are two small issues I found so far.
1. Items get highlighted when you hold left click on them, but when you hold right click, they don't.
2. Pressing Esc key while having the chat open, opens the menu, instead of just closing the chat.

**Comment by SDGNelson** [comment] 2020-12-10 02:06
Updated the beta branch with .254

Aside from bug fixes and misc improvements, most of the work today was on font legibility in a lot of different ways. For example the button sprites were reworked to provide contrast without shadows while pressed, so that text which already contrasts by color alone does not need shadows. Tomorrow I will continue this e.g. options for "good" (blue) and "bad" (orange) colors, shadow colors, further removing default uses of color, etc.

**Comment by warren39** [comment] 2020-12-10 02:12
How to host a Dedicated Server, which running this preview branch?

**Comment by SDGNelson** [comment] 2020-12-10 02:29
@warren39 it's on the preview branch, so it should be `-beta preview`

**Comment by warren39** [comment] 2020-12-10 02:33
Thanks! Its working now.

**Closed** 2020-12-15 04:59 UTC
Labels: PSA
