### ISSUE TITLE
Bugs with chat

### ISSUE THREAD

**Issue by nikiternak5269** [SmartlyDressedGames/Unturned-3.x-Community#4134] opened 2023-10-13 21:11 UTC
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/123768100/899b72d6-9351-4a99-8378-9579f972b642)
Through the message, it happens that the chat disappears - sometimes the message is not sent.

**Comment by SDGNelson** [comment] 2023-10-13 21:18
Thanks for the report! Is there a particular message that it happens repeatedly with? In particular, I wonder if some Russian letters are not getting measured properly. If there's an example Russian text chat message that causes it I can reproduce.

**Comment by nikiternak5269** [comment] 2023-10-13 21:27
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/123768100/d3f3c201-32b9-4799-978c-ba4a1ac16a94)
емае - This word is surprise, it happens that it is written, after which two invisible messages and then it was not sent at all. Then it went again

**Comment by Jdance-Media** [comment] 2023-10-13 21:47
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67397422/e2f196eb-95e3-403d-9ddf-953bde927170)
I can confirm that the issue regarding spacing and randomly blank messages is likely not from Russian characters as seen in this screenshot.

**Comment by SDGNelson** [comment] 2023-10-13 21:48
Thanks for the example. I tried posting it in chat in combinations with other random long paragraphs both English, and translated into Russian, but the chat blocks appeared normally. Considering that there have been reports of issues with some plugins after the update and it appears there's a chat-related plugin used in your screenshot, I wonder if you could try with the chat plugin turned off? It's certainly plausible (and likely) that it's related to the UI changes, but would be nice to have that out of the possibilities.

**Comment by SDGNelson** [comment] 2023-10-13 21:49
@Jdance-Media yikes! Are those each individual messages which should have an icon? Or is one of them a longer message with the barricade info?

**Comment by Jdance-Media** [comment] 2023-10-13 21:52
It is weird, some are longer messages/split into smaller messages for the command. None are using the ChatManager stuff, so no icons or any of that. It seems that some of the messages randomly blank out for no apparent reason.

**Comment by SDGNelson** [comment] 2023-10-13 22:02
@Jdance-Media I know Rocket had something to split long messages into multiple, is it using that? In the old version if there were line breaks in messages it would get clipped if outside the label, but now that it adjusts to the content size I wonder if those stray line breaks are expanding it.

**Comment by DanielWillett** [comment] 2023-10-14 02:21
It's not rocket, it happens on my server which doesn't use rocket.

**Comment by DanielWillett** [comment] 2023-10-14 02:23
Sometimes the messages are a bit to the left, sometimes they're just skipped, sometimes your messages you send don't show up at all.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/ec6beae4-f71c-4594-b482-6464f8dd6ea8)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/2e8afe6d-30bf-49d2-a8c0-73237dc6f512)

**Comment by DanielWillett** [comment] 2023-10-14 02:25
Side note, none of my messages are split or anything, they should be latin characters, I'm using uGUI at 2560x1440 (bugs were also happening on 1080p). Some of them are basic chat messages, some have rich text (TMPro tags like <#ffffff>, etc).

**Comment by CatzMR** [comment] 2023-10-14 05:00
After this update, Chinese characters in all logos are no longer available.

**Comment by DanielWillett** [comment] 2023-10-14 05:18
^^ Same with UIs using TMPro text components.

**Comment by GazziFX** [comment] 2023-10-14 06:32
Probably FontAssets needs to rebuild with new Unity

**Comment by Jdance-Media** [comment] 2023-10-14 13:42
Did a test command with UnturnedChat.Say and there was no visible issues.
```csharp
UnturnedChat.Say("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis knostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", Color.red);
UnturnedChat.Say("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt u", Color.gray);
UnturnedChat.Say("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt u", Color.cyan);
UnturnedChat.Say("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt u", Color.blue);
            
```

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67397422/4ed85088-c5e6-4d9e-9387-0e9f3a25155c)

Not sure what causes the problem to occur.

**Comment by SDGNelson** [comment] 2023-10-14 15:55
Thanks for the note about letters on signs! It looks like in early August after the LTS update the TMPro package needed to be updated, and so the extra fonts on the default font were lost. The game does automatically redirect the font used on signs, but I should make it redirect to one outside the TMPro folder so this doesn't happen again.

**Comment by wristcry** [comment] 2023-10-14 18:08
there is an exception getting thrown when this bug appears also

[2023-10-14 18:03:09] Exception invoking SDG.Unturned.ChatManager.ReceiveChatEntry from server:
[2023-10-14 18:03:09] Object reference not set to an instance of an object
[2023-10-14 18:03:09] at SDG.Unturned.GlazierElementBase_uGUI.set_UseChildAutoLayout (SDG.Unturned.ESleekChildLayout value) [0x0005c] in <b7cbb6067a694cbca55bf56a9fb3f9db>:0 
  at SDG.Unturned.SleekChatEntryV2..ctor () [0x00135] in <b7cbb6067a694cbca55bf56a9fb3f9db>:0 
  at SDG.Unturned.PlayerLifeUI.OnChatMessageReceived () [0x0004b] in <b7cbb6067a694cbca55bf56a9fb3f9db>:0 
  at SDG.Unturned.ChatManager.receiveChatMessage (Steamworks.CSteamID speakerSteamID, System.String iconURL, SDG.Unturned.EChatMode mode, UnityEngine.Color color, System.Boolean isRich, System.String text) [0x000b5] in <b7cbb6067a694cbca55bf56a9fb3f9db>:0 
  at SDG.Unturned.ChatManager.ReceiveChatEntry (Steamworks.CSteamID owner, System.String iconURL, SDG.Unturned.EChatMode mode, UnityEngine.Color color, System.Boolean rich, System.String text) [0x00000] in <b7cbb6067a694cbca55bf56a9fb3f9db>:0 
  at SDG.Unturned.ChatManager_NetMethods.ReceiveChatEntry_Read (SDG.Unturned.ClientInvocationContext& context) [0x0003f] in <b7cbb6067a694cbca55bf56a9fb3f9db>:0 
  at SDG.Unturned.ClientMessageHandler_InvokeMethod.ReadMessage (SDG.NetPak.NetPakReader reader) [0x0005b] in <b7cbb6067a694cbca55bf56a9fb3f9db>:0

**Comment by SDGNelson** [comment] 2023-10-14 19:11
Thanks @wristcry, this exception was reported in #4139 so I'm now optimistic that it should be resolved in the .2 patch!

**Comment by SDGNelson** [comment] 2023-10-15 18:15
Should be resolved now!

**Closed by SDGNelson** 2023-10-15 18:15 UTC
Labels: Resolved on preview branch
