### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by TomCzE1** [SmartlyDressedGames/Unturned-3.x-Community#2704] opened 2021-07-16 17:17 UTC
You can use skycrane´s electro magnet on vehicle that is on top of the skycrane. Also skycrane doesnt like when you electro magnet a skycrane to a skycrane.
https://www.youtube.com/watch?v=mkFf2BlQtVM

You can see through military barrier on Washington and Russia but not on Germany it may be cause due to barriers being placed separately instead of being placed altogether.
![Unturned 16 07 2021 15_57_20](https://user-images.githubusercontent.com/87533446/125979221-3e30795c-f9b3-460e-9c9c-59f44ff7a31f.png)

You can go through ladder when you crouch, eat or reload. This is probably not a bug.

Sometimes when you place barrier on vehicle in multiplayer it is invisible.

There is also one well known bug in the community the bug is called maplestrike.

Now giv beret pls

TomCzE_

**Comment by SDGNelson** [comment] 2021-07-16 19:52
Sorry, but the berets are not being given out anymore. While some of these are not ideal as-is, there are some limitations at the moment e.g. there is not a good way in Unity to have different collision results for the camera on different objects - hopefully after their new physics engine. If there is a reproducible way to place invisible barricades on vehicles please feel free to post because that is definitely a bug and should be fixed.

**Closed by SDGNelson** 2021-07-16 19:52 UTC
