### ISSUE TITLE
Using PIXEL_AVERAGE with smoothing tool on landscape tool in WIP devkit editor creates gaps between tiles

### ISSUE THREAD

**Issue by Hexadec1ma1** [SmartlyDressedGames/Unturned-3.x-Community#605] opened 2019-02-20 23:59 UTC
![20190220172518_1](https://user-images.githubusercontent.com/32914055/53133601-afcb6680-3541-11e9-87e2-3de5ba4e7b90.jpg)

**Comment by danaby2** [comment] 2019-02-21 16:03
this has been a problem for a while but honestly, i like it. Sure, its annoying but it can be fixed by setting smooth mode to BRUSH_AVERAGE and the size down and just going over the lines. this can also be used to create holes in the ground without hole volumes (less lag HYPE HYPE HYPE)

![image](https://user-images.githubusercontent.com/33376941/53182883-4192ac80-35f2-11e9-9070-4f0af2b279cf.png)

**Comment by khakers** [comment] 2019-02-21 18:17
It’s a feature not a bug™️

**Comment by SDGNelson** [comment] 2019-02-21 21:18
Sneaky trick @danaby2! The way the per-sample smoothing brush code is written I'm not sure how I want to deal with this off the top of my head, but I will do something... In the meantime (you probably already know this) there's a tool somewhere in there to repair mismatched tile boundaries.

**Comment by Hexadec1ma1** [comment] 2019-03-03 05:02
> In the meantime (you probably already know this) there's a tool somewhere in there to repair mismatched tile boundaries.

Which tool is this? I couldn't find anything that would work

**Comment by SDGNelson** [comment] 2019-03-04 22:36
My bad! These was one at some point, probably when I was working on the tools because initial versions had some bugs, but it appears to have been removed for whatever reason. I'll see if the code is still there to re-enable it

**Comment by SDGNelson** [comment] 2019-03-13 18:34
I hemmed and hawed looking at the pixel average smooth brush code deciding what to do about this, and then decided to procrastinate 👍

**Comment by danaby2** [comment] 2019-03-14 16:42
i love this comment so much

**Comment by SDGNelson** [comment] 2019-04-01 21:05
Finally fixed for the next update. Using any of the heightmap tools along a mismatched tile border should repair it for you after the update.

**Closed by SDGNelson** 2019-04-01 21:05 UTC
