### ISSUE TITLE
The game crashes after the latest update

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#4281] opened 2023-12-23 13:09 UTC
Hello, after the last update, while playing on the server the game started to crash. Crash log available.
The problem is observed among many players on the server. There is an assumption that the problem is in voice chat
[Crash_2023-12-21_201927402.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/13759140/Crash_2023-12-21_201927402.zip)

**Comment by surv0013** [comment] 2023-12-23 14:24
II have the same problem on my server, about 30% of players crash out of the game. In addition, sometimes voice chat stops working. The problem started immediately after updating the game to version 3.23.14.0. I figured it was because of my voice chat patch.
```
0x00007FF9E9E792B4 (mono-2.0-bdwgc) mono_lookup_icall_symbol
0x000001CB221567FB (Mono JIT Code) (wrapper managed-to-native) object:__icall_wrapper_mono_array_to_lparray (object)
0x000001CD3DC14EC3 (Mono JIT Code) (wrapper managed-to-native) Steamworks.NativeMethods:ISteamUser_DecompressVoice (intptr,byte[],uint,byte[],uint,uint&,uint)
0x000001CD3DC14DDB (Mono JIT Code) Steamworks.SteamUser:DecompressVoice (byte[],uint,byte[],uint,uint&,uint)
0x000001CD3DC14873 (Mono JIT Code) SDG.Unturned.PlayerVoice:AppendVoiceData (byte[],uint,bool)
0x000001CD3DC147CB (Mono JIT Code) SDG.Unturned.PlayerVoice:ReceivePlayVoiceChat (SDG.Unturned.ClientInvocationContext&)
0x000001CD3DC14613 (Mono JIT Code) SDG.Unturned.PlayerVoice_NetMethods:ReceivePlayVoiceChat_Read (SDG.Unturned.ClientInvocationContext&)
0x000001CD3DA9A54C (Mono JIT Code) SDG.Unturned.ClientMessageHandler_InvokeMethod:ReadMessage (SDG.NetPak.NetPakReader)
0x000001CC12D61B46 (Mono JIT Code) SDG.Unturned.NetMessages:ReceiveMessageFromServer (byte[],int,int)
0x000001CC12D5735B (Mono JIT Code) SDG.Unturned.Provider:listenClient ()
0x000001CC12D569B3 (Mono JIT Code) SDG.Unturned.Provider:listen ()
0x000001CB2212A49B (Mono JIT Code) SDG.Unturned.Provider:Update ()
0x000001C973DEFAC8 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007FF9E9FBFB54 (mono-2.0-bdwgc) mono_jit_set_domain
0x00007FF9E9EFE794 (mono-2.0-bdwgc) mono_object_get_virtual_method
0x00007FF9E9EFE92C (mono-2.0-bdwgc) mono_runtime_invoke
```

**Comment by SDGNelson** [comment] 2023-12-23 19:31
Sorry for the trouble, and thanks for the call stack. @surv0013 Can you elaborate on what you mean by your voice chat patch please? Is it a client change or server change?

**Comment by surv0013** [comment] 2023-12-23 22:07
> Can you elaborate on what you mean by your voice chat patch please?

I wrote about this:
```CS
[HarmonyPatch(typeof(PlayerVoice), "ReceiveVoiceChatRelay")]
```
I don't think the problem is in the patch because the data received from the player and transmitted to other players is **not edited** in this patch.

By the way, players have found a solution to the voice chat not working. To do this, you just need to disable "Keep Microphone Ready".

In general, based on the data (description of actions before the crash and logs) received from the players of my server, I came to the conclusion that due to the fact that the new parameter for voice chat in the game does not work correctly, voice message packets are not transmitted in full volume, which causes the impossibility of unpacking on the client side and leads to a crash of the game.

**Comment by SDGNelson** [comment] 2023-12-23 22:19
Oh hmm... Thanks for the input. I wonder if we should call `GetVoice` always when Keep Microphone Ready is enabled. Looking at it again it looks like it could easily crash in a different case if `GetAvailableVoice` returns a size larger than `COMPRESSED_VOICE_BUFFER` length. After testing that it seemed to be working I didn't worry about it further. This is why I should never change anything. 😦

**Comment by QERT2002** [comment] 2023-12-25 03:04
> Oh hmm... Thanks for the input. I wonder if we should call `GetVoice` always when Keep Microphone Ready is enabled. Looking at it again it looks like it could easily crash in a different case if `GetAvailableVoice` returns a size larger than `COMPRESSED_VOICE_BUFFER` length. After testing that it seemed to be working I didn't worry about it further. This is why I should never change anything. 😦

I confirm that after the update the game(client) crashed, sometimes with the stack provided by surv, sometimes after leaving the server the game(client) crashes, as I understand, a garbage collection error occurs on the stack.

Regarding “This is why I should never change anything.”, you shouldn’t say that, because any update is aimed at improving the game and some errors are just an excuse to fix them

**Comment by QERT2002** [comment] 2023-12-25 03:08
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/89f28f18-f9c8-41b9-94b1-b1dcf6cd1d30)

**Comment by SDGNelson** [comment] 2023-12-28 23:13
Hopefully this should be resolved in the .3 patch out now!

**Closed** 2024-01-08 19:10 UTC
Labels: Resolved on preview branch
