### ISSUE TITLE
Vehicles can be thrown away by player

### ISSUE THREAD

**Issue by TheMew0** [SmartlyDressedGames/Unturned-3.x-Community#4710] opened 2024-09-15 18:40 UTC
So, if you lay down on an edge of the collider of any vehicle, and quickly jump forward, it will result in vehicle flying away in the direction of your jump. It happens in multiplayer too.

https://github.com/user-attachments/assets/cba1160d-202a-4cd4-8602-3f7535040099

**Comment by GazziFX** [comment] 2024-09-15 21:19
Duplicate of https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/4680

**Comment by SDGNelson** [comment] 2024-09-15 23:02
The map and vehicle effects look really nice! Unfortunately, I'm not sure we have a great option for fixing this. Even before the latest update it was possible with moderate effort. Closing as duplicate for the meantime, thanks GazziFX.

**Closed by SDGNelson** 2024-09-15 23:02 UTC
