### ISSUE TITLE
(Debian - Steamcmd) Server unable to access Steam interface steamNetworkingUtils003/004 before SteamAPI_Init succeeded.

### ISSUE THREAD

**Issue by oliveirafrerulz** [SmartlyDressedGames/Unturned-3.x-Community#3627] opened 2023-01-04 15:09 UTC
Hi, I'm currently kind of a newby in Debian, and I'm trying to run a dedicated Unturned server on it, and when I launch it, everything seems fine, having no problems exept errors with "Shader Unsupported blahblahblah..." which, from what I know from running an Unturned server on Windows shouldn't be an issue, but then it eventually will say: 
`Linking blueprints...
Linking spawns...
Loading miscellaneous...
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: wrong ELF class: ELFCLASS32
[S_API] SteamAPI_Init(): Loaded '/home/fred/.steam/debian-installation/linux64/steamclient.so' OK.  (First tried local 'steamclient.so')
CAppInfoCacheReadFromDiskThread took 3 milliseconds to initialize
Setting breakpad minidump AppID = 304930
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
Waiting for Steam servers...
Steam servers ready!`
I can then connect to the server from it's public IP (also yes, all ports from 227015 - 27020 are forwarded and UFW was setup properly) it will load its info page with the map name, the server description and so on, but after it's done loading me in, it will instantly disconnect me with the message: "Lost connection to host or Steam Network", while if I try to connect to it via it's private IP, it will work. Sorry if this is a stupid question for stupid people, I am currently learning Debian so I'm not good at all troubleshooting it yet.

**Comment by SDGNelson** [comment] 2023-01-05 21:40
The underlying error is probably:
`dlopen failed trying to load: steamclient.so with error: steamclient.so: wrong ELF class: ELFCLASS32`

**Comment by oliveirafrerulz** [comment] 2023-01-05 22:26
Hi, so after you wrote that, I did a bit more research and followed steps to fix the steamclient.so error, but it still says 
`Loading miscellaneous...
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 3 milliseconds to initialize
Setting breakpad minidump AppID = 304930
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.`
and still appears to be broken (unable to connect to it outside of connecting to it VIA it's private IP), but I'm not sure if this has to do with the fact Unturned servers have to be left a long time before appearing on server list (and maybe it's impossible to connect to them when in that state so that's why it seems broken, because I didn't leave it on for long enough while testing this?), if it's unable to connect to something it needs for some reason or if I'm just dumb and missed something obvious?
Also thank you for your time.

**Comment by SDGNelson** [comment] 2023-01-08 22:45
Sorry, if it is still running into that issue after fixing the steamclient.so used I am not sure what to suggest. Could you attach the Server_ (id) .log file from the U3DS/Logs folder please? Will see if there are any other related errors.

**Comment by oliveirafrerulz** [comment] 2023-01-10 15:14
The most recent one [Server_QuebecReference.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10383897/Server_QuebecReference.log)
And the previous [Server_QuebecReference_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10383904/Server_QuebecReference_Prev.log)
Also (even though I greatly doubt this would be the cause of the issue in any way): While setting up and testing the server, I am running everything from an SSH session on my windows machine connecting to my Debian server (which shouldn't be an issue, I was able to setup and test my minecraft and terraria servers this way before running them directly on the machine without any problems) and my server is running with an i7-4770 and a GT610.
Finally, again, thank you for your time helping me with my major case of "being dumb".

**Comment by oliveirafrerulz** [comment] 2023-01-11 01:11
Yes, I can join locally but people outside my network can't connect to the server, but it's not a port/firewall problem, I even made sure to check this again and took the time to reorder UFW nicely, but UFW is setup so that any port from 27000 to 27039 on UDP and TCP are open for various source games on my server machine, and the same goes for my router, my ports have been properly forwaded for 27000 to 27039 for UDP and TCP to my server machine, so it shouldn't be an issue, I even have a terraria server that runs perfectly fine and works on that same machine, so I don't see where else the issue could be...

**Comment by SDGNelson** [comment] 2023-01-12 01:16
Hmm...

Maybe you can enable logging in your router and UFW to see if the requests are coming through? Though ISP-provided router might not have this unfortunately.

What other servers are you hosting? - Maybe there is a port conflict?

**Comment by oliveirafrerulz** [comment] 2023-01-12 14:59
I can't check all the exact requests from my router, but, I did try to use pktstat on my server, and when using any port checking tools online, I could see incoming connections to my public IP or domain name would be recieved by my server on the port 27015, but even if the connections are going towards my server properly and I have the dedicated unturned server running (from serverhelper to then launch headlessserver) running, it still won't work for some reason.
Right now, on that same machine, I'm running a Terraria (tModLoader) (port 7777) dedicated server (which functions) and a SSH connection (port 22) to my real computer. 
Also this might not be relevant, but while looking at the connections to my server, I noticed that an IP owned by valve was connecting to port 27023, and an [online guide](https://unturned.info/Server-Hosting/PortForwarding/) about Unturned server hosting does say that "Each Unturned server uses three consecutive ports while running. ... the third for communicating with the Steam backend services" so could it be that maybe my Unturned server, for some reason is trying to run on the wrong port by default?

**Comment by oliveirafrerulz** [comment] 2023-01-13 17:57
Update: I don't know why I didn't try this earlier: I opened my terraria server on port 27015 to check if the problem was really Unturned, and yep, it's definitely Unturned, the Terraria server can work perfectly fine using port 27015, so it's nota firewall or port issue.

**Comment by SDGNelson** [comment] 2023-01-13 20:56
Good idea checking Terraria on port 27015!

In that case it does sound like something wrong on the game side. Looking back over the issue comments I may have misread - is "[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded." still happening? If Steam is writing these to stdout/stderr that would explain why there were no errors in the game log file. Is there still some Steam-related error message in the terminal?

**Comment by oliveirafrerulz** [comment] 2023-01-14 01:02
Yes, the server still always says :
```
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
Setting breakpad minidump AppID = 304930
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
Waiting for Steam servers...
.... (Rocket stuff)
Steam servers ready!
Workshop install folder: /home/fred/.steam/debian-installation/steamapps/common/U3DS/Servers/QuebecReference/Workshop/Steam
1 workshop item(s) requested
[Server output.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10416266/Server.output.txt)

Submitting workshop query for 1 item(s)...
```
I also attached the .log file of the server and the "server output.txt" which is what the terminal would say to me when opening the server just in case you might need that? And again, thank you for your time and your patience. 
[Server_QuebecReference.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10416267/Server_QuebecReference.log)
[Server output.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10416268/Server.output.txt)

**Comment by SDGNelson** [comment] 2023-01-14 02:09
If anything, thanks for your patience! I appreciate that you are not annoyed with me by this point.

The Steam stderr message mentions SteamNetworkingUtils. Unturned only uses this in two places:
1. To enable network debug logging after successfully initializing the Steam API.
2. The ban command. (this is old and a mistake, I have now made a note to remove it for the next update)

It's also weird that SteamNetworkingUtils004 is mentioned because the current version used in Unturned is 003.

Looking it up online it seems like this goes back to the steamclient.so problem. What did you end up doing to fix that?

**Comment by oliveirafrerulz** [comment] 2023-01-14 15:43
Oh boy, I remember having that issue but not exactly how I fixed it, but looking at my search history, I think the solution I ended up with was copying steamclient.so from /.steam/sdk64 to .steam/steam/linux64? There's also a steamclient.so in my /.steam/steam/steamapps/common/U3DS/ folder, which I'm not sure if it was there when I first downloaded the server (but I did update it using steamcmd since, so that might be why?) since I remember clearly having the steamclient.so issue in the past.

**Comment by SDGNelson** [comment] 2023-01-15 18:12
When downloading the game steamcmd will automatically install the steamclient.so (32-bit) in U3DS and linux64/steamclient.so. Sometimes there are problems with this copy though. If you copy steamclient.so from steamcmd/linux64 to U3DS/linux64 does it work?

That steamcmd folder layout sounds different - are you using steamcmd, or something different like game server manager or pterodactyl?

**Comment by oliveirafrerulz** [comment] 2023-01-16 03:30
I'm using steamcmd with all default settings no forced directory download location changes or anything.
I also did what you said, but the server still won't properly function and it still ends up saying
```
Setting breakpad minidump AppID = 304930
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
```
I think it might try and fully uninstall U3DS + Steamcmd from my server, and reinstall them fully from scratch, keeping nothing but the "/U3DS/Servers/" files on my next day off to see if something might've been wrong with my files somehow, because otherwise I don't see where else an issue could even be left at this point.

**Comment by SDGNelson** [comment] 2023-01-16 18:38
Hopefully reinstall helps. Otherwise I am out of ideas to suggest, sorry. :(

**Comment by SDGNelson** [comment] 2023-01-20 16:33
Any luck with reinstalling?

**Comment by SDGNelson** [comment] 2023-01-22 23:37
Closing for now, but feel free to comment and I will re-open.

**Closed by SDGNelson** 2023-01-22 23:37 UTC

**Comment by CodingDaniel1** [comment] 2023-06-14 10:54
Hello,

im also issuing with this, 

All of my servers wont work, because [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.

I could see my server on the server list but no one can join

Ive tried to re-install the server completely but it seems not work at all, im still getting this weird error, Ive tried multiple dedicated servers on my linux machine but non of that works due to this error

**Comment by CodingDaniel1** [comment] 2023-06-14 10:57
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/128029805/7ad7dbc7-14ab-48e2-ba98-37c46ba41f14)

**Comment by SDGNelson** [comment] 2023-06-16 07:01
@CodingDaniel1 it looks like the problem is probably the missing steamservice.so error. Are you using SteamCMD? May be worth validating the install in case a file is missing.
