### ISSUE TITLE
Item duping

### ISSUE THREAD

**Issue by Rubberduck63** [SmartlyDressedGames/Unturned-3.x-Community#3049] opened 2022-02-21 21:28 UTC
I made a issue on a invincibility glitch (https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3047) and it turns out this is much worse  than a 1 time glitch.  I replicated again using a virtual machine, and it turns out you can dupe whole invetorys of items with this.  I thought it would be more appropriate to make a new issue rather than just adding on to the old one.  I sent you nelson a video of this glitch on nelson@smartlydressedgames.com  (the email on gmail).  Just to clarify that this isnt a one time glitch, my friend gave me a avenger, i logged on to it with one account, joined with the other tab of unturned open, then rejoined with the other one and you will have a 2nd avenger you can drop.  For one of the screens, it will look like you have civilian nightvision on and you can go down to 0 hp but no further (god mode).  I hope this helps.   My account name as said in the email is either dirtdan7122 or fdmonroe

**Comment by Rubberduck63** [comment] 2022-02-21 21:28
(my account name for steam)

**Comment by SDGNelson** [comment] 2022-02-22 00:43
Thanks, closing as duplicate of #3047 and will respond there

**Closed by SDGNelson** 2022-02-22 00:43 UTC
