### ISSUE TITLE
GUI elements misalignment 

### ISSUE THREAD

**Issue by gegtor** [SmartlyDressedGames/Unturned-3.x-Community#2157] opened 2020-12-05 03:39 UTC
I really like the new GUI especially the chat which now properly disappears after few seconds when rich text is used by the plugins

Anyway I found this small bug where basically any table would not match the table items in the GUI by length 
OS: macOS 11.1
Screen resolution: 2880 × 1800
<img width="354" alt="Screenshot 2020-12-04 at 23 14 44" src="https://user-images.githubusercontent.com/10978723/101232680-43d4d680-36b3-11eb-92aa-d65bc73dbf77.png">

**Comment by SDGNelson** [comment] 2020-12-05 03:46
Happy you like the new GUI! This particular case has been fixed (duplicate of #2122) for the .2 patch coming tomorrow morning, but if there is another similar case please let me know and I will fix

**Closed by SDGNelson** 2020-12-05 03:46 UTC

**Comment by gegtor** [comment] 2020-12-05 03:48
Sorry for the duplicate i was looking at open issues before opening this one

Also, new chat shadows etc are very nice please don't change them :3
